### PR TITLE
Fix scroll bar / resize handle flicker in selection panel

### LINKED ISSUE #11347: Timeline separation line flickers when hovering between horizontal selection panel scroll & timeline resize handle
see clunky title. Or better see video:

https://github.com/user-attachments/assets/da455e1d-5e8f-4591-88ec-6d8cbb55952d

### PR DESCRIPTION
**Pull request by kratos2377**
Closes #11347 

Screen Recording from my local:

https://github.com/user-attachments/assets/a696bb31-fe45-4eed-b685-e2fce0fd8155

### CODE REVIEW

**Comment by kratos2377** [comment]
@Wumpf Could you please take a look at this PR when you have a moment.

**Comment by Wumpf** [comment]
Looks like this causes a small black gap? Pinged more egui-confident people than myself to have a look :)

File: crates/viewer/re_selection_panel/src/selection_panel.rs [hunk 1]
```diff
@@ -64,6 +64,10 @@ impl SelectionPanel {
             .resizable(true)
             .frame(egui::Frame {
                 fill: ui.style().visuals.panel_fill,
+                inner_margin: egui::Margin {
+                    bottom: 4,
```
Comment (lucasmerlin) [inline crates/viewer/re_selection_panel/src/selection_panel.rs]:
```suggestion
                    // TODO(emilk/egui#7749): This is a workaround to prevent flicker between
                    // the time panel resize handle and our scroll bar.
                    bottom: 4, 
```
