### PR TITLE
Always codegen queries that contain `InstanceKey`

### LINKED ISSUE #3294: Crash when changing visible history of depth image
**Describe the bug**
When changing the visible history of a depth image the viewer crashes with
```
thread 'ThreadId(1)' panicked at 'assertion failed: components.contains(&cluster_key)', re_query/src/range.rs:187

   6: core::panicking::panic_fmt
             at core/src/panicking.rs:67:14
   7: core::panicking::panic
             at core/src/panicking.rs:117:5
   8: re_query::range::range_archetype
   9: re_query::util::query_archetype_with_history


Troubleshooting Rerun: https://www.rerun.io/docs/getting-started/troubleshooting
Report bugs: https://github.com/rerun-io/rerun/issues
```

**To Reproduce**

```python
import rerun as rr
import rerun.experimental as rr2
import numpy as np

rr.init("depth_history", spawn=True)
depth_images = np.random.rand(100,480,640)
for i, depth_image in enumerate(depth_images):
    rr.set_time_seconds("time", i*0.1) 
    rr2.log("depth_image", rr2.DepthImage(depth_image))
```

**Expected behavior**
When backprojected with transformations it would be nice if the accumulated point cloud were visible. Otherwise this feature is not as important, but the crash is still annoying.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Rerun version**
```
rerun_py 0.9.0-alpha.4 [rustc 1.72.0 (5680fa18f 2023-08-23), LLVM 16.0.5] x86_64-unknown-linux-gnu 7db7b54, built 2023-09-12T08:50:21Z
```

### PR DESCRIPTION
**Pull request by teh-cmc**
All our internal queries expect instance keys to be present in the results, whether they use them or not.
And since queries have to be crafted at compile-time, we need to make sure it's there when codegen'ing our builtin archetypes.

Fixes:
- #3294

image

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested [demo.rerun.io](https://demo.rerun.io/pr/3310) (if applicable)

- [PR Build Summary](https://build.rerun.io/pr/3310)
- [Docs preview](https://rerun.io/preview/4549fb5e2ed3bba0102083c6f8076283bf97faec/docs) 
- [Examples preview](https://rerun.io/preview/4549fb5e2ed3bba0102083c6f8076283bf97faec/examples) 
- [Recent benchmark results](https://ref.rerun.io/dev/bench/)
- [Wasm size tracking](https://ref.rerun.io/dev/sizes/)

### CODE REVIEW

File: crates/re_types_builder/src/codegen/rust/api.rs [hunk 1]
```diff
@@ -768,16 +768,20 @@ fn quote_trait_impls_from_obj(
...
+                let mut components = iter_archetype_components(obj, attr)
                     .map(|fqname| {
                         objects[fqname.as_str()]
                             .try_get_attr::<String>(crate::ATTR_RERUN_LEGACY_FQNAME)
                             .unwrap_or(fqname)
                     })
                     .chain(extras)
                     .collect::<Vec<_>>();
+                components.sort();
+                components.dedup();
```
Comment (emilk) [inline crates/re_types_builder/src/codegen/rust/api.rs:780]: nit: could be shorter and clearer with

```suggestion
                    .collect::<BTreeSet<_>>();
```

**Review by emilk — APPROVED** [review]
