### PR TITLE
Fix crash in save-to-file

### LINKED ISSUE #1888: Crash when saving ar kit scene
`python3 ./examples/python/arkitscenes/main.py` on latest. Trying to save from the ui gives me a crash. Callstack:

```
thread 'ThreadId(1)' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArgumentError("Chunk require all its arrays to have an equal number of rows")', arrow2-0.16.0/src/chunk.rs:19

   8: core::panicking::panic_fmt
             at core/src/panicking.rs:64:14
   9: core::result::unwrap_failed
             at core/src/result.rs:1791:5
  10: core::result::Result<T,E>::unwrap
             at core/src/result.rs:1113:23
      arrow2::chunk::Chunk<A>::new
             at arrow2-0.16.0/src/chunk.rs:19:9
  11: re_log_types::data_table::DataTable::serialize
             at re_log_types/src/data_table.rs:619:21
  12: re_log_types::data_table::DataTable::to_arrow_msg
             at re_log_types/src/data_table.rs:1039:31
      re_viewer::app::save_database_to_file::{{closure}}
             at re_viewer/src/app.rs:1788:13
      core::iter::adapters::map::map_try_fold::{{closure}}
             at core/src/iter/adapters/map.rs:91:28
      core::iter::traits::iterator::Iterator::try_fold
             at core/src/iter/traits/iterator.rs:2238:21
      <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::try_fold
             at core/src/iter/adapters/chain.rs:78:19
  13: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at core/src/iter/adapters/map.rs:117:9
      <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::try_fold
             at core/src/iter/adapters/mod.rs:195:9
      core::iter::traits::iterator::Iterator::try_for_each
             at core/src/iter/traits/iterator.rs:2299:9
      <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next
             at core/src/iter/adapters/mod.rs:178:9
      alloc::vec::Vec<T,A>::extend_desugared
             at alloc/src/vec/mod.rs:2848:35
      <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at alloc/src/vec/spec_extend.rs:17:9
  14: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at alloc/src/vec/spec_from_iter_nested.rs:43:9
      <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at alloc/src/vec/spec_from_iter.rs:33:9
  15: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at alloc/src/vec/mod.rs:2748:9
      core::iter::traits::iterator::Iterator::collect
             at core/src/iter/traits/iterator.rs:1836:9
      <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::{{closure}}
             at core/src/result.rs:2075:49
      core::iter::adapters::try_process
             at core/src/iter/adapters/mod.rs:164:17
      <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter
             at core/src/result.rs:2075:9
      core::iter::traits::iterator::Iterator::collect
             at core/src/iter/traits/iterator.rs:1836:9
      re_viewer::app::save_database_to_file
             at re_viewer/src/app.rs:1783:40
      re_viewer::app::save
             at re_viewer/src/app.rs:1530:23
  16: re_viewer::app::App::run_command
      re_viewer::app::App::run_pending_commands
             at re_viewer/src/app.rs:244:13
      <re_viewer::app::App as eframe::epi::App>::update
             at re_viewer/src/app.rs:580:9
  17: eframe::native::epi_integration::EpiIntegration::update::{{closure}}
             at eframe-0.21.3/src/native/epi_integration.rs:454:13
      egui::context::Context::run
             at egui-0.21.0/src/context.rs:286:9
  18: eframe::native::epi_integration::EpiIntegration::update
             at eframe-0.21.3/src/native/epi_integration.rs:452:27
  19: <eframe::native::run::wgpu_integration::WgpuWinitApp as eframe::native::run::WinitApp>::paint
             at eframe-0.21.3/src/native/run.rs:1223:21
  20: eframe::native::run::run_and_return::{{closure}}
             at eframe-0.21.3/src/native/run.rs:144:17
  21: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event::{{closure}}
      winit::platform_impl::platform::app_state::EventLoopHandler<T>::with_callback
             at winit-0.28.1/src/platform_impl/macos/app_state.rs:70:13
      <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event
             at winit-0.28.1/src/platform_impl/macos/app_state.rs:91:9
  22: winit::platform_impl::platform::app_state::Handler::handle_nonuser_event
             at winit-0.28.1/src/platform_impl/macos/app_state.rs:199:21
  23: winit::platform_impl::platform::app_state::AppState::cleared
             at winit-0.28.1/src/platform_impl/macos/app_state.rs:388:13
      winit::platform_impl::platform::observer::control_flow_end_handler::{{closure}}
             at winit-0.28.1/src/platform_impl/macos/observer.rs:79:21
      winit::platform_impl::platform::observer::control_flow_handler::{{closure}}
             at winit-0.28.1/src/platform_impl/macos/observer.rs:41:9
      std::panicking::try::do_call
             at std/src/panicking.rs:483:40
      std::panicking::try
             at std/src/panicking.rs:447:19
  24: std::panic::catch_unwind
             at std/src/panic.rs:137:14
      winit::platform_impl::platform::event_loop::stop_app_on_panic
             at winit-0.28.1/src/platform_impl/macos/event_loop.rs:245:11
      winit::platform_impl::platform::observer::control_flow_handler
             at winit-0.28.1/src/platform_impl/macos/observer.rs:39:5
      winit::platform_impl::platform::observer::control_flow_end_handler
             at winit-0.28.1/src/platform_impl/macos/observer.rs:74:9
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: winit::platform_impl::platform::event_loop::EventLoop<T>::run_return::{{closure}}
             at winit-0.28.1/src/platform_impl/macos/event_loop.rs:220:22
      objc2::rc::autorelease::autoreleasepool
             at objc2-0.3.0-beta.3/src/rc/autorelease.rs:313:5
      winit::platform_impl::platform::event_loop::EventLoop<T>::run_return
             at winit-0.28.1/src/platform_impl/macos/event_loop.rs:211:25
  36: <winit::event_loop::EventLoop<T> as winit::platform::run_return::EventLoopExtRunReturn>::run_return
             at winit-0.28.1/src/platform/run_return.rs:51:9
      eframe::native::run::run_and_return
             at eframe-0.21.3/src/native/run.rs:124:5
  37: eframe::native::run::wgpu_integration::run_wgpu::{{closure}}
             at eframe-0.21.3/src/native/run.rs:1410:17
      eframe::native::run::with_event_loop::{{closure}}
             at eframe-0.21.3/src/native/run.rs:108:9
      std::thread::local::LocalKey<T>::try_with
             at std/src/thread/local.rs:446:16
      std::thread::local::LocalKey<T>::with
             at std/src/thread/local.rs:422:9
  38: eframe::native::run::with_event_loop
             at eframe-0.21.3/src/native/run.rs:101:5
      eframe::native::run::wgpu_integration::run_wgpu
             at eframe-0.21.3/src/native/run.rs:1407:13
  39: eframe::run_native
             at eframe-0.21.3/src/lib.rs:207:13

Troubleshooting Rerun: https://www.rerun.io/docs/getting-started/troubleshooting
```

### PR DESCRIPTION
**Pull request by teh-cmc**
Fixes #1888

### CODE REVIEW

File: crates/re_arrow_store/src/store_dump.rs [hunk 1]
```diff
@@ -89,7 +89,7 @@ impl DataStore {
                     col_timelines: [(*timeline, col_time.iter().copied().map(Some).collect())]
                         .into(),
                     col_entity_path: std::iter::repeat_with(|| table.ent_path.clone())
-                        .take(table.num_rows() as _)
+                        .take(bucket.num_rows() as _)
```
Comment (teh-cmc) [inline crates/re_arrow_store/src/store_dump.rs:92]: though that's a reentrant read and and we know where that leads with parking_lot so... let's not

**Review by Wumpf — APPROVED** [review]
