### PR TITLE
Fix clearing mesh3d causing a warning

### LINKED ISSUE #6355: Clearing a `Mesh3D` prints a warning
Repro:
```rust
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let rec = rerun::RecordingStreamBuilder::new("rerun_example_mesh3d").spawn()?;

    rec.log(
        "triangle",
        &rerun::Mesh3D::new([[0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [0.0, 1.0, 0.0]])
            .with_vertex_normals([[0.0, 0.0, 1.0]])
            .with_vertex_colors([0xFF0000FF, 0x00FF00FF, 0x0000FFFF]),
    )?;

    rec.log("triangle", &rerun::Clear::recursive())?;

    Ok(())
}
```

As soon as the clear kicks in:
```
[2024-05-16T12:48:27Z WARN  re_space_view_spatial::mesh_cache] Failed to load mesh "/triangle": Failed to transfer data to the GPU: Attempting to allocate an empty buffer. -> Attempting to allocate an empty buffer.
```

### PR DESCRIPTION
**Pull request by Wumpf**
### What

* Fixes #6355

... and improve re_renderers internal error messaging a little bit.
Guess we could react to re_renderer's errors directly instead of doing a separate check, but I found it cleaner 🤷 

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using examples from latest `main` build: [rerun.io/viewer](https://rerun.io/viewer/pr/6361?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [rerun.io/viewer](https://rerun.io/viewer/pr/6361?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!

- [PR Build Summary](https://build.rerun.io/pr/6361)
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

File: crates/re_space_view_spatial/src/visualizers/meshes.rs [hunk 1]
```diff
@@ -67,6 +67,13 @@ impl Mesh3DVisualizer {
             let picking_instance_hash = re_entity_db::InstancePathHash::entity_all(entity_path);
             let outline_mask_ids = ent_context.highlight.index_outline_mask(Instance::ALL);
 
+            // Skip over empty meshes.
+            // Note that we can deal with zero normals/colors/texcoords/indicies just fine (we generate them),
```
Comment (teh-cmc) [inline crates/re_space_view_spatial/src/visualizers/meshes.rs:71]:
```suggestion
// Note that we can deal with zero normals/colors/texcoords/indices just fine (we generate them),

**Review by teh-cmc — APPROVED** [review]
