### PR TITLE
Fix broken 2D Space View heuristics in Python Notebooks

### LINKED ISSUE #5654: Spatial heuristics are broken when when run inside a notebook
This is impacting at least 0.14.1

To repro, run the following in a notebook:
```
import rerun as rr
import numpy as np

rr.init("rerun_example_images")

image1 = np.zeros((200, 300, 3), dtype=np.uint8)
image1[:, :, 0] = 255

image2 = np.zeros((200, 300, 3), dtype=np.uint8)
image2[:, :, 1] = 255

image3 = np.zeros((400, 500, 3), dtype=np.uint8)
image3[:, :, 2] = 255

rec = rr.memory_recording()

rr.log("vrs/a", rr.Image(image1))
rr.log("vrs/b", rr.Image(image2))
rr.log("vrs/c", rr.Image(image3))

rec
```

See that the heuristics incorrectly stack the image:
image

Whereas the expected behavior is to have them split
image

## Theory
Based on initial investigation my best through is the SpatialTopology store subscriber is getting confused when used with `stream_rrd_from_event_listener`, which is only used for injecting data into the viewer from notebooks.

I strongly suspect it's missing messages. Possibly related to store-subscriber initialization timing?

### PR DESCRIPTION
**Pull request by Wumpf**
### What

* Fixes #5654

could in theory affect also non-notebooks, but practically in only manifested there.
Fixes a few typos I encountered on the way and added a new pixi command for building the rerun webviewer wasm.

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using newly built examples: [app.rerun.io](https://app.rerun.io/pr/5674/index.html)
  * Using examples from latest `main` build: [app.rerun.io](https://app.rerun.io/pr/5674/index.html?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [app.rerun.io](https://app.rerun.io/pr/5674/index.html?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!

- [PR Build Summary](https://build.rerun.io/pr/5674)
- [Docs preview](https://rerun.io/preview/618e0091e723020b96d06445d36c51c14a9067e3/docs) 
- [Examples preview](https://rerun.io/preview/618e0091e723020b96d06445d36c51c14a9067e3/examples) 
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

### CODE REVIEW

File: crates/re_space_view_spatial/src/space_view_2d.rs [hunk 1]
```diff
@@ -410,7 +411,7 @@ fn recommended_space_views_with_image_splits(
             }
         }
     } else {
-        // Otherwise we can use the space as it is
+        // Otherwise use
```
Comment (teh-cmc) [inline crates/re_space_view_spatial/src/space_view_2d.rs:414]: use what?

**Review by teh-cmc — APPROVED** [review]
