### PR TITLE
Fix selection history right-click menu not working

### LINKED ISSUE #1639: Selecting selection from selection history does not work
**Describe the annoyance**
In the viewer when right clicking on the selection history arrows, it's not possible to select any of the items. I.e., you can view the history but not use it to navigate.

**Expected behavior**
Should change to the clicked on selection.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

### PR DESCRIPTION
**Pull request by teh-cmc**
https://github.com/rerun-io/rerun/assets/2910679/733bffef-5f52-4152-9e82-1b570af66a0e

- Fixes #1639

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested [demo.rerun.io](https://demo.rerun.io/pr/3819) (if applicable)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG

- [PR Build Summary](https://build.rerun.io/pr/3819)
- [Docs preview](https://rerun.io/preview/7fa62f8319321b10df31d39de3d294ba946cc20a/docs) 
- [Examples preview](https://rerun.io/preview/7fa62f8319321b10df31d39de3d294ba946cc20a/examples) 
- [Recent benchmark results](https://ref.rerun.io/dev/bench/)
- [Wasm size tracking](https://ref.rerun.io/dev/sizes/)

### CODE REVIEW

File: crates/re_viewer/src/ui/selection_history_ui.rs [hunk 1]
```diff
@@ -42,12 +42,17 @@ impl SelectionHistoryUi {
                     item_collection_to_string(blueprint, &previous.selection),
                 ));
 
+            let mut return_current = false;
             let response = response.context_menu(|ui| {
                 // undo: newest on top, oldest on bottom
                 for i in (0..history.current).rev() {
                     self.history_item_ui(blueprint, ui, i, history);
                 }
+                return_current = true;
```
Comment (emilk) [inline crates/re_viewer/src/ui/selection_history_ui.rs:51]: this will return the current selection even if the user does not click an item in the list - is this intended?

Comment (teh-cmc) [reply crates/re_viewer/src/ui/selection_history_ui.rs:51]: Yeah, selecting the current thing is a no-op.

We could add an extra check just in case I guess :shrug:

**Review by emilk — APPROVED** [review]
