### PR TITLE
Fix rectangle that indicates the zoomed pixel area on hover being one  pixel to small

### LINKED ISSUE #3074: Image zoom rectangle is off by one pixel
**Describe the bug**
Follow up on #2236. The center is correct now, but the right and bottom border are off one pixel in the little preview, compared to the box overlay shown in the image.

Note the black row / column showing up, while the white border aligns with the image boundary.

https://github.com/rerun-io/rerun/assets/9785832/cd98d047-1973-4b12-b71d-7141cc1ac504

**Rerun version**
```
rerun_py 0.8.0 [rustc 1.69.0 (84c898d65 2023-04-16), LLVM 15.0.7] x86_64-unknown-linux-gnu main df05f49, built 2023-07-27T17:36:23Z
```

### PR DESCRIPTION
**Pull request by Wumpf**
### What

* Fixes #3074

The outlines of the zoomed rectangle that we super-impose on the 2D space view were off by one pixel

Before:
Screenshot 2023-12-19 174351
Note how the rectangle on the picture is smaller than the zoomed-preview (zoomed out in this case)

After:
Screenshot 2023-12-19 175201
Note how the rectangle on the picture is identically to the zoomed-preview. The hover overlay hasn't changed, but a different pixel is hovered and the rect is correctly sized now

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [ ] I have tested the web demo (if applicable):
  * Using newly built examples: [app.rerun.io](https://app.rerun.io/pr/4590/index.html)
  * Using examples from latest `main` build: [app.rerun.io](https://app.rerun.io/pr/4590/index.html?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [app.rerun.io](https://app.rerun.io/pr/4590/index.html?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG

- [PR Build Summary](https://build.rerun.io/pr/4590)
- [Docs preview](https://rerun.io/preview/4b0954988c67c9227677ff8609dd231737bf929a/docs) 
- [Examples preview](https://rerun.io/preview/4b0954988c67c9227677ff8609dd231737bf929a/examples) 
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

### CODE REVIEW

File: crates/re_data_ui/src/image.rs [hunk 1]
```diff
@@ -503,10 +503,12 @@ pub fn show_zoomed_image_region_area_outline(
     let height = height as f32;
 
     // Show where on the original image the zoomed-in region is at:
+    // The aread shown is ZOOMED_IMAGE_TEXEL_RADIUS _surrounding_ the center.
```
Comment (teh-cmc) [inline crates/re_data_ui/src/image.rs:506]:
```suggestion
    // The area shown is ZOOMED_IMAGE_TEXEL_RADIUS _surrounding_ the center.

**Review by teh-cmc — APPROVED** [review]
