### PR TITLE
Reduce number of unwrap calls and make clippy warning for it opt-out per crate

### LINKED ISSUE #3408: Forbid `unwrap()` in our code
All `unwrap()`s will eventually cause a panic. For example:
* https://github.com/rerun-io/rerun/issues/3270
* https://github.com/rerun-io/rerun/issues/3393

If you can prove the `unwrap()` cannot happen, then you can often rewrite it in a way to avoid the `unwrap()`. If you can't: add a comment explaining why it is impossible and/or replace it with `unreachable!()`.

I suggest we turn on `clippy::unwrap_used` to enforce this.
Right now there are too many `unwrap()`s (~350) to make this feasible, and that scares me. Those are crashes waiting to happen.

So the first step is to start removing `unwraps` in our code.

* For tests we can add `#[allow(clippy::unwrap_used)]` or use `?` instead.
* For examples we should use `?` instead.
* For production code we should use `?` or `.unwrap_or_warn` or similar.

We should also:
* Remove and the `try_` prefixes of functions

We can start working on this on a per-crate basis, e.g. adding `#![warn(clippy::unwrap_used)]` to `crates/re_types/src/lib.rs` first, and then take it from there.

### PR DESCRIPTION
**Pull request by Artxiom**
### What
Resolves #3408: Remove all usages of unwrap() and forbid it's use (if applicable).

*If applicable* because even after the first batch of changes there are over 800(!) usages of unwrap() in the code - for various reasons, and often explicitly allowed. So I think it's probably unrealistic to get rid of all of them, and probably also not necessary.

The strategy:
1. Warn on all usages of `unwrap()`.
2. Remove `unwrap()` module by module.
3. Where `unwrap()` would be theoretically okay use `expect("error msg")`.
4. Leave build tools as they are for now - panics there are annoying but not critical (can happen when e.g. some command line tool is missing).
5. For tests and benchmarks unwrap is totally okay imho (`allow-unwrap-in-tests` was anyway already set in `clippy.toml`)
6. Where errors are returned combine error types and "?-ify" the code, or use some other idiomatic Rust expression.
7. Goal: eventually deny `clippy::unwrap_used` everywhere, unless explicitly allowed.

*Note: as this is my first PR, early feedback is greatly appreciated*🙏
Also - rookie question - what (or where) are the guidelines for the last three items in the checklist? Are they needed for this PR, as this is just a cleanup?

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG

- [PR Build Summary](https://build.rerun.io/pr/6311)
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

File: crates/re_build_info/src/build_info.rs [hunk 1]
```diff
@@ -166,8 +166,8 @@ fn crate_version_from_build_info_string() {
 
     {
         let expected_crate_version = build_info.version;
-        let crate_version = CrateVersion::try_parse_from_build_info_string(build_info_str).unwrap();
+        let crate_version = CrateVersion::try_parse_from_build_info_string(build_info_str);
 
-        assert_eq!(expected_crate_version, crate_version);
+        assert_eq!(Ok(expected_crate_version), crate_version);
```
Comment (Wumpf) [inline crates/re_build_info/src/build_info.rs:171]: nit: isn't this caught by the exception for allowing unwraps in test?

File: crates/re_data_store/benches/gc.rs [hunk 2]
```diff
@@ -156,8 +157,9 @@ where
     for _ in 0..NUM_ROWS_PER_ENTITY_PATH {
         #[allow(clippy::needless_range_loop)] // readability
         for i in 0..NUM_ENTITY_PATHS {
-            let row = rows_per_table[i].next().unwrap();
-            store.insert_row(&row.unwrap()).unwrap();
+            if let Some(Ok(row)) = rows_per_table[i].next() {
+                store.insert_row(&row).ok_or_log_error();
+            }
```
Comment (Wumpf) [inline crates/re_data_store/benches/gc.rs:162]: this file is part of a benchmark suite, so it _should_ count as testing code and allow unwraps 🤔 
This is likely not very important but I'm worried by swallowing errors here when they mean that the benchmark/test broke down and we'd rather have this crash

File: crates/re_types/src/lib.rs [hunk 3]
```diff
@@ -172,6 +172,7 @@
 //!
 
 #![warn(missing_docs)] // Let's keep the this crate well-documented!
+#![deny(clippy::unwrap_used)] // See #3408, remove once we remove all the unwrap's
```
Comment (Wumpf) [inline crates/re_types/src/lib.rs:175]: Why is this needed? In other crates that aren't done yet you correctly opt-out of the warning, but here the warning is opted in to error. Ci won't pass where we got clippy warnings, so this seems redundant in a way

File: crates/re_types_builder/src/codegen/rust/deserializer.rs [hunk 4]
```diff
@@ -654,9 +654,7 @@ fn quote_arrow_field_deserializer(
                                 // .collect::<DeserializationResult<Vec<_>>>()?;
 
                                 // NOTE: Unwrapping cannot fail: the length must be correct.
-                                let arr = array_init::from_iter(data).unwrap();
-
-                                Ok(arr)
+                                array_init::from_iter(data).ok_or(DeserializationError::array_init_underrun(#length))
```
Comment (Wumpf) [inline crates/re_types_builder/src/codegen/rust/deserializer.rs:657]: given that it was documented as such (and still is - comment outdated as it stands ;)), I believe we should keep the unwrap here and emit a localized `#[allow(...)]` with a comment on why.

File: crates/re_types_core/src/result.rs [hunk 5]
```diff
@@ -93,6 +95,40 @@ impl SerializationError {
     }
 }
 
+/// A cloneable wrapper around `arrow2::error::Error`, for easier use.
+///
+/// The motivation behind this type is that we often use code that can return a `arrow2::error::Error`
+/// inside functions that return a `SerializationError`. By wrapping it we can use the ? operator and simplify the code.
+/// Second, normally also `arrow2::error::Error` isn't clonable, but `SerializationError` is.
+#[derive(Clone, Debug)]
+pub struct ArcArrowError(std::sync::Arc<arrow2::error::Error>);
```
Comment (Wumpf) [inline crates/re_types_core/src/result.rs:104]: ohh super nice, makes a lot of the codegen shorter

**Review by Wumpf — CHANGES_REQUESTED** [review]
Wow, thank you so much for taking this on, love it! And even made the codegen shorter <3

> So I think it's probably unrealistic to get rid of all of them, and probably also not necessary.

Yeah I also think that's more realistic than the aspiration on that ticket. However, in the limit we manage to handle it similar to unsafe code: opt-in where absolutely necessary but generally avoid it.
I.e. 100% agree with the strategy you described there.


Apart from the small questions/nits I had I think we should actually get this out of draft and land it almost as is - doing this in smaller steps reduces merge conflicts, makes it easier to review and gives it more churn sooner.

File: crates/re_build_info/src/build_info.rs (hunk 1 above)
Comment (Artxiom) [reply crates/re_build_info/src/build_info.rs:171]: Yes. I just find this nicer/more declarative ;) ...and the log will be more descriptive: instead of panic you will see the actual values.

File: crates/re_data_store/benches/gc.rs (hunk 2 above)
Comment (Artxiom) [reply crates/re_data_store/benches/gc.rs:162]: Makes sense! Sorry, I'm new to the code base so I missed that.

File: crates/re_types/src/lib.rs (hunk 3 above)
Comment (Artxiom) [reply crates/re_types/src/lib.rs:175]: The idea is to mark this crate as "unwrap safe" already. All other (unfinished) crates should warn and the ones where unsafe is safe (😄...tests, benchmarks, builders, etc) should explicitly opt-out and allow unwrap().

**Comment by Artxiom** [comment]
@Wumpf 

Thanks a lot!
> Apart from the small questions/nits I had I think we should actually get this out of draft and land it almost as is - doing this in smaller steps reduces merge conflicts, makes it easier to review and gives it more churn sooner.

Okay, great - I just have some changes from today that I want to commit first (mostly for tests and some low hanging fruits).

And what about the last checkbox - what do I have to do to meet the conditions?

**Comment by Artxiom** [comment]
Just one more thing: as this is work in progress - should we set again globally `unwrap_used` to `allow` before merging? Else everyone will get masses of lint warnings.

File: crates/re_build_info/src/build_info.rs (hunk 1 above)
Comment (Wumpf) [reply crates/re_build_info/src/build_info.rs:171]: makes sense (:

File: crates/re_data_store/benches/gc.rs (hunk 2 above)
Comment (Wumpf) [reply crates/re_data_store/benches/gc.rs]: np!

File: crates/re_query/src/latest_at/results.rs [hunk 6]
```diff
@@ -285,6 +285,5 @@ fn downcast<C: Component>(cached: &(dyn ErasedFlatVecDeque + Send + Sync)) -> cr
     if cached.num_entries() != 1 {
         return Err(anyhow::anyhow!("latest_at deque must be single entry").into());
     }
-    // unwrap checked just above ^^^
-    Ok(cached.iter().next().unwrap())
+    Ok(cached.iter().next().expect("checked just above ^^^"))
```
Comment (Wumpf) [inline crates/re_query/src/latest_at/results.rs:288]: if this would ever trigger then it's pretty hard to read on command line - "what is above" makes sense for the comment but not for the expect message.

```suggestion
    Ok(cached.iter().next().expect("checked existence of cached value already"))
```

File: crates/re_sdk_comms/src/lib.rs [hunk 7]
```diff
@@ -29,7 +29,6 @@ pub fn default_server_addr() -> std::net::SocketAddr {
 }
 
 /// The default amount of time to wait for the TCP connection to resume during a flush
-#[allow(clippy::unnecessary_wraps)]
-pub fn default_flush_timeout() -> Option<std::time::Duration> {
-    Some(std::time::Duration::from_secs(2))
+pub fn default_flush_timeout() -> std::time::Duration {
+    std::time::Duration::from_secs(2)
 }
```
Comment (Wumpf) [inline crates/re_sdk_comms/src/lib.rs:34]: This makes the api actually harder to use and it seems the only unwrap this removes is on a pyo3 macro. That's the wrong tradeoff for me, we shouldn't (break api and) make it harder to use just because of this. Instead let's make a local exception

File: tests/rust/roundtrips/image/src/main.rs [hunk 8]
```diff
@@ -1,5 +1,8 @@
 //! Logs an `Image` archetype for roundtrip checks.
 
+// Allow unwrap() in tests (allow-unwrap-in-tests doesn't apply)
```
Comment (Wumpf) [inline tests/rust/roundtrips/image/src/main.rs:3]: that is again because of the ticket you mentioned on the other tests? Would be best to have both the ticket and the synopsis (allow-unwrap-in-tests doesn't work on integration tests) consistently at all of them

File: crates/re_types/src/lib.rs (hunk 3 above)
Comment (Wumpf) [reply crates/re_types/src/lib.rs:175]: I think there's two issues with this:
* unwrap_used being only a warning is nice because it means that during development I can take shortcuts, but upon PR submission I have to clean this all up (ci won't let anything through with warnings)
* this means we have both opt-out and opt-in to deal with at the same time

File: crates/re_types_core/src/result.rs [hunk 9]
```diff
@@ -171,6 +207,9 @@ pub enum DeserializationError {
         backtrace: _Backtrace,
     },
 
+    #[error("Array is smaller than the expected size of {size}")]
+    ArrayInitUnderrun { size: usize, backtrace: _Backtrace },
```
Comment (Wumpf) [inline crates/re_types_core/src/result.rs:211]: the need for this got removed now again, so this variant and associated `array_init_underrun` utility should go as well

Relatedly, it would still be nice to have those unwraps use a localized opt-out with comment, but we can ofc take that another time.

**Review by Wumpf — CHANGES_REQUESTED** [review]
getting there 🙃

**Comment by Wumpf** [comment]
"opting out for legit reasons" should almost never happen on crate level anyways and if so we can comment on why :)

File: crates/re_sdk_comms/src/lib.rs (hunk 7 above)
Comment (Artxiom) [reply crates/re_sdk_comms/src/lib.rs:34]: Argh...I'm really sorry, didn't consider that it's part of the sdk 😬 just found it very weird and confusing that an `Option` is returned here when it always returns a `Some`.

File: tests/rust/roundtrips/image/src/main.rs (hunk 8 above)
Comment (Artxiom) [reply tests/rust/roundtrips/image/src/main.rs:3]: No, I think this is different - isn't `roundtrip` technically not a test at all but just an app we built to use for testing?

**Comment by Artxiom** [comment]
> "opting out for legit reasons" should almost never happen on crate level anyways and if so we can comment on why :)

There are quite a lot of tests/benches that are technically their own crates that need it. But I documented it anyway wherever I encountered it.

File: crates/re_types_core/src/result.rs (hunk 9 above)
Comment (Artxiom) [reply crates/re_types_core/src/result.rs:211]: I added a localized opt-out, see`deserializer.rs`. The comment is also there but it's inside a `quote!` block and it seems it's stripped during generation.
Any ideas if there is a way to include that comment in the output? ...couldn't find anything in the docs.

File: tests/rust/roundtrips/image/src/main.rs (hunk 8 above)
Comment (Wumpf) [reply tests/rust/roundtrips/image/src/main.rs:3]: ah you're right, I missed that!

File: crates/re_types_core/src/result.rs (hunk 9 above)
Comment (Wumpf) [reply crates/re_types_core/src/result.rs:211]: ah yes that's always a bit annoying: you have to first call `quote_comment` and then insert the result into the actual `quote!`

**Comment by Artxiom** [comment]
> getting there 🙃

Oooookay...hope now it arrived 😄 
Thanks for all the input! I think it's a really good base now to refactor the code step-by-step while new stuff has to be un-unwrap-ered.

File: crates/re_types_builder/build.rs [hunk 10]
```diff
@@ -70,12 +70,14 @@ fn main() {
 
     // NOTE: This requires `flatc` to be in $PATH, but only for contributors, not end users.
     // Even for contributors, `flatc` won't be needed unless they edit some of the .fbs files.
-    let sh = Shell::new().unwrap();
+    let sh = Shell::new().expect("Shell::new() failed");
+    #[allow(clippy::unwrap_used)] // unwrap is okay here
```
Comment (Wumpf) [inline crates/re_types_builder/build.rs:74]: someething went sideways here or is `cmd!` internally doing an unwrap?

**Review by Wumpf — APPROVED** [review]
nice, thanks again!

Still need to get ci green though:
* unwraps where they are no longer allowed: https://github.com/rerun-io/rerun/actions/runs/9080837063/job/24958946682?pr=6311
* `pixi run lint-rerun` is unhappy:
https://github.com/rerun-io/rerun/actions/runs/9080837063/job/24958945687?pr=6311

File: crates/re_types_builder/build.rs (hunk 10 above)
Comment (Artxiom) [reply crates/re_types_builder/build.rs:74]: I have fixed hopefully all the linting errors.
> something went sideways here or is cmd! internally doing an unwrap?

I'm not sure I understand, does it fail somewhere? I haven't seen anything in the logs.

Comment (Artxiom) [reply crates/re_types_builder/build.rs:74]: Btw, locally I get another error when running `cargo test --quiet --all-targets`:
(I added some logs to  `bench_downcast_first` in `rerun/crates/re_data_store/benches/arrow2.rs`):

```
bench_downcast_first: re_arrow2::array::fixed_size_list::FixedSizeListArray for kind: Struct
bench_downcast_first: cell:DataCell { inner: DataCellInner { name: "example.MyPoint", size_bytes: 0, values: StructArray[{x: 0, y: 0}] } }
thread 'main' panicked at crates/re_data_store/benches/arrow2.rs:298:30:
called `Option::unwrap()` on a `None` value
```

I don't know this code well but it seems some dynamic casting goes haywire. 
The culprit seems to be this line:
`ArrayKind::Struct => bench_downcast_first::<FixedSizeListArray>(&mut group, kind)`
shouldn't it be?
`ArrayKind::Struct => bench_downcast_first::<StructArray>(&mut group, kind)`

...because judging from the logs above `generate_cells` generates a `StructArray` for `MyPoint`. 
`impl Loggable for MyPoint`also uses `Struct`/`StructArray` and not `FixedSizeListArray`.

I don't think this is caused by my changes though - and ideas?
