### PR TITLE
Gpu picking for depth clouds

### LINKED ISSUE #1584: Hovering and selection doesn't work for backprojected depth
Backprojected depth images currently don't support hovering or selecting, which makes them difficult to use.

Related:
-  #807

### LINKED ISSUE #1615: GPU picking for hover/select
We currently do picking of primitives on the CPU, which is slow, and doesn't work for the GPU-projected depth maps (and is not implemented for meshes).

The long-term best solution is to do all picking on the GPU.

This issue is done when all 2D and 3D picking is done via the GPU, including meshes and GPU-projected depth map point clouds.

---

The likely approach is to render all primitives to a secondary integer buffer encoding the instance-key. We then read-back a small area under the mouse cursor and to the picking via some smart algorithm that helps the user pick small features.

Naively picking the instance id directly under the cursor will make it difficult to ever select primitives that only cover a pixel or two. To fix this  we can read back 7x7 pixels and pick the id that covered the _fewest_ pixels AND are not on the border (things on the border could be the corner of something big). If all id:s are also on the border, then pick the id that covers the _most_ pixels.

### PR DESCRIPTION
**Pull request by Wumpf**
The last piece that didn't have gpu picking 🎉🎉
Indeed it didn't have picking at all! Making it the first piece to profit more than just on the accuracy & performance side.

This PR also takes the first step towards using instance ids for indexing pixels in accordance with the discussion results documented in #1756 
In fact, the hover effect for all images now uses instance ids to encode the hovered pixel, making the hover handling of depth clouds a very natural extension of the existing feature!

https://user-images.githubusercontent.com/1220815/232068529-d34d4c85-9cb1-4705-b528-352d4c4ae4d5.mov

Small caveat: The depth values we get via the blueprint meter settings are correctly processed in some places and not in others. Decided to leave it be for now as this is something we need to solve with proper blueprint overwrites.

Fixes #1584 and fixes #1615

* #1615
* #1584

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)

### CODE REVIEW

File: crates/re_log_types/src/component_types/instance_key.rs [hunk 1]
```diff
@@ -63,6 +63,16 @@ impl InstanceKey {
     pub fn specific_index(self) -> Option<InstanceKey> {
         self.is_specific().then_some(self)
     }
+
+    /// Creates a new [`InstanceKey`] that identifies a 2d coordinate.
+    pub fn from_2d_image_coordinate(x: u32, y: u32, image_width: u64) -> Self {
```
Comment (emilk) [inline crates/re_log_types/src/component_types/instance_key.rs:68]: you can make it more symmetrical with `to_2d_image_coordinate`:

```suggestion
    pub fn from_2d_image_coordinate([x, y]: [u32; 2], image_width: u64) -> Self {
```

**Review by emilk — APPROVED** [review]
Beautiful! And getting the zoom-in-on-hover too ❤️ 

We should now remove the explicit projection of depth maps in `car` and `nyud` examples imho - rerun does it better in every way!
