### PR TITLE
Workaround for alpha to coverage state leaking on (Web)GL renderer

### LINKED ISSUE #1195: Timeline view intermittently disappears on windows web-view
This happens consistently on all of Edge, Chrome, and Firefox.

The behavior is 100% deterministic as a function of timeline position.

Easy to reproduce with the api demo.

https://user-images.githubusercontent.com/3312232/218241323-5980315b-70d8-4f06-8bfa-768001481eb1.mp4

Different weird artifacts in the colmap demo:

https://user-images.githubusercontent.com/3312232/218241823-071d1345-ca40-41ce-ad2f-b3698c8230ed.mp4

### PR DESCRIPTION
**Pull request by Wumpf**
Plus, use `Web` hardware tier when rendering with GLES.

Fixes #1195

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: crates/re_renderer/src/config.rs [hunk 1]
```diff
@@ -12,15 +12,32 @@ pub enum HardwareTier {
...
-        #[cfg(target_arch = "wasm32")]
-        {
-            Self::Web
-        }
-        #[cfg(not(target_arch = "wasm32"))]
-        {
-            Self::Native
+        // Use "Web" tier for actual web but also if someone forces the GL backend!
+        if supported_backends() == wgpu::Backends::GL {
+            HardwareTier::Web
```
Comment (emilk) [inline crates/re_renderer/src/config.rs:38]: Sounds like we should rename this tier to `GL` or `Basic`

File: crates/re_renderer/src/renderer/outlines.rs [hunk 2]
```diff
@@ -199,11 +199,11 @@ impl OutlineMaskProcessor {
...
     /// Number of MSAA samples used for the outline mask target.
     pub fn mask_sample_count(tier: HardwareTier) -> u32 {
-        match tier {
-            HardwareTier::Web => 1,
+        match tier.support_sampling_msaa_texture() {
+            false => 1,
             // The MSAA shader variant deals with *exactly* 4 samples.
             // See `jumpflooding_step_msaa.wgsl`.
-            HardwareTier::Native => 4,
+            true => 4,
```
Comment (emilk) [inline crates/re_renderer/src/renderer/outlines.rs:206]: match on bool is a bit unusual - `if/else` is the more common idiom

**Review by emilk — APPROVED** [review]

**Comment by emilk** [comment]
I'll fix my own comments
