### PR TITLE
Fix space view cloning to also copy entity properties (visible time range, etc.)

### LINKED ISSUE #4977: Cloning a space view doesn't clone all of its configuration state
- Have e.g. a 3D point cloud view
- Set visible time range to `-inf:+inf`
- Clone the view -> the cloned view is back to default settings (`LatestAt(cur_frame)`)

### PR DESCRIPTION
**Pull request by abey79**
### What

* Part of #4977 

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using newly built examples: [app.rerun.io](https://app.rerun.io/pr/4978/index.html)
  * Using examples from latest `main` build: [app.rerun.io](https://app.rerun.io/pr/4978/index.html?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [app.rerun.io](https://app.rerun.io/pr/4978/index.html?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG

- [PR Build Summary](https://build.rerun.io/pr/4978)
- [Docs preview](https://rerun.io/preview/a5e046a0c391cb0928bc2aff540bebfc93e60ce9/docs) 
- [Examples preview](https://rerun.io/preview/a5e046a0c391cb0928bc2aff540bebfc93e60ce9/examples) 
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

### CODE REVIEW

**Comment by teh-cmc** [comment]
- Related: #4970 

In the future, this is exactly the kind of PR where we would want to add an interactive test to the checklist.

File: crates/re_viewport/src/viewport_blueprint.rs [hunk 1]
```diff
@@ -226,6 +226,30 @@ impl ViewportBlueprint {
...
+    pub fn duplicate_space_view(
+        &self,
+        space_view_id: &SpaceViewId,
+        ctx: &ViewerContext<'_>,
+    ) -> Option<SpaceViewId> {
+        let Some(space_view) = self.space_view(space_view_id) else {
+            return None;
+        };
+
+        let new_space_view = space_view.duplicate();
```
Comment (jleibs) [inline crates/re_viewport/src/viewport_blueprint.rs:239]: This leaves a behavioral difference between using `duplicate_space_view` and `duplicate` 

At a minimum, I think the property-copying logic should be folded into the `duplicate()` method instead, since that is part of the process of duplicating that structure.

However, the convenience of also adding the space view to the viewport blueprint seems nice to have factored out here instead of inlined into the selection panel.

File: crates/re_viewport/src/viewport_blueprint.rs [hunk 2]
```diff
@@ -226,6 +226,30 @@ impl ViewportBlueprint {
...
+        let new_space_view_id = new_space_view.id;
+
+        // copy entity properties from the old space view
+        let data_result = space_view.root_data_result(ctx.store_context, ctx.blueprint_query);
+        let new_data_result =
+            new_space_view.root_data_result(ctx.store_context, ctx.blueprint_query);
+        new_data_result.save_override(data_result.individual_properties().cloned(), ctx);
```
Comment (jleibs) [inline crates/re_viewport/src/viewport_blueprint.rs:246]: This is still only a portion of the data to be duplicated -- I think we also need to walk the entire query override tree and copy all of the data overrides as well.

Assuming you don't want to do that now since this incremental improvement unblocks Clement, feel free to just add a TODO(#4977) and just fully close out the issue (which I updated) to mention the other data.

**Review by jleibs — APPROVED** [review]

File: crates/re_viewport/src/viewport_blueprint.rs (hunk 1 above)
Comment (abey79) [reply crates/re_viewport/src/viewport_blueprint.rs:239]: My suggestion would be to clarify that in docstrings, and make `duplicate()` `pub(crate)` (at most), to mark that as implementation details.

File: crates/re_viewport/src/viewport_blueprint.rs (hunk 2 above)
Comment (abey79) [reply crates/re_viewport/src/viewport_blueprint.rs:246]: I will take the suggested shortcut, thanks :)
