### PR TITLE
Fix indentation of leaf items in hierarchical lists

### LINKED ISSUE #5457: Fix indentation of leaf `ListItem`
Currently, the leaf items are indented as follows (ignore disabled state):

image

It should be this way instead:

image

### PR DESCRIPTION
**Pull request by abey79**
### What

- Fixes #5457 (introduced in #5340)

Also sneaks a minor UI tweak in the plot marker selection list.

Before/after: 

image
image

<br/>
<br/>

cc @martenbjork 

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using newly built examples: [app.rerun.io](https://app.rerun.io/pr/5590/index.html)
  * Using examples from latest `main` build: [app.rerun.io](https://app.rerun.io/pr/5590/index.html?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [app.rerun.io](https://app.rerun.io/pr/5590/index.html?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!

- [PR Build Summary](https://build.rerun.io/pr/5590)
- [Docs preview](https://rerun.io/preview/380d08c73607cca35c2640ca2206e0d7c8676ed3/docs) 
- [Examples preview](https://rerun.io/preview/380d08c73607cca35c2640ca2206e0d7c8676ed3/examples) 
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

### CODE REVIEW

File: crates/re_ui/src/list_item.rs [hunk 1]
```diff
@@ -287,9 +298,20 @@ impl<'a> ListItem<'a> {
     }
 
     /// Draw the item.
-    pub fn show(self, ui: &mut Ui) -> Response {
+    pub fn show(self, ui: &mut Ui, indent_mode: IndentMode) -> Response {
```
Comment (emilk) [inline crates/re_ui/src/list_item.rs:301]: I'm curious - why did you chose to make this an argument to `show` instead of a property of `ListItem`? Is it so we consider it carefully wherever we have a list item?

**Review by emilk — APPROVED** [review]

File: crates/re_ui/src/list_item.rs (hunk 1 above)
Comment (abey79) [reply crates/re_ui/src/list_item.rs:301]: Spot on. It's way too easy to forget about it otherwise. IMHO, the alternative would be to have 3 distinct APIs, eg.:
- `show_hierarchical_with_content()`
- `show_hierarchical()`
- `show_flat()`

Maybe that would actually be better?

Comment (abey79) [reply crates/re_ui/src/list_item.rs:301]: (Also, making it a property would be a little weird with the existing `show_collapsing`, as it would be ignored in that case.)

Comment (emilk) [reply crates/re_ui/src/list_item.rs:301]: `show_hierarchical` etc would certainly be more concise, and could be a nice addition

Comment (abey79) [reply crates/re_ui/src/list_item.rs:301]: Right, I'll make that change. I like it better too.
