### PR TITLE
Use SwiftShader software rasterizer on MacOS CI

### LINKED ISSUE #11359: CI: snapshots test often fail on Mac runners.
We have an intermittent CI failure on our Mac runners, related to our UI snapshot tests. Restarting the whole CI job fixes it, but adding just a retry to the individual step does not (https://github.com/rerun-io/rerun/pull/11171)

### Excerpt

```
  [2025-09-26T14:56:22Z DEBUG re_renderer::device_caps] Found the following adapters:
  [2025-09-26T14:56:22Z DEBUG re_renderer::device_caps] * backend: Metal, device_type: IntegratedGpu, name: "Apple Paravirtual device"
  [2025-09-26T14:56:22Z INFO  re_renderer::device_caps] Picked adapter: AdapterInfo { name: "Apple Paravirtual device", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
  [2025-09-26T14:56:22Z DEBUG re_renderer::context] wgpu adapter backend: Metal, device_type: IntegratedGpu, name: "Apple Paravirtual device"
  
  thread 'test_text_documents' panicked at crates/viewer/re_view_text_document/tests/text_document_test.rs:68:13:
  Error rendering image: "Timeout"

…


  We timed out while waiting on the last successful submission to complete!
```

### Full
<details>
```
          SLOW [> 60.000s] re_view_spatial::video test_video_stream_codec_h265
          SLOW [> 60.000s] re_view_text_document view_class::test_help_view
          SLOW [> 60.000s] re_view_text_document::text_document_test test_text_documents
          SLOW [> 60.000s] re_view_text_log view_class::test_help_view
          SLOW [> 60.000s] re_view_time_series view_class::test_help_view
          FAIL [  60.287s] re_view_text_document::text_document_test test_text_documents
  ──── STDOUT:             re_view_text_document::text_document_test test_text_documents
  
  running 1 test
  test test_text_documents has been running for over 60 seconds
  test test_text_documents ... FAILED
  
  failures:
  
  failures:
      test_text_documents
  
  test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 60.25s
  
  ──── STDERR:             re_view_text_document::text_document_test test_text_documents
  [2025-09-26T14:56:22Z DEBUG re_renderer::device_caps] Found the following adapters:
  [2025-09-26T14:56:22Z DEBUG re_renderer::device_caps] * backend: Metal, device_type: IntegratedGpu, name: "Apple Paravirtual device"
  [2025-09-26T14:56:22Z INFO  re_renderer::device_caps] Picked adapter: AdapterInfo { name: "Apple Paravirtual device", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
  [2025-09-26T14:56:22Z DEBUG re_renderer::context] wgpu adapter backend: Metal, device_type: IntegratedGpu, name: "Apple Paravirtual device"
  
  thread 'test_text_documents' panicked at crates/viewer/re_view_text_document/tests/text_document_test.rs:68:13:
  Error rendering image: "Timeout"
  stack backtrace:
     0:        0x1019d9dec - std::backtrace_rs::backtrace::libunwind::trace::h397b10519d455313
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:117:9
     1:        0x1019d9dec - std::backtrace_rs::backtrace::trace_unsynchronized::h902ac8b376515985
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:14
     2:        0x1019d9dec - std::sys::backtrace::_print_fmt::hd7805902c8299639
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:66:9
     3:        0x1019d9dec - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h2c3f7b4c4ce00f07
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:39:26
     4:        0x1019fb1e0 - core::fmt::rt::Argument::fmt::h1e6a80a47071126e
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/fmt/rt.rs:181:76
     5:        0x1019fb1e0 - core::fmt::write::h1dbafa36e52e01c5
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/fmt/mod.rs:1446:25
     6:        0x1019d62ec - std::io::default_write_fmt::h09a684958e7b6931
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/io/mod.rs:639:11
     7:        0x1019d62ec - std::io::Write::write_fmt::he72d49f3084ee601
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/io/mod.rs:1914:13
     8:        0x1019d9ca0 - std::sys::backtrace::BacktraceLock::print::h1fb87370474572ed
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:42:9
     9:        0x1019db618 - std::panicking::default_hook::{{closure}}::h195a9b2c829547eb
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:300:22
    10:        0x1019db468 - std::panicking::default_hook::h18c3aa3e3a3584d5
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:327:9
    11:        0x1019dc0f8 - std::panicking::rust_panic_with_hook::h02a9fa3cad928562
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:833:13
    12:        0x1019dbd24 - std::panicking::begin_panic_handler::{{closure}}::hd1cc56578f819958
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:706:13
    13:        0x1019da2b0 - std::sys::backtrace::__rust_end_short_backtrace::h52c1e479035e4bc4
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:168:18
    14:        0x1019db9cc - __rustc[4794b31dd7191200]::rust_begin_unwind
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:697:5
    15:        0x101a7d230 - core::panicking::panic_fmt::heec96bfc27e6c546
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:75:14
    16:        0x101a04d5c - core::panicking::panic_display::h7925c192f8163de2
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:269:5
    17:        0x101a04d5c - egui_kittest::snapshot::<impl egui_kittest::Harness<State>>::snapshot::panic_cold_display::h20c8de36e140e952
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panic.rs:100:13
    18:        0x100cc3920 - egui_kittest::snapshot::<impl egui_kittest::Harness<State>>::snapshot::h81ec7e392c6220c9
                                 at /Users/runner/.cargo/git/checkouts/egui-9c90d2f9798966b7/48d903d/crates/egui_kittest/src/snapshot.rs:633:17
    19:        0x100cce014 - text_document_test::run_view_ui_and_save_snapshot::hc2999fb4ed04d26a
                                 at /Users/runner/work/rerun/rerun/crates/viewer/re_view_text_document/tests/text_document_test.rs:68:5
    20:        0x100cce014 - text_document_test::run_test_with_origin::h2b248c5107337343
                                 at /Users/runner/work/rerun/rerun/crates/viewer/re_view_text_document/tests/text_document_test.rs:22:5
    21:        0x100ccba4c - text_document_test::test_text_documents::he2c9f5befdef7d9c
                                 at /Users/runner/work/rerun/rerun/crates/viewer/re_view_text_document/tests/text_document_test.rs:49:5
    22:        0x100ccba4c - text_document_test::test_text_documents::{{closure}}::h2914a36035768e88
                                 at /Users/runner/work/rerun/rerun/crates/viewer/re_view_text_document/tests/text_document_test.rs:31:25
    23:        0x100ccba4c - core::ops::function::FnOnce::call_once::h4e11b360f2f5daf8
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/ops/function.rs:250:5
    24:        0x100d02e74 - core::ops::function::FnOnce::call_once::hbe308cb263cff40a
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/ops/function.rs:250:5
    25:        0x100d02e74 - test::__rust_begin_short_backtrace::hd3e462c585ffb8d9
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/test/src/lib.rs:648:18
    26:        0x100d02134 - test::run_test_in_process::{{closure}}::heb94e6af4d687aa0
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/test/src/lib.rs:671:60
    27:        0x100d02134 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hf651dc40561e436a
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panic/unwind_safe.rs:272:9
    28:        0x100d02134 - std::panicking::try::do_call::h5120c2300d806cdb
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:589:40
    29:        0x100d02134 - std::panicking::try::hdbc3766374024f7b
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:552:19
    30:        0x100d02134 - std::panic::catch_unwind::h9d4f52ca02562861
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panic.rs:359:14
    31:        0x100d02134 - test::run_test_in_process::hdbfe475f5b43a22b
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/test/src/lib.rs:671:27
    32:        0x100d02134 - test::run_test::{{closure}}::hd1745b6ba200dd60
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/test/src/lib.rs:592:43
    33:        0x100cd1a94 - test::run_test::{{closure}}::hc0c184005a9a6474
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/test/src/lib.rs:622:41
    34:        0x100cd1a94 - std::sys::backtrace::__rust_begin_short_backtrace::h2e1964a5193b202b
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:152:18
    35:        0x100cd4b88 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::hd090fb0a60d42c5f
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/thread/mod.rs:559:17
    36:        0x100cd4b88 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hfcb1f9fdbddd952b
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panic/unwind_safe.rs:272:9
    37:        0x100cd4b88 - std::panicking::try::do_call::h6769dcb32032aac3
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:589:40
    38:        0x100cd4b88 - std::panicking::try::h8e8f644fb259552f
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:552:19
    39:        0x100cd4b88 - std::panic::catch_unwind::h752ff5c99d023245
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panic.rs:359:14
    40:        0x100cd4b88 - std::thread::Builder::spawn_unchecked_::{{closure}}::h29a7ec0514cb4d0d
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/thread/mod.rs:557:30
    41:        0x100cd4b88 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h002d2659552a95f4
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/ops/function.rs:250:5
    42:        0x1019dd8e4 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h13a08acfc9b1b97c
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/alloc/src/boxed.rs:1966:9
    43:        0x1019dd8e4 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb76d1f5de7586d62
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/alloc/src/boxed.rs:1966:9
    44:        0x1019dd8e4 - std::sys::pal::unix::thread::Thread::new::thread_start::hf0cf67e969add794
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/pal/unix/thread.rs:97:17
    45:        0x19e78fc0c - __pthread_cond_wait
  
    Cancelling due to test failure: 4 tests still running
          SLOW [>120.000s] re_view_spatial::video test_video_stream_codec_h265
          SLOW [>120.000s] re_view_text_document view_class::test_help_view
          SLOW [>120.000s] re_view_text_log view_class::test_help_view
          SLOW [>120.000s] re_view_time_series view_class::test_help_view
          SLOW [>180.000s] re_view_spatial::video test_video_stream_codec_h265
          SLOW [>180.000s] re_view_text_document view_class::test_help_view
          SLOW [>180.000s] re_view_text_log view_class::test_help_view
          SLOW [>180.000s] re_view_time_series view_class::test_help_view
          SLOW [>240.000s] re_view_spatial::video test_video_stream_codec_h265
          SLOW [>240.000s] re_view_text_document view_class::test_help_view
          SLOW [>240.000s] re_view_text_log view_class::test_help_view
          SLOW [>240.000s] re_view_time_series view_class::test_help_view
          SLOW [>300.000s] re_view_spatial::video test_video_stream_codec_h265
          SLOW [>300.000s] re_view_text_document view_class::test_help_view
          SLOW [>300.000s] re_view_text_log view_class::test_help_view
          SLOW [>300.000s] re_view_time_series view_class::test_help_view
          SLOW [>360.000s] re_view_spatial::video test_video_stream_codec_h265
          SLOW [>360.000s] re_view_text_document view_class::test_help_view
          SLOW [>360.000s] re_view_text_log view_class::test_help_view
          SLOW [>360.000s] re_view_time_series view_class::test_help_view
          SLOW [>420.000s] re_view_spatial::video test_video_stream_codec_h265
          SLOW [>420.000s] re_view_text_document view_class::test_help_view
          SLOW [>420.000s] re_view_text_log view_class::test_help_view
          SLOW [>420.000s] re_view_time_series view_class::test_help_view
          SLOW [>480.000s] re_view_spatial::video test_video_stream_codec_h265
          SLOW [>480.000s] re_view_text_document view_class::test_help_view
          SLOW [>480.000s] re_view_text_log view_class::test_help_view
          SLOW [>480.000s] re_view_time_series view_class::test_help_view
          SLOW [>540.000s] re_view_spatial::video test_video_stream_codec_h265
          SLOW [>540.000s] re_view_text_document view_class::test_help_view
          SLOW [>540.000s] re_view_text_log view_class::test_help_view
          SLOW [>540.000s] re_view_time_series view_class::test_help_view
          SLOW [>600.000s] re_view_spatial::video test_video_stream_codec_h265
          SLOW [>600.000s] re_view_text_document view_class::test_help_view
          SLOW [>600.000s] re_view_text_log view_class::test_help_view
          SLOW [>600.000s] re_view_time_series view_class::test_help_view
          FAIL [ 645.396s] re_view_time_series view_class::test_help_view
  ──── STDOUT:             re_view_time_series view_class::test_help_view
  
  running 1 test
  test view_class::test_help_view has been running for over 60 seconds
  test view_class::test_help_view ... FAILED
  
  failures:
  
  failures:
      view_class::test_help_view
  
  test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 645.24s
  
  ──── STDERR:             re_view_time_series view_class::test_help_view
  
  thread 'view_class::test_help_view' panicked at /Users/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wgpu-core-26.0.1/src/device/queue.rs:206:29:
  We timed out while waiting on the last successful submission to complete!
  stack backtrace:
     0:        0x10484b888 - std::backtrace_rs::backtrace::libunwind::trace::h397b10519d455313
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:117:9
     1:        0x10484b888 - std::backtrace_rs::backtrace::trace_unsynchronized::h902ac8b376515985
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:14
     2:        0x10484b888 - std::sys::backtrace::_print_fmt::hd7805902c8299639
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:66:9
     3:        0x10484b888 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h2c3f7b4c4ce00f07
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:39:26
     4:        0x10486c1a8 - core::fmt::rt::Argument::fmt::h1e6a80a47071126e
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/fmt/rt.rs:181:76
     5:        0x10486c1a8 - core::fmt::write::h1dbafa36e52e01c5
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/fmt/mod.rs:1446:25
     6:        0x104847fdc - std::io::default_write_fmt::h09a684958e7b6931
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/io/mod.rs:639:11
     7:        0x104847fdc - std::io::Write::write_fmt::he72d49f3084ee601
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/io/mod.rs:1914:13
     8:        0x10484b73c - std::sys::backtrace::BacktraceLock::print::h1fb87370474572ed
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:42:9
     9:        0x10484cf9c - std::panicking::default_hook::{{closure}}::h195a9b2c829547eb
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:300:22
    10:        0x10484cdec - std::panicking::default_hook::h18c3aa3e3a3584d5
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:327:9
    11:        0x10484da7c - std::panicking::rust_panic_with_hook::h02a9fa3cad928562
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:833:13
    12:        0x10484d680 - std::panicking::begin_panic_handler::{{closure}}::hd1cc56578f819958
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:699:13
    13:        0x10484bd4c - std::sys::backtrace::__rust_end_short_backtrace::h52c1e479035e4bc4
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:168:18
    14:        0x10484d350 - __rustc[4794b31dd7191200]::rust_begin_unwind
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:697:5
    15:        0x1048c8fd0 - core::panicking::panic_fmt::heec96bfc27e6c546
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:75:14
    16:        0x1042ebe94 - <wgpu_core::device::queue::Queue as core::ops::drop::Drop>::drop::h769b95b086a526e9
    17:        0x1042dfed4 - alloc::sync::Arc<T,A>::drop_slow::h4fc6b3b63d62ef88
    18:        0x10430bd58 - wgpu_core::device::global::<impl wgpu_core::global::Global>::queue_drop::he3115553f45b9b28
    19:        0x1042a0f88 - alloc::sync::Arc<T,A>::drop_slow::hd9cf8aa9b492e3c9
    20:        0x1040b9b50 - core::ptr::drop_in_place<egui_wgpu::RenderState>::h2e1a958caa8b9163
    21:        0x1040bb524 - core::ptr::drop_in_place<alloc::boxed::Box<dyn egui_kittest::renderer::TestRenderer>>::hb581f2e2a1cb34d6
    22:        0x1040bdf24 - <egui_kittest::renderer::LazyRenderer as egui_kittest::renderer::TestRenderer>::render::h21601a8ff929eb25
    23:        0x104094960 - egui_kittest::Harness<State>::render::h51c05d0b8f0a7f65
                                 at /Users/runner/.cargo/git/checkouts/egui-9c90d2f9798966b7/48d903d/crates/egui_kittest/src/lib.rs:605:9
    24:        0x104094960 - egui_kittest::snapshot::<impl egui_kittest::Harness<State>>::try_snapshot::h53309892c5c15f7a
                                 at /Users/runner/.cargo/git/checkouts/egui-9c90d2f9798966b7/48d903d/crates/egui_kittest/src/snapshot.rs:587:14
    25:        0x104094960 - egui_kittest::snapshot::<impl egui_kittest::Harness<State>>::snapshot::hd78ef04745e53145
                                 at /Users/runner/.cargo/git/checkouts/egui-9c90d2f9798966b7/48d903d/crates/egui_kittest/src/snapshot.rs:630:15
    26:        0x10409c07c - re_test_context::TestContext::test_help_view::h9e689b377f78b30a
                                 at /Users/runner/work/rerun/rerun/crates/viewer/re_test_context/src/lib.rs:688:13
    27:        0x10409db10 - re_view_time_series::view_class::test_help_view::h1c4ab59d36685579
                                 at /Users/runner/work/rerun/rerun/crates/viewer/re_view_time_series/src/view_class.rs:964:5
    28:        0x10409db10 - re_view_time_series::view_class::test_help_view::{{closure}}::h64ad41a8810129c6
                                 at /Users/runner/work/rerun/rerun/crates/viewer/re_view_time_series/src/view_class.rs:963:20
    29:        0x10409db10 - core::ops::function::FnOnce::call_once::hb0942cd7542fe374
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/ops/function.rs:250:5
    30:        0x1041245c8 - core::ops::function::FnOnce::call_once::hbe308cb263cff40a
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/ops/function.rs:250:5
    31:        0x1041245c8 - test::__rust_begin_short_backtrace::hd3e462c585ffb8d9
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/test/src/lib.rs:648:18
    32:        0x104123888 - test::run_test_in_process::{{closure}}::heb94e6af4d687aa0
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/test/src/lib.rs:671:60
    33:        0x104123888 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hf651dc40561e436a
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panic/unwind_safe.rs:272:9
    34:        0x104123888 - std::panicking::try::do_call::h5120c2300d806cdb
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:589:40
    35:        0x104123888 - std::panicking::try::hdbc3766374024f7b
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:552:19
    36:        0x104123888 - std::panic::catch_unwind::h9d4f52ca02562861
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panic.rs:359:14
    37:        0x104123888 - test::run_test_in_process::hdbfe475f5b43a22b
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/test/src/lib.rs:671:27
    38:        0x104123888 - test::run_test::{{closure}}::hd1745b6ba200dd60
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/test/src/lib.rs:592:43
    39:        0x1040f31e8 - test::run_test::{{closure}}::hc0c184005a9a6474
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/test/src/lib.rs:622:41
    40:        0x1040f31e8 - std::sys::backtrace::__rust_begin_short_backtrace::h2e1964a5193b202b
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:152:18
    41:        0x1040f62dc - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::hd090fb0a60d42c5f
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/thread/mod.rs:559:17
    42:        0x1040f62dc - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hfcb1f9fdbddd952b
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panic/unwind_safe.rs:272:9
    43:        0x1040f62dc - std::panicking::try::do_call::h6769dcb32032aac3
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:589:40
    44:        0x1040f62dc - std::panicking::try::h8e8f644fb259552f
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:552:19
    45:        0x1040f62dc - std::panic::catch_unwind::h752ff5c99d023245
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panic.rs:359:14
    46:        0x1040f62dc - std::thread::Builder::spawn_unchecked_::{{closure}}::h29a7ec0514cb4d0d
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/thread/mod.rs:557:30
    47:        0x1040f62dc - core::ops::function::FnOnce::call_once{{vtable.shim}}::h002d2659552a95f4
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/ops/function.rs:250:5
    48:        0x10484f268 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h13a08acfc9b1b97c
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/alloc/src/boxed.rs:1966:9
    49:        0x10484f268 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb76d1f5de7586d62
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/alloc/src/boxed.rs:1966:9
    50:        0x10484f268 - std::sys::pal::unix::thread::Thread::new::thread_start::hf0cf67e969add794
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/pal/unix/thread.rs:97:17
    51:        0x19e78fc0c - __pthread_cond_wait
  
          FAIL [ 645.599s] re_view_text_log view_class::test_help_view
  ──── STDOUT:             re_view_text_log view_class::test_help_view
  
  running 1 test
  test view_class::test_help_view has been running for over 60 seconds
  test view_class::test_help_view ... FAILED
  
  failures:
  
  failures:
      view_class::test_help_view
  
  test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 645.44s
  
  ──── STDERR:             re_view_text_log view_class::test_help_view
  
  thread 'view_class::test_help_view' panicked at /Users/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wgpu-core-26.0.1/src/device/queue.rs:206:29:
  We timed out while waiting on the last successful submission to complete!
  stack backtrace:
     0:        0x10502b954 - std::backtrace_rs::backtrace::libunwind::trace::h397b10519d455313
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:117:9
     1:        0x10502b954 - std::backtrace_rs::backtrace::trace_unsynchronized::h902ac8b376515985
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:14
     2:        0x10502b954 - std::sys::backtrace::_print_fmt::hd7805902c8299639
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:66:9
     3:        0x10502b954 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h2c3f7b4c4ce00f07
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:39:26
     4:        0x10504c274 - core::fmt::rt::Argument::fmt::h1e6a80a47071126e
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/fmt/rt.rs:181:76
     5:        0x10504c274 - core::fmt::write::h1dbafa36e52e01c5
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/fmt/mod.rs:1446:25
     6:        0x1050280a8 - std::io::default_write_fmt::h09a684958e7b6931
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/io/mod.rs:639:11
     7:        0x1050280a8 - std::io::Write::write_fmt::he72d49f3084ee601
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/io/mod.rs:1914:13
     8:        0x10502b808 - std::sys::backtrace::BacktraceLock::print::h1fb87370474572ed
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:42:9
     9:        0x10502d068 - std::panicking::default_hook::{{closure}}::h195a9b2c829547eb
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:300:22
    10:        0x10502ceb8 - std::panicking::default_hook::h18c3aa3e3a3584d5
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:327:9
    11:        0x10502db48 - std::panicking::rust_panic_with_hook::h02a9fa3cad928562
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:833:13
    12:        0x10502d74c - std::panicking::begin_panic_handler::{{closure}}::hd1cc56578f819958
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:699:13
    13:        0x10502be18 - std::sys::backtrace::__rust_end_short_backtrace::h52c1e479035e4bc4
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:168:18
    14:        0x10502d41c - __rustc[4794b31dd7191200]::rust_begin_unwind
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:697:5
    15:        0x1050a9000 - core::panicking::panic_fmt::heec96bfc27e6c546
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:75:14
    16:        0x104bc0be8 - <wgpu_core::device::queue::Queue as core::ops::drop::Drop>::drop::h769b95b086a526e9
    17:        0x104bb4c28 - alloc::sync::Arc<T,A>::drop_slow::h4fc6b3b63d62ef88
    18:        0x104be0aac - wgpu_core::device::global::<impl wgpu_core::global::Global>::queue_drop::he3115553f45b9b28
    19:        0x104b75cdc - alloc::sync::Arc<T,A>::drop_slow::hd9cf8aa9b492e3c9
    20:        0x10489c174 - core::ptr::drop_in_place<egui_wgpu::RenderState>::h2e1a958caa8b9163
    21:        0x10489db48 - core::ptr::drop_in_place<alloc::boxed::Box<dyn egui_kittest::renderer::TestRenderer>>::hb581f2e2a1cb34d6
    22:        0x1048a0548 - <egui_kittest::renderer::LazyRenderer as egui_kittest::renderer::TestRenderer>::render::h21601a8ff929eb25
    23:        0x104878960 - egui_kittest::Harness<State>::render::h6d3fc3148c610ace
                                 at /Users/runner/.cargo/git/checkouts/egui-9c90d2f9798966b7/48d903d/crates/egui_kittest/src/lib.rs:605:9
    24:        0x104878960 - egui_kittest::snapshot::<impl egui_kittest::Harness<State>>::try_snapshot::hb01547dec36af45f
                                 at /Users/runner/.cargo/git/checkouts/egui-9c90d2f9798966b7/48d903d/crates/egui_kittest/src/snapshot.rs:587:14
    25:        0x104878960 - egui_kittest::snapshot::<impl egui_kittest::Harness<State>>::snapshot::h0c7992089fe359fd
                                 at /Users/runner/.cargo/git/checkouts/egui-9c90d2f9798966b7/48d903d/crates/egui_kittest/src/snapshot.rs:630:15
    26:        0x10487e04c - re_test_context::TestContext::test_help_view::h328afdd9fd5b49e9
                                 at /Users/runner/work/rerun/rerun/crates/viewer/re_test_context/src/lib.rs:688:13
    27:        0x10487b540 - re_view_text_log::view_class::test_help_view::h8dea7ad04e3a39ae
                                 at /Users/runner/work/rerun/rerun/crates/viewer/re_view_text_log/src/view_class.rs:458:5
    28:        0x10487b540 - re_view_text_log::view_class::test_help_view::{{closure}}::h61c7f979d6627fac
                                 at /Users/runner/work/rerun/rerun/crates/viewer/re_view_text_log/src/view_class.rs:457:20
    29:        0x10487b540 - core::ops::function::FnOnce::call_once::h53bed02a1252120c
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/ops/function.rs:250:5
    30:        0x104906bec - core::ops::function::FnOnce::call_once::hbe308cb263cff40a
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/ops/function.rs:250:5
    31:        0x104906bec - test::__rust_begin_short_backtrace::hd3e462c585ffb8d9
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/test/src/lib.rs:648:18
    32:        0x104905eac - test::run_test_in_process::{{closure}}::heb94e6af4d687aa0
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/test/src/lib.rs:671:60
    33:        0x104905eac - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hf651dc40561e436a
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panic/unwind_safe.rs:272:9
    34:        0x104905eac - std::panicking::try::do_call::h5120c2300d806cdb
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:589:40
    35:        0x104905eac - std::panicking::try::hdbc3766374024f7b
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:552:19
    36:        0x104905eac - std::panic::catch_unwind::h9d4f52ca02562861
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panic.rs:359:14
    37:        0x104905eac - test::run_test_in_process::hdbfe475f5b43a22b
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/test/src/lib.rs:671:27
    38:        0x104905eac - test::run_test::{{closure}}::hd1745b6ba200dd60
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/test/src/lib.rs:592:43
    39:        0x1048d580c - test::run_test::{{closure}}::hc0c184005a9a6474
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/test/src/lib.rs:622:41
    40:        0x1048d580c - std::sys::backtrace::__rust_begin_short_backtrace::h2e1964a5193b202b
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:152:18
    41:        0x1048d8900 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::hd090fb0a60d42c5f
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/thread/mod.rs:559:17
    42:        0x1048d8900 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hfcb1f9fdbddd952b
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panic/unwind_safe.rs:272:9
    43:        0x1048d8900 - std::panicking::try::do_call::h6769dcb32032aac3
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:589:40
    44:        0x1048d8900 - std::panicking::try::h8e8f644fb259552f
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:552:19
    45:        0x1048d8900 - std::panic::catch_unwind::h752ff5c99d023245
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panic.rs:359:14
    46:        0x1048d8900 - std::thread::Builder::spawn_unchecked_::{{closure}}::h29a7ec0514cb4d0d
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/thread/mod.rs:557:30
    47:        0x1048d8900 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h002d2659552a95f4
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/ops/function.rs:250:5
    48:        0x10502f334 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h13a08acfc9b1b97c
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/alloc/src/boxed.rs:1966:9
    49:        0x10502f334 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb76d1f5de7586d62
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/alloc/src/boxed.rs:1966:9
    50:        0x10502f334 - std::sys::pal::unix::thread::Thread::new::thread_start::hf0cf67e969add794
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/pal/unix/thread.rs:97:17
    51:        0x19e78fc0c - __pthread_cond_wait
  
          FAIL [ 645.643s] re_view_text_document view_class::test_help_view
  ──── STDOUT:             re_view_text_document view_class::test_help_view
  
  running 1 test
  test view_class::test_help_view has been running for over 60 seconds
  test view_class::test_help_view ... FAILED
  
  failures:
  
  failures:
      view_class::test_help_view
  
  test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 645.47s
  
  ──── STDERR:             re_view_text_document view_class::test_help_view
  
  thread 'view_class::test_help_view' panicked at /Users/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wgpu-core-26.0.1/src/device/queue.rs:206:29:
  We timed out while waiting on the last successful submission to complete!
  stack backtrace:
     0:        0x1012d7910 - std::backtrace_rs::backtrace::libunwind::trace::h397b10519d455313
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:117:9
     1:        0x1012d7910 - std::backtrace_rs::backtrace::trace_unsynchronized::h902ac8b376515985
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:14
     2:        0x1012d7910 - std::sys::backtrace::_print_fmt::hd7805902c8299639
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:66:9
     3:        0x1012d7910 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h2c3f7b4c4ce00f07
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:39:26
     4:        0x1012f8230 - core::fmt::rt::Argument::fmt::h1e6a80a47071126e
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/fmt/rt.rs:181:76
     5:        0x1012f8230 - core::fmt::write::h1dbafa36e52e01c5
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/fmt/mod.rs:1446:25
     6:        0x1012d4064 - std::io::default_write_fmt::h09a684958e7b6931
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/io/mod.rs:639:11
     7:        0x1012d4064 - std::io::Write::write_fmt::he72d49f3084ee601
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/io/mod.rs:1914:13
     8:        0x1012d77c4 - std::sys::backtrace::BacktraceLock::print::h1fb87370474572ed
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:42:9
     9:        0x1012d9024 - std::panicking::default_hook::{{closure}}::h195a9b2c829547eb
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:300:22
    10:        0x1012d8e74 - std::panicking::default_hook::h18c3aa3e3a3584d5
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:327:9
    11:        0x1012d9b04 - std::panicking::rust_panic_with_hook::h02a9fa3cad928562
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:833:13
    12:        0x1012d9708 - std::panicking::begin_panic_handler::{{closure}}::hd1cc56578f819958
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:699:13
    13:        0x1012d7dd4 - std::sys::backtrace::__rust_end_short_backtrace::h52c1e479035e4bc4
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:168:18
    14:        0x1012d93d8 - __rustc[4794b31dd7191200]::rust_begin_unwind
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:697:5
    15:        0x101354fbc - core::panicking::panic_fmt::heec96bfc27e6c546
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:75:14
    16:        0x100e6cba8 - <wgpu_core::device::queue::Queue as core::ops::drop::Drop>::drop::h769b95b086a526e9
    17:        0x100e60be8 - alloc::sync::Arc<T,A>::drop_slow::h4fc6b3b63d62ef88
    18:        0x100e8ca6c - wgpu_core::device::global::<impl wgpu_core::global::Global>::queue_drop::he3115553f45b9b28
    19:        0x100e21c9c - alloc::sync::Arc<T,A>::drop_slow::hd9cf8aa9b492e3c9
    20:        0x100b48160 - core::ptr::drop_in_place<egui_wgpu::RenderState>::h2e1a958caa8b9163
    21:        0x100b49b34 - core::ptr::drop_in_place<alloc::boxed::Box<dyn egui_kittest::renderer::TestRenderer>>::hb581f2e2a1cb34d6
    22:        0x100b4c534 - <egui_kittest::renderer::LazyRenderer as egui_kittest::renderer::TestRenderer>::render::h21601a8ff929eb25
    23:        0x100b24960 - egui_kittest::Harness<State>::render::hcbfd370f32a7d5e9
                                 at /Users/runner/.cargo/git/checkouts/egui-9c90d2f9798966b7/48d903d/crates/egui_kittest/src/lib.rs:605:9
    24:        0x100b24960 - egui_kittest::snapshot::<impl egui_kittest::Harness<State>>::try_snapshot::hc41d327058b913e2
                                 at /Users/runner/.cargo/git/checkouts/egui-9c90d2f9798966b7/48d903d/crates/egui_kittest/src/snapshot.rs:587:14
    25:        0x100b24960 - egui_kittest::snapshot::<impl egui_kittest::Harness<State>>::snapshot::h228dc39d521cc7f1
                                 at /Users/runner/.cargo/git/checkouts/egui-9c90d2f9798966b7/48d903d/crates/egui_kittest/src/snapshot.rs:630:15
    26:        0x100b2a038 - re_test_context::TestContext::test_help_view::h47892fac4d6cdcd8
                                 at /Users/runner/work/rerun/rerun/crates/viewer/re_test_context/src/lib.rs:688:13
    27:        0x100b27540 - re_view_text_document::view_class::test_help_view::h4f94e394f0afd90d
                                 at /Users/runner/work/rerun/rerun/crates/viewer/re_view_text_document/src/view_class.rs:214:5
    28:        0x100b27540 - re_view_text_document::view_class::test_help_view::{{closure}}::ha03a3e29611a6510
                                 at /Users/runner/work/rerun/rerun/crates/viewer/re_view_text_document/src/view_class.rs:213:20
    29:        0x100b27540 - core::ops::function::FnOnce::call_once::h547848a68cfc1064
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/ops/function.rs:250:5
    30:        0x100bb2bd8 - core::ops::function::FnOnce::call_once::hbe308cb263cff40a
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/ops/function.rs:250:5
    31:        0x100bb2bd8 - test::__rust_begin_short_backtrace::hd3e462c585ffb8d9
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/test/src/lib.rs:648:18
    32:        0x100bb1e98 - test::run_test_in_process::{{closure}}::heb94e6af4d687aa0
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/test/src/lib.rs:671:60
    33:        0x100bb1e98 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hf651dc40561e436a
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panic/unwind_safe.rs:272:9
    34:        0x100bb1e98 - std::panicking::try::do_call::h5120c2300d806cdb
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:589:40
    35:        0x100bb1e98 - std::panicking::try::hdbc3766374024f7b
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:552:19
    36:        0x100bb1e98 - std::panic::catch_unwind::h9d4f52ca02562861
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panic.rs:359:14
    37:        0x100bb1e98 - test::run_test_in_process::hdbfe475f5b43a22b
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/test/src/lib.rs:671:27
    38:        0x100bb1e98 - test::run_test::{{closure}}::hd1745b6ba200dd60
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/test/src/lib.rs:592:43
    39:        0x100b817f8 - test::run_test::{{closure}}::hc0c184005a9a6474
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/test/src/lib.rs:622:41
    40:        0x100b817f8 - std::sys::backtrace::__rust_begin_short_backtrace::h2e1964a5193b202b
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:152:18
    41:        0x100b848ec - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::hd090fb0a60d42c5f
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/thread/mod.rs:559:17
    42:        0x100b848ec - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hfcb1f9fdbddd952b
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panic/unwind_safe.rs:272:9
    43:        0x100b848ec - std::panicking::try::do_call::h6769dcb32032aac3
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:589:40
    44:        0x100b848ec - std::panicking::try::h8e8f644fb259552f
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:552:19
    45:        0x100b848ec - std::panic::catch_unwind::h752ff5c99d023245
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panic.rs:359:14
    46:        0x100b848ec - std::thread::Builder::spawn_unchecked_::{{closure}}::h29a7ec0514cb4d0d
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/thread/mod.rs:557:30
    47:        0x100b848ec - core::ops::function::FnOnce::call_once{{vtable.shim}}::h002d2659552a95f4
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/ops/function.rs:250:5
    48:        0x1012db2f0 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h13a08acfc9b1b97c
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/alloc/src/boxed.rs:1966:9
    49:        0x1012db2f0 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb76d1f5de7586d62
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/alloc/src/boxed.rs:1966:9
    50:        0x1012db2f0 - std::sys::pal::unix::thread::Thread::new::thread_start::hf0cf67e969add794
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/pal/unix/thread.rs:97:17
    51:        0x19e78fc0c - __pthread_cond_wait
  
          FAIL [ 647.604s] re_view_spatial::video test_video_stream_codec_h265
  ──── STDOUT:             re_view_spatial::video test_video_stream_codec_h265
  
  running 1 test
  test test_video_stream_codec_h265 has been running for over 60 seconds
  test test_video_stream_codec_h265 ... FAILED
  
  failures:
  
  failures:
      test_video_stream_codec_h265
  
  test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 5 filtered out; finished in 647.31s
  
  ──── STDERR:             re_view_spatial::video test_video_stream_codec_h265
  [2025-09-26T14:56:20Z INFO  video] Pixi ffmpeg not found at "/Users/runner/work/rerun/rerun/.pixi/envs/default/Library/bin/ffmpeg"
  [2025-09-26T14:56:20Z DEBUG cros_codecs::codec::h265::parser] Parsed SPS(0), resolution: (1920, 1080): NAL size was 43
  [2025-09-26T14:56:20Z DEBUG cros_codecs::codec::h265::parser] Parsed SPS(0), resolution: (1920, 1080): NAL size was 43
  [2025-09-26T14:56:20Z DEBUG cros_codecs::codec::h265::parser] Parsed SPS(0), resolution: (1920, 1080): NAL size was 43
  [2025-09-26T14:56:21Z DEBUG re_renderer::device_caps] Found the following adapters:
  [2025-09-26T14:56:21Z DEBUG re_renderer::device_caps] * backend: Metal, device_type: IntegratedGpu, name: "Apple Paravirtual device"
  [2025-09-26T14:56:21Z INFO  re_renderer::device_caps] Picked adapter: AdapterInfo { name: "Apple Paravirtual device", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
  [2025-09-26T14:56:21Z DEBUG re_renderer::context] wgpu adapter backend: Metal, device_type: IntegratedGpu, name: "Apple Paravirtual device"
  [2025-09-26T14:56:21Z DEBUG cros_codecs::codec::h265::parser] Parsed SPS(0), resolution: (1920, 1080): NAL size was 43
  [2025-09-26T14:56:21Z DEBUG re_video::decode::ffmpeg_cli::ffmpeg] Parsed FFmpeg version: 7.1
  [2025-09-26T14:56:21Z DEBUG re_video::decode::ffmpeg_cli::ffmpeg] FFmpeg configuration: ["--prefix=/Users/runner/work/rerun/rerun/.pixi/envs/default", "--cc=arm64-apple-darwin20.0.0-clang", "--cxx=arm64-apple-darwin20.0.0-clang++", "--nm=arm64-apple-darwin20.0.0-nm", "--ar=arm64-apple-darwin20.0.0-ar", "--disable-doc", "--enable-openssl", "--enable-demuxer=dash", "--enable-hardcoded-tables", "--enable-libfreetype", "--enable-libharfbuzz", "--enable-libfontconfig", "--enable-libopenh264", "--enable-libdav1d", "--enable-cross-compile", "--arch=arm64", "--target-os=darwin", "--cross-prefix=arm64-apple-darwin20.0.0-", "--host-cc=/Users/runner/miniforge3/conda-bld/ffmpeg_1738950713088/_build_env/bin/x86_64-apple-darwin13.4.0-clang", "--enable-neon", "--disable-gnutls", "--enable-libmp3lame", "--enable-libvpx", "--enable-libass", "--enable-pthreads", "--enable-libopenvino", "--enable-gpl", "--enable-libx264", "--enable-libx265", "--enable-libaom", "--enable-libsvtav1", "--enable-libxml2", "--enable-pic", "--enable-shared", "--disable-static", "--enable-version3", "--enable-zlib", "--enable-libopus", "--enable-librsvg", "--enable-ffplay", "--pkg-config=/Users/runner/miniforge3/conda-bld/ffmpeg_1738950713088/_build_env/bin/pkg-config"]
  [2025-09-26T14:56:21Z DEBUG re_renderer::video::player] Signaling end of video
  [2025-09-26T14:56:21Z DEBUG re_video::decode::ffmpeg_cli::ffmpeg] /video, codec: H.265 HEV1 (hvc1.1.6.L120.90)'s ffmpeg is Done
  [2025-09-26T14:56:21Z DEBUG re_renderer::video::player] Dropping VideoPlayer "/video, codec: H.265 HEV1 (hvc1.1.6.L120.90)"
  [2025-09-26T14:56:21Z DEBUG re_renderer::video::player] Signaling end of video
  [2025-09-26T14:56:22Z DEBUG re_video::decode::ffmpeg_cli::ffmpeg] /video, codec: H.265 HEV1 (hvc1.1.6.L120.90)'s ffmpeg is Done
  
  thread 'test_video_stream_codec_h265' panicked at crates/viewer/re_view_spatial/tests/video.rs:303:17:
  Error rendering image: "Timeout"
  stack backtrace:
     0:        0x10157229c - std::backtrace_rs::backtrace::libunwind::trace::h397b10519d455313
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:117:9
     1:        0x10157229c - std::backtrace_rs::backtrace::trace_unsynchronized::h902ac8b376515985
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:14
     2:        0x10157229c - std::sys::backtrace::_print_fmt::hd7805902c8299639
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:66:9
     3:        0x10157229c - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h2c3f7b4c4ce00f07
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:39:26
     4:        0x1015940ac - core::fmt::rt::Argument::fmt::h1e6a80a47071126e
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/fmt/rt.rs:181:76
     5:        0x1015940ac - core::fmt::write::h1dbafa36e52e01c5
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/fmt/mod.rs:1446:25
     6:        0x10156e3cc - std::io::default_write_fmt::h09a684958e7b6931
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/io/mod.rs:639:11
     7:        0x10156e3cc - std::io::Write::write_fmt::he72d49f3084ee601
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/io/mod.rs:1914:13
     8:        0x101572150 - std::sys::backtrace::BacktraceLock::print::h1fb87370474572ed
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:42:9
     9:        0x101573b78 - std::panicking::default_hook::{{closure}}::h195a9b2c829547eb
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:300:22
    10:        0x1015739c8 - std::panicking::default_hook::h18c3aa3e3a3584d5
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:327:9
    11:        0x101574658 - std::panicking::rust_panic_with_hook::h02a9fa3cad928562
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:833:13
    12:        0x101574284 - std::panicking::begin_panic_handler::{{closure}}::hd1cc56578f819958
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:706:13
    13:        0x101572760 - std::sys::backtrace::__rust_end_short_backtrace::h52c1e479035e4bc4
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:168:18
    14:        0x101573f2c - __rustc[4794b31dd7191200]::rust_begin_unwind
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:697:5
    15:        0x101639a2c - core::panicking::panic_fmt::heec96bfc27e6c546
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:75:14
    16:        0x10159e08c - core::panicking::panic_display::h0a05875c28ccc4e6
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:269:5
    17:        0x10159e08c - egui_kittest::snapshot::<impl egui_kittest::Harness<State>>::snapshot_options::panic_cold_display::hb36ccabc1b645302
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panic.rs:100:13
    18:        0x1002602c0 - egui_kittest::snapshot::<impl egui_kittest::Harness<State>>::snapshot_options::h353cacc8c0732840
                                 at /Users/runner/.cargo/git/checkouts/egui-9c90d2f9798966b7/48d903d/crates/egui_kittest/src/snapshot.rs:615:17
    19:        0x100251ffc - video::test_video::h7f2042f891bd2b22
                                 at /Users/runner/work/rerun/rerun/crates/viewer/re_view_spatial/tests/video.rs:303:9
    20:        0x10024d2f0 - video::test_video_stream_codec_h265::he6001137bfff5241
                                 at /Users/runner/work/rerun/rerun/crates/viewer/re_view_spatial/tests/video.rs:340:5
    21:        0x10024d2f0 - video::test_video_stream_codec_h265::{{closure}}::hf5221fc8cb460b9c
                                 at /Users/runner/work/rerun/rerun/crates/viewer/re_view_spatial/tests/video.rs:339:34
    22:        0x10024d2f0 - core::ops::function::FnOnce::call_once::hbb22b27db56cd57d
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/ops/function.rs:250:5
    23:        0x1004680e4 - core::ops::function::FnOnce::call_once::hbe308cb263cff40a
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/ops/function.rs:250:5
    24:        0x1004680e4 - test::__rust_begin_short_backtrace::hd3e462c585ffb8d9
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/test/src/lib.rs:648:18
    25:        0x1004673a4 - test::run_test_in_process::{{closure}}::heb94e6af4d687aa0
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/test/src/lib.rs:671:60
    26:        0x1004673a4 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hf651dc40561e436a
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panic/unwind_safe.rs:272:9
    27:        0x1004673a4 - std::panicking::try::do_call::h5120c2300d806cdb
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:589:40
    28:        0x1004673a4 - std::panicking::try::hdbc3766374024f7b
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:552:19
    29:        0x1004673a4 - std::panic::catch_unwind::h9d4f52ca02562861
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panic.rs:359:14
    30:        0x1004673a4 - test::run_test_in_process::hdbfe475f5b43a22b
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/test/src/lib.rs:671:27
    31:        0x1004673a4 - test::run_test::{{closure}}::hd1745b6ba200dd60
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/test/src/lib.rs:592:43
    32:        0x100436d04 - test::run_test::{{closure}}::hc0c184005a9a6474
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/test/src/lib.rs:622:41
    33:        0x100436d04 - std::sys::backtrace::__rust_begin_short_backtrace::h2e1964a5193b202b
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:152:18
    34:        0x100439df8 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::hd090fb0a60d42c5f
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/thread/mod.rs:559:17
    35:        0x100439df8 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hfcb1f9fdbddd952b
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panic/unwind_safe.rs:272:9
    36:        0x100439df8 - std::panicking::try::do_call::h6769dcb32032aac3
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:589:40
    37:        0x100439df8 - std::panicking::try::h8e8f644fb259552f
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:552:19
    38:        0x100439df8 - std::panic::catch_unwind::h752ff5c99d023245
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panic.rs:359:14
    39:        0x100439df8 - std::thread::Builder::spawn_unchecked_::{{closure}}::h29a7ec0514cb4d0d
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/thread/mod.rs:557:30
    40:        0x100439df8 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h002d2659552a95f4
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/ops/function.rs:250:5
    41:        0x101575e44 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h13a08acfc9b1b97c
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/alloc/src/boxed.rs:1966:9
    42:        0x101575e44 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb76d1f5de7586d62
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/alloc/src/boxed.rs:1966:9
    43:        0x101575e44 - std::sys::pal::unix::thread::Thread::new::thread_start::hf0cf67e969add794
                                 at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/pal/unix/thread.rs:97:17
    44:        0x19e78fc0c - __pthread_cond_wait
  [2025-09-26T14:57:22Z DEBUG re_renderer::video] Dropping Video "/video"
  [2025-09-26T14:57:22Z DEBUG re_renderer::video::player] Dropping VideoPlayer "/video, codec: H.265 HEV1 (hvc1.1.6.L120.90)"
  
  ────────────
       Summary [ 664.922s] 688/717 tests run: 683 passed, 5 failed, 0 skipped
          FAIL [ 647.604s] re_view_spatial::video test_video_stream_codec_h265
          FAIL [ 645.643s] re_view_text_document view_class::test_help_view
          FAIL [  60.287s] re_view_text_document::text_document_test test_text_documents
          FAIL [ 645.599s] re_view_text_log view_class::test_help_view
          FAIL [ 645.396s] re_view_time_series view_class::test_help_view
  warning: 29/717 tests were not run due to test failure (run with --no-fail-fast to run all tests, or run with --max-fail)
  error: test run failed
  
  See the "Upload test results" step for a link to the snapshot test artifact.
  > cargo test --quiet --all-features --doc ❌
  'RUSTFLAGS=" " RUSTDOCFLAGS=" " RERUN_DISABLE_WEB_VIEWER_SERVER="1" TRACY_ENABLED="0" TRACY_NO_INVARIANT_CHECK="1" cargo test --quiet --all-features --doc' failed with exit-code 101. Output:
```
</details>

### PR DESCRIPTION
**Pull request by Wumpf**
### Related

* Fixes #11359 
* Partially #8475
* Depends on https://github.com/rerun-io/rerun/pull/12444
* Depends on https://github.com/rerun-io/rerun/pull/12449

### What

The setup software rasterizer script got extended to have an upload utility and there's now a vulkan upload script as well. Both utils are a bit wordy due to their vibecoded nature, but I found it pretty useful!
At CI runtime we just just grab a prebuilt swiftshader dylib and set up an ICD file that points to it. which is pretty straight forward.

Unfortunately SwiftShader seems to be a little bit buggy when it comes to accuracy of filtering and MSAA. I had to bump treshholds very high and upload larger bgr test images to workaround these problems

### CODE REVIEW

File: crates/viewer/re_ui/src/testing.rs [hunk 1]
```diff
@@ -28,20 +28,44 @@ pub fn new_harness<T>(option: TestOptions, size: impl Into<Vec2>) -> HarnessBuil
     builder
 }
 
-fn default_snapshot_options_for_ui() -> SnapshotOptions {
-    SnapshotOptions::default().failed_pixel_count_threshold(10) // we sometimes have a few wrong pixels in text rendering in egui for unknown reasons
+fn use_lenient_macos_ci_thresholds() -> bool {
+    // TODO(andreas): As of writing SwiftShader gets MSAA wrong and has drastically different texture filtering.
+    // TODO(andreas): A more straight forward check for swiftshader would be better here.
```
[the remark this answers is not in the document]
Comment (Wumpf) [reply crates/viewer/re_ui/src/testing.rs:33]: hey, nothing with with andreas!

File: crates/viewer/re_view_spatial/tests/snapshots/bgr_images_bgr_f16.png
Comment (emilk) [inline crates/viewer/re_view_spatial/tests/snapshots/bgr_images_bgr_f16.png:1]: why the size change?

File: crates/viewer/re_ui/tests/modal_tests.rs [hunk 2]
```diff
@@ -48,19 +48,19 @@ pub fn test_modal_list_item_should_match_snapshot() {
...
 ) {
     let mut modal_handler = ModalHandler::default();
     modal_handler.open();
 
-    let mut harness = egui_kittest::Harness::builder()
-        .with_size(Vec2::new(700.0, 700.0))
-        .build_ui(|ui| {
-            re_ui::apply_style_and_install_loaders(ui.ctx());
+    let mut harness =
+        re_ui::testing::new_harness(re_ui::testing::TestOptions::Gui, Vec2::new(700.0, 700.0))
```
Comment (emilk) [inline crates/viewer/re_ui/tests/modal_tests.rs:57]: Maybe we should just do an egui patch release with https://github.com/emilk/egui/pull/7643 so we can have a single `kittest.toml` in our root folder instead. Ping @lucasmerlin

File: crates/viewer/re_ui/src/testing.rs [hunk 3]
```diff
@@ -28,20 +28,44 @@ pub fn new_harness<T>(option: TestOptions, size: impl Into<Vec2>) -> HarnessBuil
...
+    } else {
+        0.2 / 100.0
+    };
     let max_broken_pixels = (num_total_pixels * broken_pixels_fraction).round() as usize;
 
-    let threshold = 1.5; // Must be pretty high because of 3D grid :/
+    let threshold = if lenient_macos_ci_thresholds {
+        2.5
+    } else {
+        1.5 // Must be pretty high because of 3D grid :/
```
Comment (emilk) [inline crates/viewer/re_ui/src/testing.rs]: Isn't that better with the new grid shader?

File: crates/viewer/re_ui/src/testing.rs [hunk 4]
```diff
@@ -28,20 +28,44 @@ pub fn new_harness<T>(option: TestOptions, size: impl Into<Vec2>) -> HarnessBuil
     builder
 }
 
-fn default_snapshot_options_for_ui() -> SnapshotOptions {
-    SnapshotOptions::default().failed_pixel_count_threshold(10) // we sometimes have a few wrong pixels in text rendering in egui for unknown reasons
+fn use_lenient_macos_ci_thresholds() -> bool {
+    // TODO(andreas): As of writing SwiftShader gets MSAA wrong and has drastically different texture filtering.
+    // TODO(andreas): A more straight forward check for swiftshader would be better here.
+    cfg!(target_os = "macos") && std::env::var("CI").is_ok()
```
Comment (emilk) [inline crates/viewer/re_ui/src/testing.rs:35]: This means we should no longer use the mac CI build as a source for committing snapshot changes, I guess?

File: crates/viewer/re_test_context/src/lib.rs [hunk 5]
```diff
@@ -318,6 +318,12 @@ static SHARED_WGPU_RENDERER_SETUP: std::sync::LazyLock<SharedWgpuResources> =
 fn init_shared_renderer_setup() -> SharedWgpuResources {
     let instance = wgpu::Instance::new(&re_renderer::device_caps::testing_instance_descriptor());
     let adapter = re_renderer::device_caps::select_testing_adapter(&instance);
+
+    assert!(
+        adapter.get_info().device_type == wgpu::DeviceType::Cpu || std::env::var("CI").is_err(),
+        "We require a software renderer for CI tests. GPU based ones have been unreliable in the past."
+    );
```
Comment (emilk) [inline crates/viewer/re_test_context/src/lib.rs]: I have a hard time parsing this logic. We must either use software rendering or not be on CI?

How about

```suggestion
    let is_ci = std::env::var("CI").is_ok();
    if is_ci {
	    assert!(
	        adapter.get_info().device_type == wgpu::DeviceType::Cpu,
	        "We require a software renderer for CI tests. GPU based ones have been unreliable in the past."
	    );
    }
```

File: crates/viewer/re_ui/tests/modal_tests.rs (hunk 2 above)
Comment (emilk) [reply crates/viewer/re_ui/tests/modal_tests.rs:57]: Oh, but we have different thresholds on CI… so maybe not

File: crates/viewer/re_view_spatial/tests/bgr_images.rs [hunk 6]
```diff
@@ -61,7 +61,7 @@ fn run_bgr_test<T: ImageChannelType>(
     snapshot_results.add(test_context.run_view_ui_and_save_snapshot(
         view_id,
         &snapshot_name,
-        egui::vec2(160.0, 120.0),
+        egui::vec2(300.0, 200.0),
```
Comment (emilk) [inline crates/viewer/re_view_spatial/tests/bgr_images.rs:64]: Unintentional?

File: Cargo.toml [hunk 7]
```diff
@@ -430,6 +430,7 @@ wgpu = { version = "27.0.1", default-features = false, features = [
   "vulkan",
   "webgl",
   "webgpu",
+  "vulkan-portability", # Enables use of Vulkan on MacOS. We use this for software rasterizing our CI (there aren't any Metal software rasterizers and we had issues with flaky tests when creating lots of Metal devices in parallel)
```
Comment (emilk) [inline Cargo.toml]: sort

File: scripts/ci/setup_software_rasterizer.py [hunk 8]
```diff
@@ -5,10 +5,18 @@
 See https://github.com/gfx-rs/wgpu/blob/a8a91737b2d2f378976e292074c75817593a0224/.github/workflows/ci.yml#L10
 In fact we're the exact same Mesa builds that wgpu produces,
 see https://github.com/gfx-rs/ci-build
+
+For macOS, we use SwiftShader instead of lavapipe. SwiftShader is Google's software Vulkan implementation
+that provides better compatibility with macOS.
+Using a software rasterizer avoids GPU-related flakiness on CI runners which we hit quite often when
+running many tests in parallel - we got spurious timeouts and failure to find graphics devices,
+the cause of these issues is unknown.
```
Comment (emilk) [inline scripts/ci/setup_software_rasterizer.py]: Link to the issue for posterity!

File: crates/viewer/re_viewer/src/lib.rs [hunk 9]
```diff
@@ -207,13 +210,14 @@ pub(crate) fn wgpu_options(force_wgpu_backend: Option<&str>) -> egui_wgpu::WgpuC
...
-                // TODO(#8475): Install custom native adapter selector with more extensive logging and the ability to pick adapter by name
+                // TODO(#8475): Add the ability to pick adapter by name.
                 // (user may e.g. request "nvidia" or "intel" and it should just work!)
-                // ideally producing structured reasoning of why which one was picked in the process.
-                // This should live in re_renderer::config so that we can reuse it in tests & re_renderer examples.
-                native_adapter_selector: None,
+                // Should ideally produce structured reasoning of why which one was picked in the process.
+                native_adapter_selector: Some(std::sync::Arc::new(move |adapters, surface|
+                    re_renderer::device_caps::select_adapter(adapters, backends, surface)
+                )),
```
Comment (emilk) [inline crates/viewer/re_viewer/src/lib.rs:221]: Does this change how we select the wgpu adaptor, for the real viewer?
Such a significant change should go in its own PR

File: scripts/ci/setup_software_rasterizer.py [hunk 10]
```diff
@@ -185,8 +201,178 @@ def setup_lavapipe_for_windows() -> dict[str, str]:
     return env_vars
 
 
+def extract_swiftshader_from_chrome() -> tuple[Path, str] | None:
+    """
+    Extract SwiftShader binaries from a local (!) Chrome installation.
```
Comment (emilk) [inline scripts/ci/setup_software_rasterizer.py:208]: This all feels pretty brittle. Not just this file, but… well, the whole thing :) 

Is there an easy way to switch back to GPU rendering without reverting this whole PR (if the need arises)?

**Review by emilk — COMMENTED** [review]
Exciting stuff!

I usually pick the Mac output in kitdiff to commit new snapshot images. We should switch that recommendation to… Linux?

File: crates/viewer/re_view_spatial/tests/bgr_images.rs (hunk 6 above)
Comment (Wumpf) [reply crates/viewer/re_view_spatial/tests/bgr_images.rs:64]: intentional, see pr description: this makes the test a bit more robust. before that I needed even higher threshholds

File: crates/viewer/re_ui/src/testing.rs (hunk 3 above)
Comment (Wumpf) [reply crates/viewer/re_ui/src/testing.rs]: I didn't try fuzzing with the threshhold for non "lenient mac" because I didn't want to add even more churn. But the high treshhold for `lenient_macos_ci_thresholds` is unfortunately needed with the new grid

**Comment by Wumpf** [comment]
> I usually pick the Mac output in kitdiff to commit new snapshot images. We should switch that recommendation to… Linux?

yeah, we should recommend Linux for it! I can add that
Also someone on the wgpu call just told me that it _should_ be possible to build mesa+lavapipe for Mac as well and run that. I'll create an issue for that and link it up in the relevant places

File: crates/viewer/re_viewer/src/lib.rs (hunk 9 above)
Comment (Wumpf) [reply crates/viewer/re_viewer/src/lib.rs:221]: I can split it out 👍

File: scripts/ci/setup_software_rasterizer.py (hunk 10 above)
Comment (Wumpf) [reply scripts/ci/setup_software_rasterizer.py:208]: yeah fairly easily, we can just not run  the `setup_software_rasterizer` script on ci and that's it :). The relevant part is that  whether `VK_DRIVER_FILES` env var is set!

note that this method in particular isn't run on ci, that's for local runs to get a new swiftshader build to upload it then

File: crates/viewer/re_view_spatial/tests/snapshots/bgr_images_bgr_f16.png
Comment (Wumpf) [reply crates/viewer/re_view_spatial/tests/snapshots/bgr_images_bgr_f16.png:1]: > I had to bump treshholds very high and upload larger bgr test images to workaround these problems

so to add more detail to that: bigger images have less errors because there's less minification going on, relative number of broken pixels becomes smaller

File: crates/viewer/re_ui/src/testing.rs (hunk 3 above)
Comment (Wumpf) [reply crates/viewer/re_ui/src/testing.rs]: trying lower threshhold on the grid pr right now!

**Comment by Wumpf** [comment]
converted to draft until the prerequisite branches land

File: scripts/ci/setup_software_rasterizer.py (hunk 10 above)
Comment (Wumpf) [reply scripts/ci/setup_software_rasterizer.py:208]: added a note to make the fact that this is part of a "local utility" more clear

File: scripts/ci/setup_software_rasterizer.py [hunk 11]
```diff
@@ -185,8 +203,180 @@ def setup_lavapipe_for_windows() -> dict[str, str]:
...
+
+    except Exception as e:
+        print(f"✗ GCloud download failed: {e}")
+        sys.exit(1)
+
+    # Create ICD JSON file
+    # The ICD file tells the Vulkan loader where to find the driver implementation.
+    icd_json = {
+        "file_format_version": "1.0.0",
+        "ICD": {"library_path": str(swiftshader_lib.resolve()), "api_version": "1.3.0"},
```
[the remark this answers is not in the document]
Comment (Wumpf) [reply scripts/ci/setup_software_rasterizer.py:357]: nah, I think this is fine, vulkan version doesn't change that often

File: crates/viewer/re_ui/src/testing.rs [hunk 12]
```diff
@@ -38,10 +54,19 @@ pub fn default_snapshot_options_for_3d(viewport_size: Vec2) -> SnapshotOptions {
     // How many depend on the size of the image.
     let num_total_pixels = viewport_size.x * viewport_size.y;
 
-    let broken_pixels_fraction = 4e-4; // 0.04% of pixels.
+    let lenient_macos_ci_thresholds = use_lenient_macos_ci_thresholds();
+    let broken_pixels_fraction = if lenient_macos_ci_thresholds {
+        1.0 / 100.0
```
[the remark this answers is not in the document]
Comment (Wumpf) [reply crates/viewer/re_ui/src/testing.rs:59]: has clear enough name

**Review by emilk — APPROVED** [review]
Awesine!
