### PR TITLE
Prevent switches to welcome screen if tables are present

### LINKED ISSUE #9465: Deleting all recordings switches to welcome screen although tables still present
**Describe the bug**
Title.

**To Reproduce**
1. Open recording from welcome screen.
2. Add table entry.
3. Remove above recording
4. Viewer jumps back to the welcome screen

**Additional context**

* Introduced by: #9437

### PR DESCRIPTION
**Pull request by grtlr**
### Related

* Closes #9465

### What

All of this logic is quite brittle, but it should to unblock the `v0.23` release.

### CODE REVIEW

File: crates/viewer/re_viewer_context/src/store_hub.rs [hunk 1]
```diff
@@ -141,6 +141,11 @@ impl StoreHub {
         "Welcome screen".into()
     }
 
+    /// App ID used as a marker to display the welcome screen.
+    pub fn table_app_id() -> ApplicationId {
+        "table".into()
+    }
```
Comment (abey79) [inline crates/viewer/re_viewer_context/src/store_hub.rs:147]: that docstring is probably wrong

**Review by abey79 — APPROVED** [review]
