### PR TITLE
Fix crash for missing class ids causing zero sized texture

### LINKED ISSUE #1946: Crash when trying to create zero sized classid color map texture
Running https://github.com/rerun-io/grounding-sam/commit/e1eb0043ba58866cabf506ba20021bc9d5d2c2ca causes a wgpu error which causes a panic in release mode.
```
2023-04-20T14:22:44Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default

thread 'ThreadId(1)' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension Y is zero

', wgpu-0.15.1/src/backend/direct.rs:3024

   8: core::panicking::panic_fmt
             at core/src/panicking.rs:64:14`
```

Running it in debug isn't a crash but reveals that somewhere we create a zero sized color map:
```
[2023-04-20T15:08:46Z WARN  re_renderer::error_tracker] unknown error cause cause=InvalidDimension(Zero(Y))
[2023-04-20T15:08:46Z ERROR re_renderer::error_tracker] WGPU error tick_nr=85 description=Validation Error

    Caused by:
        In Device::create_texture
          note: label = `class_id_colormap`
        Dimension Y is zero
```

### PR DESCRIPTION
**Pull request by Wumpf**
Two things fixed actually:
* texture manager now checks for zero sized texture, this ripples out in a lot more error handling
* class id texture texture handles not having any classes gracefully

Fixes #1946

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: crates/re_renderer/examples/2d.rs [hunk 1]
```diff
@@ -36,16 +36,19 @@ impl framework::Example for Render2D {
...
+                &mut re_ctx.gpu_resources.textures,
+                &Texture2DCreationDesc {
+                    label: "rerun logo".into(),
+                    data: image_data.into(),
+                    format: wgpu::TextureFormat::Rgba8UnormSrgb,
+                    width: rerun_logo.width(),
+                    height: rerun_logo.height(),
+                },
+            )
+            .expect("Failed to create texture for rerun logo");
```
Comment (emilk) [inline crates/re_renderer/examples/2d.rs:51]: separate note, but I think we should stop using `unwrap` and `expect` in our examples. Using `?` is often more readable anyways

**Comment by Wumpf** [comment]
having some trouble there with the nested error construct turns out. `TextureManager2DError<()>` is not ok since it can't be printed via std::fmt::Display

File: crates/re_renderer/examples/2d.rs (hunk 1 above)
Comment (Wumpf) [reply crates/re_renderer/examples/2d.rs:51]: for the samples we want to crash quickly though I'd reason. We should avoid  `unwrap` but using `expect` can help finding issues quickly. If we propagate errors upwards via `?` you loose context

Comment (Wumpf) [reply crates/re_renderer/examples/2d.rs:51]: in the viewer for sure we should almost always handle errors gracefully ending either in correect workarounds or reports (or both). But to me it feels like this isn't all that applicable for samples

File: crates/re_viewer/src/gpu_bridge/tensor_to_gpu.rs [hunk 2]
```diff
@@ -179,11 +182,13 @@ fn class_id_tensor_to_gpu(
...
             }
-        });
+        })
+        .map_err(|e| anyhow::anyhow!("Failed to create class_id_colormap: {e:?}"))?;
 
     let main_texture_handle = try_get_or_create_texture(render_ctx, hash(tensor.id()), || {
         general_texture_creation_desc_from_tensor(debug_name, tensor)
-    })?;
+    })
+    .map_err(|e| anyhow::anyhow!("Failed to create texture for class id tensor: {e:?}"))?;
```
Comment (emilk) [inline crates/re_viewer/src/gpu_bridge/tensor_to_gpu.rs:191]: again

File: crates/re_viewer/src/gpu_bridge/tensor_to_gpu.rs [hunk 3]
```diff
@@ -212,7 +217,8 @@ fn depth_tensor_to_gpu(
 
     let texture = try_get_or_create_texture(render_ctx, hash(tensor.id()), || {
         general_texture_creation_desc_from_tensor(debug_name, tensor)
-    })?;
+    })
+    .map_err(|e| anyhow::anyhow!("Failed to create depth tensor texture: {e:?}"))?;
```
Comment (emilk) [inline crates/re_viewer/src/gpu_bridge/tensor_to_gpu.rs:221]: again

**Comment by Wumpf** [comment]
I know there is a lint for that is working & failing. But need to figure out how to deal with `()` there because that is not Display'able

File: crates/re_renderer/examples/2d.rs (hunk 1 above)
Comment (emilk) [reply crates/re_renderer/examples/2d.rs:51]: `.context("Failed to create texture for rerun logo")?` isn't that much longer than `.expect("Failed to create texture for rerun logo")`

I'm not suggesting we use `thiserror`, just that we try to make our example code nice, readable, and idiomatic for our users

**Comment by emilk** [comment]
`Impl Display for TextureManager2DError<()>` ?

File: crates/re_renderer/examples/2d.rs (hunk 1 above)
Comment (Wumpf) [reply crates/re_renderer/examples/2d.rs:51]: that implies forwarding anyhow errors. But for the sample code how is this much different than using expect?

Comment (Wumpf) [reply crates/re_renderer/examples/2d.rs:51]: Hmm am I doing something wrong or is it not possible to use `.context` on a thiserror result? I mean that then means a lot of map_err again just like in this PR

**Comment by Wumpf** [comment]
That would imply a public `Never` enum/struct in this case though as some of the methods return `TextureManager2DError<()>`. Doesn't seem great.

Tbh didn't think of your crossed out solution, too tired, I think I better call it a day...

**Comment by emilk** [comment]
Go home, and I'll take a stab at it

File: crates/re_renderer/examples/2d.rs (hunk 1 above)
Comment (emilk) [reply crates/re_renderer/examples/2d.rs:51]: you are doing something wrong :)

https://docs.rs/anyhow/latest/anyhow/trait.Context.html

anyways - we'll not be doing it in this PR

Comment (Wumpf) [reply crates/re_renderer/examples/2d.rs:51]: ah. ofc. same problem again. It requires `Display` of the error, that's why it didn't work here. Hnghn.

File: crates/re_viewer/src/gpu_bridge/tensor_to_gpu.rs [hunk 4]
```diff
@@ -94,7 +94,8 @@ fn color_tensor_to_gpu(
             width,
             height,
         })
-    })?;
+    })
+    .map_err(|err| anyhow::anyhow!("Failed to create texture for color tensor: {err}"))?;
```
Comment (emilk) [inline crates/re_viewer/src/gpu_bridge/tensor_to_gpu.rs:98]: this could be using `.context()` instead

Comment (emilk) [reply crates/re_viewer/src/gpu_bridge/tensor_to_gpu.rs:98]: same elsewhere

**Review by emilk — APPROVED** [review]

File: crates/re_renderer/Cargo.toml [hunk 5]
```diff
@@ -55,6 +55,7 @@ glam = { workspace = true, features = ["bytemuck"] }
 half = { workspace = true, features = ["bytemuck"] }
 itertools = { workspace = true }
 macaw.workspace = true
+never = '0.1'
```
Comment (Wumpf) [inline crates/re_renderer/Cargo.toml:58]: ohhhh

File: crates/re_renderer/src/resource_managers/texture_manager.rs [hunk 6]
```diff
@@ -96,12 +96,29 @@ impl<'a> Texture2DCreationDesc<'a> {
 }
 
 #[derive(thiserror::Error, Debug)]
-pub enum TextureManager2DError<DataCreationError> {
+pub enum TextureCreationError {
```
Comment (Wumpf) [inline crates/re_renderer/src/resource_managers/texture_manager.rs:99]: good idea to split it out. we should consider moving this down to the texture pool later :)

**Review by Wumpf — COMMENTED** [review]
thanks for looking after it! I'll go after the `context` calls instead of `map_error` before merging

File: crates/re_renderer/src/resource_managers/texture_manager.rs [hunk 7]
```diff
@@ -95,6 +95,32 @@ impl<'a> Texture2DCreationDesc<'a> {
...
+
+#[derive(thiserror::Error, Debug)]
+pub enum TextureManager2DError<DataCreationError> {
+    /// Something went wrong when creating the GPU texture.
+    #[error(transparent)]
+    TextureCreation(TextureCreationError),
+
+    /// Something went wrong in a user-callback.
+    #[error(transparent)]
+    DataCreation(#[from] DataCreationError),
```
Comment (emilk) [inline crates/re_renderer/src/resource_managers/texture_manager.rs:112]: after writing this I realized this would probably lead to less code, and less complications:

```suggestion
    #[error(transparent)]
    TextureCreation(#[from] TextureCreationError),

    /// Something went wrong in a user-callback.
    #[error(transparent)]
    DataCreation(DataCreationError),
```
