### PR TITLE
Fix too many points crash

### LINKED ISSUE #1779: crash in `CpuWriteGpuReadBuffer::push`
On v0.4.0 we see analytics crashes on:
```
re_renderer/src/allocator/cpu_write_gpu_read_belt.rs:80
```

Crashing code:
```rust
    pub fn push(&mut self, element: T) {
        self.as_slice()[..std::mem::size_of::<T>()].copy_from_slice(bytemuck::bytes_of(&element));
        self.unwritten_element_range.start += 1;
    }
```

Callstack:
```
  14: re_renderer::point_cloud_builder::PointCloudBatchBuilder<PerPointUserData>::extend_defaults
  15: re_viewer::ui::view_spatial::scene::scene_part::points3d::Points3DPart::process_entity_view
  16: <re_viewer::ui::view_spatial::scene::scene_part::points3d::Points3DPart as re_viewer::ui::view_spatial::scene::scene_part::ScenePart>::load
  17: re_viewer::ui::space_view::SpaceView::scene_ui
  18: <re_viewer::ui::viewport::TabViewer as egui_dock::TabViewer>::ui
  19: egui::containers::frame::Frame::show_dyn
  20: core::ops::function::FnOnce::call_once{{vtable.shim}}
  21: egui::ui::Ui::scope_dyn
  22: egui_dock::DockArea<Tab>::show_inside
  23: core::ops::function::FnOnce::call_once{{vtable.shim}}
  24: egui::ui::Ui::scope_dyn
  25: re_viewer::ui::viewport::Viewport::viewport_ui
  26: core::ops::function::FnOnce::call_once{{vtable.shim}}
  27: egui::containers::frame::Frame::show_dyn
  28: egui::containers::panel::CentralPanel::show_inside_dyn
  29: core::ops::function::FnOnce::call_once{{vtable.shim}}
  30: core::ops::function::FnOnce::call_once{{vtable.shim}}
  31: egui::containers::frame::Frame::show_dyn
  32: egui::containers::panel::CentralPanel::show_inside_dyn
  33: re_viewer::app::AppState::show
  34: core::ops::function::FnOnce::call_once{{vtable.shim}}
  35: core::ops::function::FnOnce::call_once{{vtable.shim}}
  36: egui::containers::frame::Frame::show_dyn
  37: egui::containers::panel::CentralPanel::show_inside_dyn
  38: egui::containers::panel::CentralPanel::show_dyn
  39: <re_viewer::app::App as eframe::epi::App>::update
  40: egui::context::Context::run
  41: eframe::native::epi_integration::EpiIntegration::update
  42: <eframe::native::run::wgpu_integration::WgpuWinitApp as eframe::native::run::WinitApp>::paint
  43: eframe::native::run::run_and_return::{{closure}}
  44: winit::platform_impl::platform::x11::EventLoop<T>::run_return::single_iteration
  45: winit::platform_impl::platform::x11::EventLoop<T>::run_return
  46: eframe::native::run::run_and_return
  47: std::thread::local::LocalKey<T>::with
  48: eframe::native::run::wgpu_integration::run_wgpu
  49: eframe::run_native
```

### PR DESCRIPTION
**Pull request by Wumpf**
Simplified the point cloud builder further in the process - we almost always have all the fields ready so we can remove a lot of complexity the "nicer"/fine-grained interface brings with it.

Note that the second commit here (which removes chaining the iterators with fallback values) got frame time for max-points in nyud down to about 131ms from 145ms before that commit (in release).

Edit: Tried on main with a quick & dirty fix, gives me for the same scenario about 143ms. Meaning this PR is perf win :)

Fix #1779

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by teh-cmc** [comment]
```cargo r --example depth_cloud
    Finished dev [optimized + debuginfo] target(s) in 0.18s
     Running `target/debug/examples/depth_cloud`

thread 'main' panicked at 'attempt to subtract with overflow', /home/cmc/dev/rerun-io/rerun/crates/re_renderer/src/point_cloud_builder.rs:220:75
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:111:5
   3: draw_backprojected_point_cloud<re_renderer::renderer::lines::LineDrawData, re_renderer::renderer::rectangles::RectangleDrawData>
   4: draw
             at ./crates/re_renderer/examples/depth_cloud.rs:345:13
   5: {closure#0}<depth_cloud::RenderDepthClouds>
             at ./crates/re_renderer/examples/framework.rs:262:40
   6: sticky_exit_callback<(), depth_cloud::framework::{impl#1}::run::{closure_env#0}<depth_cloud::RenderDepthClouds>>
   7: run_return<(), depth_cloud::framework::{impl#1}::run::{closure_env#0}<depth_cloud::RenderDepthClouds>>
             at /home/cmc/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.28.1/src/platform_impl/linux/wayland/event_loop/mod.rs:548:21
   8: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run
             at /home/cmc/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.28.1/src/platform_impl/linux/wayland/event_loop/mod.rs:222:25
   9: winit::platform_impl::platform::EventLoop<T>::run
             at /home/cmc/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.28.1/src/platform_impl/linux/mod.rs:792:56
  10: winit::event_loop::EventLoop<T>::run
             at /home/cmc/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.28.1/src/event_loop.rs:305:9
  11: depth_cloud::framework::Application<E>::run
             at ./crates/re_renderer/examples/framework.rs:189:9
  12: {async_fn#0}<depth_cloud::RenderDepthClouds>
             at ./crates/re_renderer/examples/framework.rs:363:5
  13: block_on<depth_cloud::framework::run::{async_fn_env#0}<depth_cloud::RenderDepthClouds>>
             at /home/cmc/.cargo/registry/src/github.com-1ecc6299db9ec823/pollster-0.3.0/src/lib.rs:128:15
  14: start<depth_cloud::RenderDepthClouds>
             at ./crates/re_renderer/examples/framework.rs:383:9
  15: call_once<fn(), ()>
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

File: crates/re_renderer/src/point_cloud_builder.rs [hunk 1]
```diff
@@ -141,92 +140,110 @@ impl<'a> PointCloudBatchBuilder<'a> {
...
-                .last_mut()
-                .unwrap()
-                .additional_outline_mask_ids_vertex_ranges,
-            start_vertex_index: old_size as _,
+                .picking_instance_ids_buffer
+                .extend(picking_instance_ids.take(num_points));
+            // Fill up with defaults. Doing this in a separate step is faster than chaining the iterator.
+            self.0.picking_instance_ids_buffer.extend(
+                std::iter::repeat(PickingLayerInstanceId::default()).take(num_written - num_points),
+            );
```
Comment (teh-cmc) [inline crates/re_renderer/src/point_cloud_builder.rs:221]: I don't see how these unchecked subtractions could be safe, surely `num_written` can be smaller than `num_points` in many cases?

**Review by teh-cmc — CHANGES_REQUESTED** [review]

**Comment by Wumpf** [comment]
only tested in the viewer in the end and didn't notice that the default adding there was broken (the viewer doesn't seem to make use of this ever)

**Review by teh-cmc — APPROVED** [review]
