### PR TITLE
Fix for single channel textures displayed only in the red channel

### LINKED ISSUE #4878: Single channel textures in .obj and .glb / .gltf files not working as expected
**Describe the bug**
When opening [these meshes](https://github.com/rerun-io/rerun/files/14002908/meshes.zip), the obj file has no texture and the glb / gltf files either show up red or give an error. In Open3D all meshes show up red. So maybe something with the meshes is off? 
However, they work fine in f3d / Blender / MeshLab (all meshes were exported from a DAE / COLLADA file via Blender; there were similar issues when using trimesh to do the conversion; source mesh is also included in the zip):

| Format | Rerun | O3D | MeshLab | f3d | Blender |
| --- | ---   | --- | --- | --- | --- |
| [obj with mtl and png texture](https://docs.blender.org/manual/en/2.80/addons/io_scene_obj.html#wavefront-obj) | white w/o texture | red | works | works | works |
|  [glb](https://docs.blender.org/manual/en/2.80/addons/io_scene_gltf2.html#gltf-binary-glb) | red | red |  no support | works | works | works |
| [gltf + bin + texture](https://docs.blender.org/manual/en/2.80/addons/io_scene_gltf2.html#gltf-separate-gltf-bin-textures) | error | red | no support | works | works |
| [gltf embedded](https://docs.blender.org/manual/en/2.80/addons/io_scene_gltf2.html#gltf-embedded-gltf) | red | red | no support | works | works |

The error for gltf + bin + texture is
```
Failed to load mesh "/\\//home/leo/rerun_material/meshes/gltf\\+bin\\+textures/mesh.gltf": external reference in slice only import
```

**To Reproduce**
Drag & drop the attached files into the Rerun Viewer.

**Expected behavior**
Ideally, show the textured mesh in all cases. If there's an issue with the mesh leading to missing texture and red material (?) it would be nice to get some information about the problem.

**Screenshots**
No texture (obj in Rerun)
image

Red (glb in Rerun)
image

"Correct" (obj in MeshLab)
image

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Rerun version**
> rerun_py 0.12.1 [rustc 1.74.0 (79e9716c9 2023-11-13), LLVM 17.0.4] x86_64-unknown-linux-gnu release-0.12.1 bef0d78, built 2024-01-17T16:50:34Z

### LINKED ISSUE #10766: GLTF with greyscale JPG texture renders only in the red channel
**Describe the bug**
GLB 3D models generated with JPEG (not JPEG2000) texture images with a greyscale color profile are rendered as if the texture is only applied to the red channel with the green and blue channels empty. The same models render correctly in other online GLTF viewers such as  https://gltf.report/ and https://gltf-viewer.donmccurdy.com/.

**To Reproduce**
1. Create a greyscale image with a greyscale color profile (e.g. `Working Grey - Dot Grain 20%` in Photoshop) and save as `JPEG` (not JP2/JPF/JPEG2000).
2. Apply texture to default cube in Blender
3. Export as GLB with material embedded
4. Load in rerun viewer via `rr.log("world/asset", rr.Asset3D(path=path_to_test_cube))`

**Expected behavior**
This should render a cube with a greyscale image as its texture, not a cube with only the red channel textured and the green and blue channels set to black.

**Screenshots**
Properly rendered greyscale texture:
Image

Rerun only renders texture in red channel:
Image

If we change `AlbedoFactor` on our object to exclude red light, we can see that rerun sees the Green and Blue channels of the image as just flat black:
Image

**Backtrace**

**Desktop (please complete the following information):**
 - OS: macOS Sequoia 15.5

**Rerun version**

`rerun-cli 0.23.4 (default map_view nasm native_viewer release web_viewer) [rustc 1.84.0 (9fc6b4312 2025-01-07), LLVM 19.1.5] x86_64-apple-darwin release-0.23.4 b411df2, built 2025-06-26T13:24:15Z
Video features: av1 default ffmpeg nasm serde`

**Additional context**

Note that rerun renders greyscale textures fine if it's saved as JPEG2000. It also works if you just save the JPG with an sRGB profile (though this wastes space).

### PR DESCRIPTION
**Pull request by IsseW**
### Related
* Closes #4878
* Closes #10766

### What

Implements @emilk's suggestion https://github.com/rerun-io/rerun/issues/10766#issuecomment-3241289535, switch if we interpret the texture as grayscale or rgb depending on input from `MaterialUniformBuffer`.

Also adds an image comparison test with a quad textured with a single channel texture.

--- 

manual checks added via @Wumpf review. See review comments
* [x] 8bit single channel images and displaying them in a 2d view
* [x] 8bit segmentation images - I don't think this goes through this path, but I'm mildly nervous about our lack of testcoverage there
    * [x] with annotation context setting classids to change colors
    * [x] without annotation context... tbh I don't recall how this behaves in the first place
* [x] check if depth images can ever get in here, but I think they can't since they're never 8bit (would be kinda weird)
* [x] works on WebGL
* [x] works on WebGPU

### CODE REVIEW

File: crates/viewer/re_viewer_context/src/gpu_bridge/image_to_gpu.rs [hunk 1]
```diff
@@ -319,6 +319,10 @@ pub fn texture_creation_desc_from_color_image<'a>(
         let datatype = image.format.datatype();
 
         match (color_model, datatype) {
+            (ColorModel::L, ChannelDatatype::U8) => (
+                cast_slice_to_cow(&image.buffer),
+                SourceImageDataFormat::WgpuCompatible(TextureFormat::R8Unorm),
```
Comment (IsseW) [inline crates/viewer/re_viewer_context/src/gpu_bridge/image_to_gpu.rs:324]: Without this change this was being sent to the shader as a `R8Uint` which caused a wgpu validation error

Comment (Wumpf) [reply crates/viewer/re_viewer_context/src/gpu_bridge/image_to_gpu.rs:324]: ah nice, I thiiiink this is the right place & right fix given how fallbacks work. But since lack some test coverage in this area I'd like you to have a look what happens before after for a few different scenarios - I've put those as checkboxes in the ci description so they get picked up by "checkbox ci"

There should be respective snippets for all of those - should hopefully be just a matter of running existing rust/python snippets and maybe adjusting a thing. Reach out if this ends up being substantial work, thx!

File: crates/store/re_types/src/components/image_format_ext.rs [hunk 2]
```diff
@@ -14,6 +14,13 @@ impl ImageFormat {
         datatypes::ImageFormat::segmentation([width, height], datatype).into()
     }
 
+    /// Create a new grayscale image format with 8 bit for the single channel with the given
+    /// resolution.
+    #[inline]
+    pub fn l8([width, height]: [u32; 2]) -> Self {
```
Comment (Wumpf) [inline crates/store/re_types/src/components/image_format_ext.rs:20]: neat utility :)

File: crates/viewer/re_view_spatial/tests/mesh.rs [hunk 3]
```diff
@@ -0,0 +1,58 @@
+use re_log_types::TimePoint;
+use re_test_context::{TestContext, external::egui_kittest::SnapshotOptions};
+use re_test_viewport::TestContextExt as _;
+use re_types::{RowId, archetypes::Mesh3D};
+use re_viewer_context::{RecommendedView, ViewClass as _};
+use re_viewport_blueprint::ViewBlueprint;
+
+#[test]
+pub fn test_single_channel_mesh() {
```
Comment (Wumpf) [inline crates/viewer/re_view_spatial/tests/mesh.rs:9]: love how this turned out!

File: crates/viewer/re_view_spatial/tests/mesh.rs [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+    });
+
+    let size = egui::vec2(300.0, 300.0);
+
+    let mut harness = test_context
+        .setup_kittest_for_rendering()
+        .with_size(size)
+        .build_ui(|ui| test_context.run_with_single_view(ui, view_id));
+
+    let broken_pixels_fraction = 0.0045;
```
Comment (Wumpf) [inline crates/viewer/re_view_spatial/tests/mesh.rs]: c&p from another test or is this empircal result from running ci?
we shouldn't use this whenever possible, there's already some default threshholding going on which tries to be edge sensitive, so chances we could run this without extra threshhold

(naturally the higher the threshhold the less often we catch buts, the lower it is the more flakiness we risk)

File: crates/viewer/re_renderer/src/mesh.rs [hunk 5]
```diff
@@ -218,12 +218,35 @@ pub struct GpuMaterial {
...
+
     /// Keep in sync with [`MaterialUniformBuffer`] in `instanced_mesh.wgsl`
     #[repr(C)]
     #[derive(Clone, Copy, bytemuck::Pod, bytemuck::Zeroable)]
     pub struct MaterialUniformBuffer {
-        pub albedo_factor: wgpu_buffer_types::Vec4,
-        pub end_padding: [wgpu_buffer_types::PaddingRow; 16 - 1],
+        albedo_factor: wgpu_buffer_types::Vec4,
+        texture_format: u32,
+        row_padding: [f32; 4 - 1],
```
Comment (Wumpf) [inline crates/viewer/re_renderer/src/mesh.rs]:
```suggestion
        texture_format: wgpu_buffer_types::U32RowPadded,
```

**Review by Wumpf — CHANGES_REQUESTED** [review]
looking great overall!

But I'm a lil bit paranoid about the check in `image_to_gpu` and webgl/webgpu surprises, see comments.

I trust you confirmed things working with the assets supplied by the issue authors? :)
The older one had a broken loading issue, we may want to create a follow-up ticket (haven't checked on the details just now myself, maybe I'm wrong)

**Comment by IsseW** [comment]
> I trust you confirmed things working with the assets supplied by the issue authors? :)

Yep! Some of the models from #4878 and a model from the discord thread linked in #10766.

> The older one had a broken loading issue, we may want to create a follow-up ticket

Will look into this

File: crates/viewer/re_view_spatial/tests/mesh.rs (hunk 4 above)
Comment (IsseW) [reply crates/viewer/re_view_spatial/tests/mesh.rs]: Ah I saw it on some of the different tests in spatial so assumed it was somewhat standard to have there. Though, turning it off I do see some errors in the test: https://github.com/rerun-io/rerun/actions/runs/17441789015/job/49526341139?pr=11101#step:7:700

So error rate ~0.0003 if I understand the message correctly

Comment (Wumpf) [reply crates/viewer/re_view_spatial/tests/mesh.rs]: those error rates are super mysterious unfortunately. I haven't really gotten my head around yet what they actually mean >.<
it's not a mean-squared-error as most image comparisons would do, instead it's using https://crates.io/crates/dify to mark pixel as either "success" or "broken". The main threshhold controls the "brokenness" (???) per pixel in dify and then we added "completely broken pixels" on top because ofc some pixels are just completely off.
Dify seems to do a great job being tolerant on edges which I like, but otherwise the controls are unfortunately super intransparent right now :/

**Comment by IsseW** [comment]
> without annotation context... tbh I don't recall how this behaves in the first place

seems to automatically assign colors to the different indices then.

**Comment by IsseW** [comment]
>  check if depth images can ever get in here, but I think they can't since they're never 8bit (would be kinda weird)

They can't, and segmentation images don't either, they have their own `image_to_gpu` functions

```rust
/// `colormap` is currently only used for depth images.
pub fn image_to_gpu(
    render_ctx: &RenderContext,
    debug_name: &str,
    image: &ImageInfo,
    image_stats: &ImageStats,
    annotations: &Annotations,
    colormap: Option<&ColormapWithRange>,
) -> anyhow::Result<ColormappedTexture> {
    re_tracing::profile_function!();

    let texture_key = generate_texture_key(image);

    match image.kind {
        ImageKind::Color => {
            color_image_to_gpu(render_ctx, debug_name, texture_key, image, image_stats)
        }
        ImageKind::Depth => depth_image_to_gpu(
            render_ctx,
            debug_name,
            texture_key,
            image,
            image_stats,
            colormap,
        ),
        ImageKind::Segmentation => segmentation_image_to_gpu(
            render_ctx,
            debug_name,
            texture_key,
            image,
            image_stats,
            annotations,
        ),
    }
}
```

**Review by Wumpf — APPROVED** [review]
