### PR TITLE
Fix heuristic object properties being broken in some cases / fix DepthMeter being ignored sometimes

### LINKED ISSUE #4644: DepthImage backprojection doesn't set up correctly if the same entity is used for camera and image
Possibly the same sort of thing as #3296, but I can reproduce this on the latest code b4768f30b481a29b17dfbded685531bdd98f1286 .

**Describe the bug**
If a `DepthImage` and `Pinhole` are logged to the same entity, the backprojection will fail to render because the meter value is 0. Yet, it works fine if the value is manually changed.

**To Reproduce**
1. Modify `code-examples/depth_image_3d.rs` so that both `log()` operations use the same entity path.
2. `cargo run --bin rerun`
3. `cargo run --bin depth_image_3d`
4. Observe that no backprojected depth appears.
5. Select the 3D view of the entity and observe that "Backproject meter" is equal to 0.

**Expected behavior**
The logged meter value should be respected.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.2.1 (23C71)

**Rerun version**
rerun-cli 0.12.0-alpha.3 [rustc 1.74.0 (79e9716c9 2023-11-13), LLVM 17.0.4] x86_64-apple-darwin

Also reproduces with released rerun 0.11

### PR DESCRIPTION
**Pull request by Wumpf**
### What

* Fixes #4644 

The way we updated properties for auto-property values made it pretty much random (not literally, but feels as-if) when and when not we'd see updated `EditableAutoValue::Auto` values!

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using newly built examples: [app.rerun.io](https://app.rerun.io/pr/4679/index.html)
  * Using examples from latest `main` build: [app.rerun.io](https://app.rerun.io/pr/4679/index.html?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [app.rerun.io](https://app.rerun.io/pr/4679/index.html?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG

- [PR Build Summary](https://build.rerun.io/pr/4679)
- [Docs preview](https://rerun.io/preview/7f911b822059b82883b2e8d1a909819ab618ff46/docs) 
- [Examples preview](https://rerun.io/preview/7f911b822059b82883b2e8d1a909819ab618ff46/examples) 
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

### CODE REVIEW

File: crates/re_space_view_spatial/src/heuristics.rs [hunk 1]
```diff
@@ -186,7 +186,7 @@ fn update_depth_cloud_property_heuristics(
                 properties.backproject_radius_scale = EditableAutoValue::Auto(1.0);
             }
 
-            entity_properties.update(ent_path.clone(), properties);
+            entity_properties.overwrite_properties(ent_path.clone(), properties);
```
Comment (jleibs) [inline crates/re_space_view_spatial/src/heuristics.rs:189]: This seems like the opposite of what we want.  If an entity has both a depth heuristic and a pinhole heuristic, only one of these is going to end up being applied.

Comment (Wumpf) [reply crates/re_space_view_spatial/src/heuristics.rs:189]: I don't think that's true. Each time we first retrieve `properties` via `entity_properties.get` which will have the updated value. None of the things we set here overwrite each other directly

Comment (jleibs) [reply crates/re_space_view_spatial/src/heuristics.rs:189]: Ahh -- I needed to expand to see the context that this is a read-edit-write loop and not just a blind update.  Still feels fragile, but as I've mentioned, hopefully this is all going away soon enough when we split properties into their own components.

**Review by jleibs — APPROVED** [review]
