### PR TITLE
Fix log spam on Windows when shutting down viewer

### LINKED ISSUE #6099: winsock logspam when closing the windows viewer
Getting lots of `[2024-04-24T14:12:00Z WARN  re_sdk_comms::server] Failed to accept incoming SDK client: Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)` from python when closing the viewer.

repro: run `pixi run -e examples structure_from_motion`, close the viewer after python is done. observe logspam

### PR DESCRIPTION
**Pull request by Wumpf**
### What

* Fixes #6099

Regressed recently with http server rewrite.

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using examples from latest `main` build: [rerun.io/viewer](https://rerun.io/viewer/pr/6118?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [rerun.io/viewer](https://rerun.io/viewer/pr/6118?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!

- [PR Build Summary](https://build.rerun.io/pr/6118)
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

File: crates/re_sdk_comms/src/server.rs [hunk 1]
```diff
@@ -135,6 +135,32 @@ fn listen_for_new_clients(listener: &TcpListener, options: ServerOptions, tx: &S
...
+                            WSANOTINITIALISED => {
+                                // This happens either if WSAStartup wasn't called beforehand,
+                                // or WSACleanup was called as part of shutdown already.
+                                //
+                                // If we end up in here it's almost certainly the later case
+                                // which implies that the process is shutting down.
+                                break;
+                            }
+                            WSAEINTR => {
+                                // A blocking operation as interrupted.
```
Comment (Wumpf) [inline crates/re_sdk_comms/src/server.rs:154]:
```suggestion
                                // A blocking operation was interrupted.
```

File: crates/re_sdk_comms/src/server.rs [hunk 2]
```diff
@@ -135,6 +135,32 @@ fn listen_for_new_clients(listener: &TcpListener, options: ServerOptions, tx: &S
                     .ok();
             }
             Err(err) => {
+                if cfg!(target_os = "windows") {
+                    const WSANOTINITIALISED: i32 = 10093;
+                    const WSAEINTR: i32 = 10004;
```
Comment (emilk) [inline crates/re_sdk_comms/src/server.rs:140]: Please add some references for these in case we need to add a third

**Review by emilk — APPROVED** [review]
