### PR TITLE
C++ fix failure to serialize empty component arrays / archetypes

### LINKED ISSUE #3840: C++ arrow failure when logging empty vector
Logging an empty vector of 3d points gives:
```
Failed to parse Arrow IPC encapsulated message: No Chunk found in stream
```

(maybe relevant: it was logged through a custom ComponentBatchAdapter, adding stuff to it worked though)

### PR DESCRIPTION
**Pull request by Wumpf**
### What

* Fixes #3840

The actual fix is isolated to the second commit (c34e168d9e88b7a9cbd693c9bc10a9cf5187ec36).

The first makes serialization code nicer and it's what's left of my attempt to solve it on the C++ side which I gave upon eventually (but it was very obviously worth keeping)

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested [demo.rerun.io](https://demo.rerun.io/pr/3919) (if applicable)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG

- [PR Build Summary](https://build.rerun.io/pr/3919)
- [Docs preview](https://rerun.io/preview/daf52e6864d771cd8ca9f312284c555bd76b5f46/docs) 
- [Examples preview](https://rerun.io/preview/daf52e6864d771cd8ca9f312284c555bd76b5f46/examples) 
- [Recent benchmark results](https://ref.rerun.io/dev/bench/)
- [Wasm size tracking](https://ref.rerun.io/dev/sizes/)

### CODE REVIEW

File: crates/rerun_c/src/lib.rs [hunk 1]
```diff
@@ -534,8 +540,11 @@ fn parse_arrow_ipc_encapsulated_message(
     let chunks = chunks.map_err(|err| format!("Arrow error: {err}"))?;
 
     if chunks.is_empty() {
-        return Err("No Chunk found in stream".to_owned());
+        // This might be a bug in arrow2 or the C++ SDK, but it seems that when we send an
+        // IPC with an empty array from C++ we don't get any arrays here at all.
+        return Ok(arrow2::array::NullArray::new_empty(arrow2::datatypes::DataType::Null).boxed());
```
Comment (teh-cmc) [inline crates/rerun_c/src/lib.rs:545]: That's going to throw an error at runtime, we cannot blindly change the type of whatever was being logged to `Null`.

Hitting this path should definitely return an error; I'm looking into the root cause.

**Review by teh-cmc — CHANGES_REQUESTED** [review]

**Review by teh-cmc — COMMENTED** [review]
:+1:

**Review by teh-cmc — APPROVED** [review]
