### PR TITLE
Fix a drag-and-drop display regression

### LINKED ISSUE #8204: Drag-and-drop in the blueprint tree has glitch
Apparently introduced in 0.19.

https://github.com/user-attachments/assets/5e85a687-2fb7-4cf2-8970-774374324206

### PR DESCRIPTION
**Pull request by abey79**
### Related

* Closes #8204

### What

This PR fix a display regression introduced in 0.17

#### 0.16

https://github.com/user-attachments/assets/6855b0e0-b5d7-415d-9ea5-e8d51d3111fa

#### 0.17

Note the busy hover highlight and the confusing target-container white frame.

https://github.com/user-attachments/assets/08085dca-3150-4f01-9d51-c3e981c08651

#### This PR

https://github.com/user-attachments/assets/c100b858-4d97-45f2-85a2-ea17e3f9d0c5

### CODE REVIEW

File: crates/viewer/re_ui/src/list_item/list_item.rs [hunk 1]
```diff
@@ -338,6 +335,10 @@ impl ListItem {
             style_response.hovered = true;
         }
 
+        if egui::DragAndDrop::has_any_payload(ui.ctx()) {
+            //style_response.hovered = false;
+        }
```
Comment (Wumpf) [inline crates/viewer/re_ui/src/list_item/list_item.rs:340]: dead code?

**Review by Wumpf — APPROVED** [review]
subtle, but now I can't unsee and need this! 😄

File: crates/viewer/re_ui/src/list_item/list_item.rs (hunk 1 above)
Comment (abey79) [reply crates/viewer/re_ui/src/list_item/list_item.rs:340]: 🤦🏻
