### PR TITLE
Fix failing to preview small images

### LINKED ISSUE #3430: Viewer refuses to display images which have too large of an aspect ratio
**Describe the bug**
When logging an image with an extremely high aspect ratio. For example:
```
rr.experimental.log("image", rr.archetypes.Image(np.ones(shape=(4000, 2, 1))))
```
We just get an error: `Condition failed: 'resolution_in_pixel[0] > 0 && resolution_in_pixel[1] > 0'`

**To Reproduce**
```
rr.experimental.log("image", rr.archetypes.Image(np.ones(shape=(4000, 2, 1))))
```

**Expected behavior**
Image should be displayed.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: 

**Rerun version**
Presumably all versions.

### PR DESCRIPTION
**Pull request by Wumpf**
### What

* Fixes #3430

Changed the way we deal with image previews. They now occupy always the requested size (previously, they'd expand to a max size) and the image displayed within may be stretched in rare situations.
Fixed-sized-ness of the preview image is an improvement in thus far as I think as it makes ui layouting a bit easier and more predictable, but I had to add a flag to not do so on hovering the preview since we would have a lot of empty space there otherwise.

Test code:
```python
import rerun as rr
import numpy as np

rr.init("sliver image", spawn=True)

slow_gradient = np.arange(0, 1.0, 1.0 / 1000, dtype=float)
rr.log("image", rr.Image([slow_gradient]))

slow_gradient_rot = slow_gradient.reshape((slow_gradient.shape[0], 1))
rr.log("image2", rr.Image(slow_gradient_rot))
```

-------------

Before with hovering the preview:
horizontal:
image
vertical:
image
car:
image

-------------

After with hovering the preview:
horizontal:
image
vertical:
image
car:
image

-------------

I originally also wanted to tackle increasing the default zoom in the viewport. Had some initial success but found getting the zoom state correctly set in all situations too fiddely, so gave up on this for now. This aspect will be need to be re-visited anyways when we drop the scroll bars as long planned.

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested [demo.rerun.io](https://demo.rerun.io/pr/3520) (if applicable)

- [PR Build Summary](https://build.rerun.io/pr/3520)
- [Docs preview](https://rerun.io/preview/cd19bd3a7a86d1f01aa1359645777770e5c62ece/docs) 
- [Examples preview](https://rerun.io/preview/cd19bd3a7a86d1f01aa1359645777770e5c62ece/examples) 
- [Recent benchmark results](https://ref.rerun.io/dev/bench/)
- [Wasm size tracking](https://ref.rerun.io/dev/sizes/)

### CODE REVIEW

**Comment by emilk** [comment]
> As visible, the cropping makes the larger previews ofc less truthful as well. The only other way to deal with this is stretching which may be acceptable in these cases

I think stretching to at least on ui point wide/high makes perfect sense

**Comment by Wumpf** [comment]
for gradients it's the obvious thing, but we may also run into this with images that aren't gradient, they just happen to haven an awful aspect ratio

File: crates/re_data_ui/src/image.rs [hunk 1]
```diff
@@ -109,26 +109,27 @@ fn tensor_ui(
...
+                        let preview_size = Vec2::splat(400.0);
+                        show_image_preview(
                             ctx.render_ctx,
                             ctx.re_ui,
                             ui,
                             texture.clone(),
                             &debug_name,
-                            max_size,
+                            preview_size,
+                            true,
```
Comment (emilk) [inline crates/re_data_ui/src/image.rs:132]: enum!

File: crates/re_data_ui/src/image.rs [hunk 2]
```diff
@@ -109,26 +109,27 @@ fn tensor_ui(
...
-                        max_size,
+                        preview_size,
+                        false,
                     )
                     .on_hover_ui(|ui| {
-                        // Show larger image on hover
-                        let max_size = Vec2::splat(400.0);
-                        show_image_at_max_size(
+                        // Show larger image on hover.
+                        let preview_size = Vec2::splat(400.0);
```
Comment (emilk) [inline crates/re_data_ui/src/image.rs:124]: Will small 20x20 images now be blown up to 400x400?

**Comment by Wumpf** [comment]
🤔 but maybe stretching to the min size might be the better call. After all the min size is still tiny, you won't notice that it's stretched no matter the content

**Comment by Wumpf** [comment]
okay let's try that instead. should be simpler code as well :/

File: crates/re_data_ui/src/image.rs (hunk 2 above)
Comment (Wumpf) [reply crates/re_data_ui/src/image.rs:124]: they would with this. But I'd reason this is actually a good thing. Should a 2x2 image really show as a 2x2 preview?

Comment (Wumpf) [reply crates/re_data_ui/src/image.rs:124]: it is nearest neighbor already :)
As discussed on slack as well I left a note ✔️

File: crates/re_data_ui/src/image.rs [hunk 3]
```diff
@@ -230,26 +232,77 @@ fn texture_size(colormapped_texture: &ColormappedTexture) -> Vec2 {
     egui::vec2(w as f32, h as f32)
 }
 
-fn show_image_at_max_size(
+#[derive(Clone, Copy, PartialEq, Eq)]
+enum PreviewSizeShrink {
+    /// Stick to the desired size. May cause
```
Comment (emilk) [inline crates/re_data_ui/src/image.rs:237]: …irritated bowls?

File: crates/re_data_ui/src/image.rs [hunk 4]
```diff
@@ -230,26 +232,77 @@ fn texture_size(colormapped_texture: &ColormappedTexture) -> Vec2 {
...
+        // But it can happen that this makes one of the axis too small, so let's stretch it if needed.
+        egui::Vec2::splat(zoom).at_least(min_size / texture_size)
+    };
+
+    let scaled_texture_size = texture_size * texture_scale_factor;
+
+    // Request the desired size, but shrink one dimension if the texture is too wide/narrow if so required.
+    let requested_rect = match image_fit {
+        PreviewSizeShrink::DontShrink => desired_size,
+        PreviewSizeShrink::ShrinkToTextureAspectRatio => {
```
Comment (emilk) [inline crates/re_data_ui/src/image.rs:280]: I don't follow this logic - we should always respect aspect ratio, with the single exception of very thin images - and that exception is always a valid exception, afaict. So why is there an option here to do different things? Shouldn't we always resize the image to the given desired_size (in an aspect-ratio-respecting manner) and then slightly adjust one axis if it becomes thinner than `MIN_SIZE`?

Comment (Wumpf) [reply crates/re_data_ui/src/image.rs:280]: Maybe it's just poorly named: What I'm after is that the reserved ui space would adapt to the texture or not.

Situation where we'd like the ui element for the preview to take a fixed amount of space:
image
-> If this icon is a vertical gradient, I still want it to take the same amount of space left and right because otherwise it doesn't align well if there's more such lines below, causing a less tidy look

This here on the other hand is pretty much the only situation where I do want the ui space to adapt to the aspect ratio of the image.
image
Having always the 400x400 box here would be pretty weird for a thin gradient, we want to shrink the ui around it without making the image smaller.

File: crates/re_data_ui/src/image.rs (hunk 3 above)
Comment (Wumpf) [reply crates/re_data_ui/src/image.rs:237]: May cause copy and paste error without reading over it again. :nod:

File: crates/re_data_ui/src/image.rs (hunk 4 above)
Comment (Wumpf) [reply crates/re_data_ui/src/image.rs:280]: So this option isn't really about what happens with the texture but what happens with the allocated space. Naming should reflect this better.

But before I touch stuff again, do you agree that the outlined behavior makes sense or do you think this is weird/confusing/wrong?

Comment (emilk) [reply crates/re_data_ui/src/image.rs:280]: > If this icon is a vertical gradient, I still want it to take the same amount of space left and right because otherwise it doesn't align well if there's more such lines below, causing a less tidy look

That makes sense - in the table you want all preview images to take up the same amount of space.

But that can be made a lot simpler with:

```rs
ui.allocate_ui(max_image_size, |ui| {
    show_image_preview(…, max_image_size)
});
```

no need for `show_image_preview` to worry about all that complexity.

(also, `show_image_preview` should be called `image_preview_ui`)

**Review by emilk — APPROVED** [review]

File: crates/re_data_ui/src/image.rs [hunk 5]
```diff
@@ -232,77 +239,38 @@ fn texture_size(colormapped_texture: &ColormappedTexture) -> Vec2 {
...
-
 /// Shows preview of an image.
 ///
-/// Displays the image in inside the desired size.
-/// Image will be stretched in the dimensions it is below a certain threshold.
+/// Displays the image at the desired size, without overshooting it, and preserving aspect ration.
 ///
-/// TODO(andreas): Small images will be blown up to the desired size, this may not always be what we want.
-///                 Maybe add `PreviewSizeShrink::ShrinkToFitWithMin(egui::Vec2)`?
+/// Very extremely images will be stretched on their thin axis to make them visible.
```
Comment (Wumpf) [inline crates/re_data_ui/src/image.rs:246]:
```suggestion
/// Extremely small images will be stretched on their thin axis to make them visible.
```

**Comment by Wumpf** [comment]
cargo deny failure is a known issue
