### PR TITLE
Warn on duplicated data-loader in PATH

### LINKED ISSUE #4756: Entities with `timeless=False` are logged twice when using custom loader
**Describe the bug**
It seems that all entities with time are logged twice when using a custom loader.

Especially noticable / annoying with TextLog, as all logs appear twice.

**To Reproduce**
1. Modify the docx example by changing to `timeless=False`.
2. Log the docx via drag-and-drop or `rerun example.docx`
3. Switch to `log_time`.

The text document appears twice on the timeline.

**Expected behavior**
I'd expect the same timeline as when running
```
import rerun as rr
rr.init("test", spawn=True)
rr.log("test", rr.TextDocument("test"), timeless=False)
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Rerun version**
```rerun_py 0.12.0-rc.6 [rustc 1.74.0 (79e9716c9 2023-11-13), LLVM 17.0.4] x86_64-unknown-linux-gnu release-0.12.0 4fc0c00, built 2024-01-09T14:41:10Z```

### PR DESCRIPTION
**Pull request by teh-cmc**
image

- Fixes #4756

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using newly built examples: [app.rerun.io](https://app.rerun.io/pr/4762/index.html)
  * Using examples from latest `main` build: [app.rerun.io](https://app.rerun.io/pr/4762/index.html?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [app.rerun.io](https://app.rerun.io/pr/4762/index.html?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG

- [PR Build Summary](https://build.rerun.io/pr/4762)
- [Docs preview](https://rerun.io/preview/0539efbd2307b70f73aace4457934a0fb0893c7c/docs) 
- [Examples preview](https://rerun.io/preview/0539efbd2307b70f73aace4457934a0fb0893c7c/examples) 
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

### CODE REVIEW

**Comment by emilk** [comment]
> But why can't I see the toast ??

Probably because you log before the `re_log::ChannelLogger` is created. We should probably start storing up log messages right away on startup. It will be required for showing a history of log messages in the ui anyways.

File: crates/re_data_source/src/data_loader/loader_external.rs [hunk 1]
```diff
@@ -50,7 +50,26 @@ pub static EXTERNAL_LOADER_PATHS: Lazy<Vec<std::path::PathBuf>> = Lazy::new(|| {
...
+    let mut exe_names = executables
+        .iter()
+        .filter_map(|path| path.file_name())
+        .collect_vec();
+    exe_names.sort();
+
+    use itertools::Itertools as _;
+    for (name1, name2) in exe_names.iter().tuple_windows::<(_, _)>() {
+        if name1 == name2 {
+            re_log::warn_once!("Found duplicated data-loader in $PATH: {:?}", name1);
```
Comment (emilk) [inline crates/re_data_source/src/data_loader/loader_external.rs:68]: We should print the paths to both executables, otherwise it is very hard for a user to debug this.

**Comment by teh-cmc** [comment]
> > But why can't I see the toast ??
> 
> Probably because you log before the `re_log::ChannelLogger` is created. We should probably start storing up log messages right away on startup. It will be required for showing a history of log messages in the ui anyways, but let's do it some other time imho.

Yeah that would make sense when I load from the CLI, but I've had much weirder things happen when playing with this, even when using drag-n-drop... but anyway that's a problem for another day as you say.

File: crates/re_data_source/src/data_loader/loader_external.rs
Comment (teh-cmc) [inline crates/re_data_source/src/data_loader/loader_external.rs:1]: We might want to rerun this whole logic every time a file is loaded to really hammer the point home... I don't mind either way.

File: crates/re_data_source/src/data_loader/loader_external.rs (hunk 1 above)
Comment (teh-cmc) [reply crates/re_data_source/src/data_loader/loader_external.rs:68]: I mean `which -a` seems like the next logical step to do :shrug: but sure I can cook something up

**Comment by teh-cmc** [comment]
Updated to track the origin of duplicates.

The only thing left to decide is whether to re-warn on all file loads on just on the first one (current behavior).

**Review by jleibs — APPROVED** [review]
This seems good enough for now -- this seems safe to merge and cherry-pick with minimal testing whereas changing the logic to run on every load could have larger ripple effects.

We can make the behavior more robust in the future.
