### PR TITLE
Fix crash on empty mesh

### LINKED ISSUE #3416: Rerun viewer crashes when mesh is cleared
**Describe the bug**
When using `rr.log_mesh` / `rr2.log(..., rr2.Mesh3D(...))` and clearing the entity, the viewer crashes with the error below.

**To Reproduce**
```python
import numpy as np
import rerun as rr
import rerun.experimental as rr2

rr.init("temp_mesh", spawn=True)

rr.set_time_sequence("time", 0)
rr2.log(
    "mesh",
    rr2.Mesh3D(
        np.random.random((3, 3)),
        mesh_properties=rr2.cmp.MeshProperties([[0, 1, 2]]),
    ),
)
rr.set_time_sequence("time", 1)
rr2.log("mesh", rr2.Clear(False))
```
If it doesn't crash immediately, try scrolling the timeline in the viewer.

**Backtrace**
```
thread 'ThreadId(1)' panicked at 'Buffer slices can not be empty'
wgpu-0.17.0/src/lib.rs:2720
stack backtrace:
   6: core::panicking::panic_fmt
             at core/src/panicking.rs:67:14
   7: core::panicking::panic_display
             at core/src/panicking.rs:150:5
      core::panicking::panic_str
             at core/src/panicking.rs:134:5
      core::option::expect_failed
             at core/src/option.rs:1952:5
   8: re_renderer::allocator::cpu_write_gpu_read_belt::CpuWriteGpuReadBelt::allocate
   9: re_renderer::mesh::GpuMesh::new
  10: re_renderer::resource_managers::mesh_manager::MeshManager::create

```

**Rerun version**
```
rerun_py 0.9.0-alpha.4 [rustc 1.72.1 (d5c2e9c34 2023-09-13), LLVM 16.0.5] x86_64-unknown-linux-gnu 2e9df4c, built 2023-09-23T09:59:35Z
```

### PR DESCRIPTION
**Pull request by Wumpf**
### What

* Fixes #3416

Two steps:
* make the crash merely a warning by propagating allocation failure on the belt
* fix that warning (previously crash) in meshes.rs

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested [demo.rerun.io](https://demo.rerun.io/pr/3448) (if applicable)

- [PR Build Summary](https://build.rerun.io/pr/3448)
- [Docs preview](https://rerun.io/preview/87e2824fe6d34c97720d53cc663211b09c1a5ecb/docs) 
- [Examples preview](https://rerun.io/preview/87e2824fe6d34c97720d53cc663211b09c1a5ecb/examples) 
- [Recent benchmark results](https://ref.rerun.io/dev/bench/)
- [Wasm size tracking](https://ref.rerun.io/dev/sizes/)

### CODE REVIEW

File: crates/re_renderer/src/line_strip_builder.rs [hunk 1]
```diff
@@ -43,7 +43,9 @@ impl LineStripSeriesBuilder {
                 &ctx.device,
                 &ctx.gpu_resources.buffers,
                 LineDrawData::MAX_NUM_STRIPS,
-            );
+            )
+            .unwrap_debug_or_log_error()
+            .expect("Failed to allocate picking instance id buffer"); // TODO(#3408): Should never happen but should propagate error anyways
```
Comment (emilk) [inline crates/re_renderer/src/line_strip_builder.rs:48]: chaining `unwrap_debug_or_log_error` and `expect` makes no sense.

If you are going to panic anyway, just use `expect`

```suggestion
            .expect("Failed to allocate picking instance id buffer"); // TODO(#3408): Should never happen but should propagate error anyways
```

File: crates/re_renderer/src/point_cloud_builder.rs [hunk 2]
```diff
@@ -31,19 +31,26 @@ impl PointCloudBuilder {
...
+        let color_buffer = ctx
+            .cpu_write_gpu_read_belt
+            .lock()
+            .allocate::<Color32>(
+                &ctx.device,
+                &ctx.gpu_resources.buffers,
+                PointCloudDrawData::MAX_NUM_POINTS,
+            )
+            .unwrap_debug_or_log_error()
+            .expect("Failed to allocate color buffer"); // TODO(#3408): Should never happen but should propagate error anyways
```
Comment (emilk) [inline crates/re_renderer/src/point_cloud_builder.rs:43]:
```suggestion
            .expect("Failed to allocate color buffer"); // TODO(#3408): Should never happen but should propagate error anyways
```

File: crates/re_renderer/src/point_cloud_builder.rs [hunk 3]
```diff
@@ -31,19 +31,26 @@ impl PointCloudBuilder {
...
         let picking_instance_ids_buffer = ctx
             .cpu_write_gpu_read_belt
             .lock()
             .allocate::<PickingLayerInstanceId>(
                 &ctx.device,
                 &ctx.gpu_resources.buffers,
                 PointCloudDrawData::MAX_NUM_POINTS,
-            );
+            )
+            .unwrap_debug_or_log_error()
```
Comment (emilk) [inline crates/re_renderer/src/point_cloud_builder.rs:52]:
```suggestion
```

**Review by emilk — APPROVED** [review]
