### PR TITLE
Make video decoding errors recoverable

### LINKED ISSUE #7491: Video decoder with multiple streams gets into error state after some scrubbing
Reproed while reviewing https://github.com/rerun-io/rerun/pull/7490, mp4 update and way the new preview plays might be relevant.

Used video: https://drive.google.com/file/d/19f_xKtM0ZcrLgSMfOAx2wCFJkEbB-g_m/view?usp=sharing

Did a bunch of seeks while the video is selected so that the preview keeps playing. Eventually both decoders get into an unrecoverable state:
image

Some more relevant browser log - looks like it first fails to decode but then can't recover:
```
[re_renderer::allocator::gpu_readback_belt] re_renderer/src/allocator/gpu_readback_belt.rs:278: Allocating new GpuReadbackBelt chunk of size 0.1 MiB [RemoteViewer.iXPtKCIw.js line 1 > Function:3244:17](https://rerun.io/_app/immutable/chunks/RemoteViewer.iXPtKCIw.js%20line%201%20%3E%20Function)
ERROR: [re_renderer::video::decoder::web] re_renderer/src/video/decoder/web.rs:421: failed to decode video: EncodingError: The given encoding is not supported. [RemoteViewer.iXPtKCIw.js line 1 > Function:3250:17](https://rerun.io/_app/immutable/chunks/RemoteViewer.iXPtKCIw.js%20line%201%20%3E%20Function)
ERROR: [re_renderer::video::decoder::web] re_renderer/src/video/decoder/web.rs:341: Failed to decode video chunk: InvalidStateError: VideoDecoder.decode: Decoder must be configured first [RemoteViewer.iXPtKCIw.js line 1 > Function:3250:17](https://rerun.io/_app/immutable/chunks/RemoteViewer.iXPtKCIw.js%20line%201%20%3E%20Function)
ERROR: [re_renderer::video::decoder::web] re_renderer/src/video/decoder/web.rs:421: failed to decode video: EncodingError: The given encoding is not supported. [RemoteViewer.iXPtKCIw.js line 1 > Function:3250:17](https://rerun.io/_app/immutable/chunks/RemoteViewer.iXPtKCIw.js%20line%201%20%3E%20Function)
[re_renderer::video::decoder::web] re_renderer/src/video/decoder/web.rs:84: Dropping VideoDecoder [RemoteViewer.iXPtKCIw.js line 1 > Function:3244:17](https://rerun.io/_app/immutable/chunks/RemoteViewer.iXPtKCIw.js%20line%201%20%3E%20Function)
[re_renderer::video::decoder::web] re_renderer/src/video/decoder/web.rs:86: Error when closing video decoder: InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable [RemoteViewer.iXPtKCIw.js line 1 > Function:3250:17](https://rerun.io/_app/immutable/chunks/RemoteViewer.iXPtKCIw.js%20line%201%20%3E%20Function)
[re_renderer::video::decoder::web] re_renderer/src/video/decoder/web.rs:84: Dropping VideoDecoder [RemoteViewer.iXPtKCIw.js line 1 > Function:3244:17](https://rerun.io/_app/immutable/chunks/RemoteViewer.iXPtKCIw.js%20line%201%20%3E%20Function)
[re_renderer::video::decoder::web] re_renderer/src/video/decoder/web.rs:86: Error when closing video decoder: InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable
```

### PR DESCRIPTION
**Pull request by Wumpf**
### What

* Fixes #7491

Unlike the issue title implies, the test video here always fails decoding at some point for Firefox & Chrome, it's not entirely deterministic though when & how often.

https://github.com/user-attachments/assets/8b04af17-66d2-47b0-8314-da9f3d5ee3f3

Latest version tested on Firefox & Chrome on Mac. Previously tested a similar changeset on Firefox & Chrome on Windows.

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using examples from latest `main` build: [rerun.io/viewer](https://rerun.io/viewer/pr/7521?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [rerun.io/viewer](https://rerun.io/viewer/pr/7521?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!
* [x] If have noted any breaking changes to the log API in `CHANGELOG.md` and the migration guide

- [PR Build Summary](https://build.rerun.io/pr/7521)
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

File: crates/viewer/re_renderer/src/video/decoder/web.rs [hunk 1]
```diff
@@ -300,20 +295,37 @@ impl VideoDecoder {
...
         let Some(frame_idx) = latest_at_idx(
             &frames,
             |frame| frame.composition_timestamp,
             &presentation_timestamp,
         ) else {
-            // no buffered frames - texture will be blank
+            // No buffered frames - texture will be blank.
+
+            // Might this be due to an error?
+            if let Some(last_decoding_error) = decoder_output.last_decoding_error.clone() {
```
Comment (jprochazk) [inline crates/viewer/re_renderer/src/video/decoder/web.rs:314]: question: Doing it this way makes sense to me, but I wonder if we should unconditionally check for errors, instead of only in case we don't have any buffered frames? Would that make a difference in any case?

File: crates/viewer/re_renderer/src/video/mod.rs [hunk 2]
```diff
@@ -47,17 +47,15 @@ pub enum DecodingError {
     NegativeTimestamp,
 }
 
+pub type FrameDecodingResult = Result<DecodedFrame, DecodingError>;
+
 /// Information about the status of a frame decoding.
-pub enum FrameDecodingResult {
+pub enum DecodedFrame {
```
Comment (jprochazk) [inline crates/viewer/re_renderer/src/video/mod.rs:53]: nit: The frame may not be decoded yet, so I'm not sure about the naming here. Maybe `DecoderOutput`? We could also just use `Result<Poll<GpuTexture2D>, DecodingError>`

**Review by jprochazk — APPROVED** [review]
Cool!

File: crates/viewer/re_renderer/src/video/mod.rs (hunk 2 above)
Comment (Wumpf) [reply crates/viewer/re_renderer/src/video/mod.rs:53]: `Poll<GpuTexture2D>` would mean that the other side has to store the last known good texture and deal with all of that, also incompatible with the idea of small previews. But I like the naming suggestion!

File: crates/viewer/re_renderer/src/video/decoder/web.rs (hunk 1 above)
Comment (Wumpf) [reply crates/viewer/re_renderer/src/video/decoder/web.rs:314]: Given that we throw away everything when reseting because of error it really shouldn't make a difference - if we fully recoverd by the time we enter here (impossible since we haven't given control back to the browser) then we wouldn't care about the error no matter how much time passed.
It's more that my internal logic went "only look for errors if we're out of frames" 🤔

File: crates/viewer/re_renderer/src/video/mod.rs (hunk 2 above)
Comment (Wumpf) [reply crates/viewer/re_renderer/src/video/mod.rs:53]: oh I already used up `DecoderOutput` now as an internal structure :thinking:
Hmm I can at least offer a counter argument that even on `Pending` we still tend to return a decoded frame...
