### PR TITLE
Fix decoding errors for MCAP files with gaps in protobufs

### LINKED ISSUE #12410: Rerun crashes when trying to load protobuf MCAP file
<!--
First look if there is already a similar bug report. If there is, upvote the issue with 👍
-->

**Describe the bug**
Rerun crashes when trying to load protobuf MCAP file

**To Reproduce**
1. Drag protobuf-encoded file into rerun or use the cmdline to open it
2. Observe crash

**Expected behavior**
Maybe some conversion error output or something, but no crash should happen.

**Backtrace**
With internal information redacted:
```
thread 'load_mcap("recovered.mcap"' panicked at 'StructBuilder (Schema { fields: [Field { name: "XX" }, Field { name: XX }, Field { name: "XX" }, Field { name: "XX" }, Field { name: "XX" }, Field { name: "XX" }, Field { name: "XX" }, Field { name: "XX" }, Field { name: "XX" }, Field { name: "XX" }], metadata: {} }) and field_builder with index 0 (Struct([Field { name: "XX", data_type: UInt64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: "XX", data_type: UInt32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }])) are of unequal lengths: (0 != 10).'
arrow-array-56.2.0/src/builder/struct_builder.rs:269
stack backtrace:
   6: core::panicking::panic_fmt
   7: arrow_array::builder::struct_builder::StructBuilder::validate_content::{{closure}}::panic_cold_display
   8: arrow_array::builder::struct_builder::StructBuilder::validate_content
   9: arrow_array::builder::struct_builder::StructBuilder::finish
  10: <re_mcap::layers::protobuf::ProtobufMessageParser as re_mcap::parsers::decode::MessageParser>::finalize
  11: <re_mcap::layers::MessageLayerRunner as re_mcap::layers::Layer>::process
  12: re_mcap::layers::ExecutionPlan::run
  13: re_data_loader::loader_mcap::load_mcap
  14: re_data_loader::loader_mcap::load_mcap_mmap
  15: std::sys::backtrace::__rust_begin_short_backtrace
  16: core::ops::function::FnOnce::call_once{{vtable.shim}}
  17: std::sys::pal::unix::thread::Thread::new::thread_start
  18: start_thread
             at pthread_create.c:442:8
  19: __GI___clone3
             at clone3.S:81:0
```
There are also some errors in the lead-up to the crash:
```
[2026-01-12T22:16:16Z ERROR re_mcap::layers] Failed to decode message on channel /XX/XX: missing protobuf field 8                                                                                                                                                                                                                                                       
[2026-01-12T22:16:16Z ERROR re_mcap::layers] Failed to decode message on channel /XX/XX: missing protobuf field 1  
```
These errors don't make sense to me because the fields are not `required` fields. They are `optional` according to the output of `mcap list schemas file.mcap`.

**Desktop:**
Ubuntu 22.04

**Rerun version**
```
rerun-cli 0.28.1 (base lance map_view nasm native_viewer oss_server perf_telemetry re_server release_full release_no_web_viewer web_viewer) [rustc 1.88.0 (6b00bc388 2025-06-23), LLVM 20.1.5] x86_64-unknown-linux-gnu prepare-release-0.28.1 ac98620, built 2025-12-19T21:06:08.748579589Z
Video features: av1 ffmpeg nasm
```

**Additional context**
The protobuf data is defined with `syntax = "proto3";`, where all data is optional by default, so it should be expected that some fields are missing.

### PR DESCRIPTION
**Pull request by grtlr**
### Related

* Closes #12410.
* Closes RR-3309.

### What

We didn't properly account for gaps in the schema. This PR does three things:

* Prevent crashes by making the `StructBuilder` logic more robust.
* Properly handle gaps in the schema.
* Add test cases for the above.

### CODE REVIEW

File: crates/store/re_mcap/src/layers/protobuf.rs [hunk 1]
```diff
@@ -650,4 +691,249 @@ mod test {
...
+
+                write_message(&mut writer, channel_id, &msg, 100 + i)
+                    .expect("failed to write message");
+            }
+
+            let summary = writer.finish().expect("finishing writer failed");
+            (summary, writer.into_inner().into_inner())
+        };
+
+        // With the fix, field number gaps should be handled correctly:
```
Comment (MichaelGrupp) [inline crates/store/re_mcap/src/layers/protobuf.rs]: These tests/comments look like AI-generated? "With the fix, ..." --> remove, or be more specific for future readers what "the fix" means.

File: crates/store/re_mcap/src/layers/protobuf.rs [hunk 2]
```diff
@@ -650,4 +691,249 @@ mod test {
...
+        // and correctly map them to their actual protobuf field numbers.
+        // Result: All fields should be read correctly with their values intact!
+        let chunks = run_layer(&summary, buffer.as_slice());
+
+        // Verify we got all messages
+        assert_eq!(chunks.len(), 1);
+        assert_eq!(chunks[0].num_rows(), 10);
+
+        // Verify the data contains actual values, not nulls
+        // (Before the fix, description and count would be null due to field mapping bug)
```
Comment (MichaelGrupp) [inline crates/store/re_mcap/src/layers/protobuf.rs]: Another reference to "the fix" and a bug.

File: crates/store/re_mcap/src/layers/protobuf.rs [hunk 3]
```diff
@@ -650,4 +691,249 @@ mod test {
...
+
+            // Message 1: has all fields
+            let dynamic_message_1 = DynamicMessage::parse_text_format(
+                person_message.clone(),
+                "name: \"Alice\" id: 123 status: 1",
+            )
+            .expect("failed to parse text format");
+
+            // Message 2: has only name (id and status missing)
+            // This tests the bug - struct with missing optional fields
```
Comment (MichaelGrupp) [inline crates/store/re_mcap/src/layers/protobuf.rs]: ....

File: crates/store/re_mcap/src/layers/protobuf.rs [hunk 4]
```diff
@@ -650,4 +691,249 @@ mod test {
...
+                DynamicMessage::parse_text_format(person_message.clone(), "id: 456")
+                    .expect("failed to parse text format");
+
+            // Message 4: has only status (name and id missing)
+            let dynamic_message_4 =
+                DynamicMessage::parse_text_format(person_message.clone(), "status: 2")
+                    .expect("failed to parse text format");
+
+            // Message 5: empty message (all fields missing)
+            // This is the most extreme case - may trigger the crash
```
Comment (MichaelGrupp) [inline crates/store/re_mcap/src/layers/protobuf.rs]: "the crash"

File: crates/store/re_mcap/src/layers/protobuf.rs (hunk 1 above)
Comment (MichaelGrupp) [reply crates/store/re_mcap/src/layers/protobuf.rs]: Also, more minor/optional regarding consistency: the comments in the (hand-written?) `protobuf.rs` end with a period, these don't.

**Comment by grtlr** [comment]
Ah shoot, sorry I'll do another pass.

**Comment by icolwell-as** [comment]
When I compiled this branch it threw the following warning:
```
warning: variant `MissingField` is never constructed
  --> crates/store/re_mcap/src/layers/protobuf.rs:51:5
   |
24 | enum ProtobufError {
   |      ------------- variant in this enum
...
51 |     MissingField { field: u32 },
   |     ^^^^^^^^^^^^
   |
   = note: `ProtobufError` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
   = note: `#[warn(dead_code)]` on by default
```

File: crates/store/re_mcap/src/layers/protobuf.rs [hunk 5]
```diff
@@ -606,14 +702,101 @@ mod test {
         chunks
     }
 
+    /// Helper to create test messages with various field combinations.
+    fn create_test_messages(person_message: &MessageDescriptor) -> Vec<DynamicMessage> {
```
Comment (MichaelGrupp) [inline crates/store/re_mcap/src/layers/protobuf.rs:706]: These helpers can probably be annotated `#[cfg(test)]`?

Comment (MichaelGrupp) [reply crates/store/re_mcap/src/layers/protobuf.rs:706]: Or test `mod` in this file

Comment (grtlr) [reply crates/store/re_mcap/src/layers/protobuf.rs:706]: Admittedly a bit unconventional, but they are in `mod integration_tests`, which is marked as `cfg(test)`.

I'm not quite sure how to structure this entire file going forward, which is why I did this in the meantime.
