### PR TITLE
Fixes broken tile resize introduced by #5044

### LINKED ISSUE #5061: Can't resize space views
Open https://app.rerun.io/commit/b9cd458/index.html and go to any example.

https://github.com/rerun-io/rerun/assets/2624717/95fdf3f2-1caf-414d-b3e5-e44f0ecda4b8

### PR DESCRIPTION
**Pull request by abey79**
### What

- Fixes #5061

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using newly built examples: [app.rerun.io](https://app.rerun.io/pr/5064/index.html)
  * Using examples from latest `main` build: [app.rerun.io](https://app.rerun.io/pr/5064/index.html?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [app.rerun.io](https://app.rerun.io/pr/5064/index.html?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG

- [PR Build Summary](https://build.rerun.io/pr/5064)
- [Docs preview](https://rerun.io/preview/da3ca8a3ebf53647a43095c403a63b61007417c6/docs) 
- [Examples preview](https://rerun.io/preview/da3ca8a3ebf53647a43095c403a63b61007417c6/examples) 
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

### CODE REVIEW

File: crates/re_viewport/src/viewport.rs [hunk 1]
```diff
@@ -832,9 +831,12 @@ impl<'a, 'b> egui_tiles::Behavior<SpaceViewId> for TabViewer<'a, 'b> {
 
                 self.edited = true;
             }
-            EditAction::TabSelected => {
+            EditAction::TabSelected | EditAction::TileResized => {
                 self.edited = true;
             }
+            EditAction::TileDragged => {
+                // no synchronisation needed
```
Comment (emilk) [inline crates/re_viewport/src/viewport.rs:838]: why not?

Comment (abey79) [reply crates/re_viewport/src/viewport.rs:838]: That happens when a drag starts, so no tiles are actually modified. When the drag completes, then we get `TileDropped` and run the synchronisation.

Comment (emilk) [inline crates/re_viewport/src/viewport.rs:838]:
```suggestion
                // No synchronization needed, because TileDragged happens when a drag starts, so no tiles are actually modified. When the drag completes, then we get `TileDropped` and run the synchronization.
```

**Review by emilk — APPROVED** [review]
