### PR TITLE
C++ Warning fixes, werror on ci, C++17 compliance

### LINKED ISSUE #2903: Build with warnings as errors on CI for C++
Also, there's a bunch of warning settings not in place for rerun_cpp right now!

### PR DESCRIPTION
**Pull request by Wumpf**
### What

* Fixes #2903 
* Part of #2919
* currate warning list for gcc/clang
* enable warnings as errors on CI, for simplicity it's always active on roundtrip tests
* enable standard set of warning settings on all C++ targets
* fix warnings in codegen'ed code and manually written code
* fix accidental C++20 (should have been caught in theory by warnings but it didn't trigger for unknown reason)

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested [demo.rerun.io](https://demo.rerun.io/pr/2957) (if applicable)

- [PR Build Summary](https://build.rerun.io/pr/2957)
- [Docs preview](https://rerun.io/preview/pr%3Aandreas%2Fcpp%2Fwarning-fixes-and-ci-werror/docs)
- [Examples preview](https://rerun.io/preview/pr%3Aandreas%2Fcpp%2Fwarning-fixes-and-ci-werror/examples)

### CODE REVIEW

**Comment by emilk** [comment]
> fix accidental C++20 (should have been caught in theory by warnings but it didn't trigger for unknown reason)

Try `-Wc99-extensions`

File: tests/cpp/build_all_doc_examples.sh [hunk 1]
```diff
@@ -5,10 +5,31 @@ script_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
...
+WERROR=false
+
+while test $# -gt 0; do
+  case "$1" in
+    --werror)
+      shift
+      WERROR=true
+      ;;
+
+    *)
```
Comment (emilk) [inline tests/cpp/build_all_doc_examples.sh:18]: it would be good to error on unknown options here instead of swallowing them silently (e.g. if the user uses `-werror` or `--Werror`)

Comment (Wumpf) [reply tests/cpp/build_all_doc_examples.sh:18]: did so now as well for our publish_crates script (where I copied argument parsing from ;)

**Comment by Wumpf** [comment]
`-Wc99-extensions` sadly still didn't catch 
```
        rr_data_row c_data_row {
            .entity_path = entity_path,
            .num_instances = static_cast<uint32_t>(num_instances),
            .num_data_cells = static_cast<uint32_t>(num_data_cells),
            .data_cells = c_data_cells.get(),
        };
        ```

but left it in anyways

**Comment by Wumpf** [comment]
Remaining warning happens to be fixed in #2959. Not duplicating it in here, waiting for that instead!

File: rerun_cpp/src/rerun/recording_stream.cpp [hunk 2]
```diff
@@ -73,22 +73,19 @@ namespace rerun {
...
         // Map to C API:
-        std::vector<rr_data_cell> c_data_cells;
-        c_data_cells.reserve(num_data_cells);
-        for (size_t i = 0; i < num_data_cells; ++i) {
-            c_data_cells.push_back({
-                .component_name = data_cells[i].component_name,
-                .num_bytes = static_cast<uint64_t>(data_cells[i].buffer->size()),
-                .bytes = data_cells[i].buffer->data(),
-            });
+        std::unique_ptr<rr_data_cell[]> c_data_cells =
```
Comment (emilk) [inline rerun_cpp/src/rerun/recording_stream.cpp:76]: Why the use of a `unique_ptr` here? What was wrong with just having a vector on the stack and pointing to it?

Comment (Wumpf) [reply rerun_cpp/src/rerun/recording_stream.cpp:76]: _afaik_ std::vector never has small array optimization, so it's a heap alloc regardless

Comment (Wumpf) [reply rerun_cpp/src/rerun/recording_stream.cpp:76]: confirmed. std::vector can't implement small vector optimization because std::move on it isn't allowed to invalidate the iterator T_T
https://youtu.be/vElZc6zSIXM?t=233

Comment (emilk) [reply rerun_cpp/src/rerun/recording_stream.cpp:81]: > don't need to reserve and doesn't have additional overhead for the counter. 

`std::vector<rr_data_cell> c_data_cells{num_data_cells};`

also has no reserve, and is arguably simpler

File: CMakeLists.txt [hunk 3]
```diff
@@ -6,14 +6,43 @@ function(set_default_warning_settings target)
...
+            -Wcast-align
+            -Wcast-qual
+            -Wformat=2
+            -Wmissing-include-dirs
+            -Wnull-dereference
+            -Wpointer-arith
+            -Wshadow
+            -Wswitch-enum
+            -Wvla
+            -Wold-style-cast
```
Comment (emilk) [inline CMakeLists.txt:23]: sort!

File: crates/re_types_builder/src/codegen/cpp/mod.rs [hunk 4]
```diff
@@ -812,36 +812,47 @@ impl QuotedObject {
...
+                            _data.#field_ident = other._data.#field_ident;
+                            break;
+                        }
+                    });
+                }
+            }
+
+            let trivial_memcpy = quote! {
+                const void *otherbytes = reinterpret_cast<const void *>(&other._data);
+                void *thisbytes = reinterpret_cast<void *>(&this->_data);
```
Comment (emilk) [inline crates/re_types_builder/src/codegen/cpp/mod.rs:840]: nit: let use the same style as we specify in `.clang-format`

```suggestion
                const void* otherbytes = reinterpret_cast<const void*>(&other._data);
                void* thisbytes = reinterpret_cast<void *>(&this->_data);
```

**Review by emilk — APPROVED** [review]
Always nice to run on as many warnings as possible, especially for unsafe languages

File: rerun_cpp/src/rerun/recording_stream.cpp (hunk 2 above)
Comment (Wumpf) [reply rerun_cpp/src/rerun/recording_stream.cpp:81]: That one is _technically_ slower since it zero-inits all elements. But yeah I guess that's the most appropriate one here!
