### PR TITLE
Fix web viewer feature flags

### LINKED ISSUE #8294: `map-view` feature not enabled in web-viewer
Not on any PR builds, nor on 0.20.2 viewer at https://rerun.io/viewer?url=https%3A%2F%2Fapp.rerun.io%2Fversion%2F0.20.2%2Fexamples%2Fnuscenes_dataset.rrd

### PR DESCRIPTION
**Pull request by jprochazk**
### Related

* Closes #8294

### What

* `build-web-viewer` now propagates `--no-default-features`, and doesn't include it by default
* Made `map_view` a default feature in `re_viewer`

### CODE REVIEW

File: rerun_js/web-viewer/build-wasm.mjs [hunk 1]
```diff
@@ -31,7 +31,8 @@ function buildWebViewer(mode) {
       "cargo run -p re_dev_tools -- build-web-viewer",
       modeFlags,
       "--target no-modules-base",
-      "--features grpc",
+      "--no-default-features",
+      "--features grpc,map_view",
```
Comment (emilk) [inline rerun_js/web-viewer/build-wasm.mjs:35]: I suggest we have a `release = ["grpc", "map_view"]` feature in `re_viewer` instead. It feels like a more discoverable location for controlling what goes into the release.

```suggestion
      "--features release",
```

Comment (jprochazk) [reply rerun_js/web-viewer/build-wasm.mjs]: At this point I just made `map_view` the default. I don't agree with the `release` feature for web viewer specifically, it makes sense for rerun-cli because there it makes it possible for it to be compiled without `nasm`, and with `-F release` in case you do want `nasm`.

Comment (jprochazk) [reply rerun_js/web-viewer/build-wasm.mjs]: The big problem here imho was `build_web_viewer` silently passing `--no-default-features` to the `re_viewer` build. To discover all the features being requested, you look through the commands that mention `build-web-viewer`, same as with every other non-web build command.

**Comment by jprochazk** [comment]
Seems to work: https://rerun.io/viewer/pr/8295?url=https%3A%2F%2Fapp.rerun.io%2Fversion%2F0.20.2%2Fexamples%2Fnuscenes_dataset.rrd

File: rerun_js/web-viewer/build-wasm.mjs [hunk 2]
```diff
@@ -31,7 +31,8 @@ function buildWebViewer(mode) {
       "cargo run -p re_dev_tools -- build-web-viewer",
       modeFlags,
       "--target no-modules-base",
-      "--features grpc",
+      "--no-default-features",
+      "--features grpc,map_view", // no `analytics`
```
Comment (emilk) [inline rerun_js/web-viewer/build-wasm.mjs:35]: why not?

File: pixi.toml [hunk 3]
```diff
@@ -175,29 +175,29 @@ rerun-web = { cmd = "cargo run --package rerun-cli --no-default-features --featu
...
+rerun-web-release = { cmd = "cargo run --package rerun-cli --no-default-features --features web_viewer,map_view,grpc --release -- --web-viewer", depends_on = [
   "rerun-build-web-release",
 ] }
 
 # Compile the web-viewer wasm in release mode.
 #
 # This installs the `wasm32-unknown-unknown` rust target if it's not already installed.
 # (this looks heavy but takes typically below 0.1s!)
-rerun-build-web-release = "rustup target add wasm32-unknown-unknown && cargo run -p re_dev_tools -- build-web-viewer --features analytics,grpc --release -g"
+rerun-build-web-release = "rustup target add wasm32-unknown-unknown && cargo run -p re_dev_tools -- build-web-viewer --no-default-features --features analytics,grpc,map_view --release -g"
```
Comment (emilk) [inline pixi.toml:200]: Isn't easier to keep the default features and just add on grpc?

**Review by emilk — APPROVED** [review]
Nice!

Btw, I wonder if we shouldn't make a `re_web_viewer` crate that just wraps `re_viewer`. `re_viewer` is weird in that it is both a library, and web app. Food for thought

**Review by emilk — APPROVED** [review]
Nice!

Btw, I wonder if we shouldn't make a `re_web_viewer` crate that just wraps `re_viewer`. `re_viewer` is weird in that it is both a library, and web app. Food for thought

File: rerun_js/web-viewer/build-wasm.mjs (hunk 1 above)
Comment (emilk) [reply rerun_js/web-viewer/build-wasm.mjs]: Makes sense 👍

File: rerun_js/web-viewer/build-wasm.mjs (hunk 2 above)
Comment (jprochazk) [reply rerun_js/web-viewer/build-wasm.mjs:35]: this is for the NPM package, we don't want users' applications which embed the web viewer this way to send analytics to us. they will only do that if they embed the web viewer as an iframe

File: pixi.toml (hunk 3 above)
Comment (jprochazk) [reply pixi.toml:200]: I wanted to be more explicit here, because you're not going to type the long command

**Comment by jprochazk** [comment]
> Btw, I wonder if we shouldn't make a re_web_viewer crate that just wraps re_viewer. re_viewer is weird in that it is both a library, and web app. Food for thought

https://github.com/rerun-io/rerun/issues/8297
