### PR TITLE
Codegen: Multi-pass refactoring & support for `--check`

### LINKED ISSUE #3495: Add a `--check` argument to `cargo codegen`
This should do a dry-run and return an error code if any of the files would be modified.

This would be a bit clearer and less error prone in the CI check:
https://github.com/rerun-io/rerun/blob/50222c2349cfaec64f795636d2398d26e6bf4738/.github/workflows/reusable_checks.yml#L138-L140

And would also be something that could be added to a git `pre-push` hook to reduce frequency of submitting code that's going to fail the codegen check.

### PR DESCRIPTION
**Pull request by teh-cmc**
- Adds a new `CodeFormatter` trait.
- Adds a new trait-based generic `generate_code` helper, and reimplement all language-specific backends in terms of it.
- Adds `--check` flag.
- Use `--check` instead of git dirtyness checks on CI.

---

- Fixes #3495 
- DNM: requires #3917 first

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested [demo.rerun.io](https://demo.rerun.io/pr/3918) (if applicable)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG

- [PR Build Summary](https://build.rerun.io/pr/3918)
- [Docs preview](https://rerun.io/preview/b02b166619ab1ede4cdcac149a42c392ca8f13a4/docs) 
- [Examples preview](https://rerun.io/preview/b02b166619ab1ede4cdcac149a42c392ca8f13a4/examples) 
- [Recent benchmark results](https://ref.rerun.io/dev/bench/)
- [Wasm size tracking](https://ref.rerun.io/dev/sizes/)

### CODE REVIEW

**Comment by teh-cmc** [comment]
And then succeeding as it should: https://github.com/rerun-io/rerun/actions/runs/6563258948/job/17827053364?pr=3918

File: crates/re_types_builder/src/bin/build_re_types.rs [hunk 1]
```diff
@@ -44,17 +44,17 @@ fn main() {
...
             "--help" => {
                 println!("Usage: [--help] [--force] [--profile]");
                 return;
             }
-            "--force" => {
-                always_run = true;
-            }
+            "--force" => always_run = true,
             "--profile" => profiler.start(),
+            "--check" => check = true,
```
Comment (jleibs) [inline crates/re_types_builder/src/bin/build_re_types.rs:57]: Check should imply force.

**Review by jleibs — APPROVED** [review]
