### PR TITLE
Fix selection highlighting in blueprint tree view

### LINKED ISSUE #2728: Fix "selected" state when hovering a blueprint item
This is what a selected Blueprint item looks like:

image

When hovered, the item changes to this:

image

It's a strange state, because it's not clear what is hovered vs selected.

👉 For now, I recommend changing the grey color in the hover state to blue, so that the entire elements looks selected, even when hovered.

### LINKED ISSUE #2828: Revert #2796 for the 0.8 release
#2796 needs to be reverted before releasing 0.8

### PR DESCRIPTION
**Pull request by abey79**
### What

Before:

image

After:

image

This PR also reverts #2796 (fixes #2828).

#### Changes
- Blue area is properly drawn
- Size of the hover/selection effect is fixed (after being broken in #2796)

Fixes #2728

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested [demo.rerun.io](https://demo.rerun.io/pr/2824) (if applicable)

- [PR Build Summary](https://build.rerun.io/pr/2824)
- [Docs preview](https://rerun.io/preview/pr%3Aantoine%2Fblueprint_tree_selection_2728/docs)
- [Examples preview](https://rerun.io/preview/pr%3Aantoine%2Fblueprint_tree_selection_2728/examples)

### CODE REVIEW

File: crates/re_viewport/src/viewport_blueprint_ui.rs [hunk 1]
```diff
@@ -459,13 +483,19 @@ fn blueprint_row_with_buttons(
 
     // The main button might have been highlighted because what it was referring
     // to was hovered somewhere else, and then we also want it highlighted here.
-    if button_hovered || main_button_response.highlighted() {
+    if button_hovered || main_button_response.highlighted() || selected {
```
Comment (Wumpf) [inline crates/re_viewport/src/viewport_blueprint_ui.rs:486]: is checking for `main_button_response.highlighted()` even necessary now that `selected` is passed in? I'd expect that any time `main_button_response.highlighted()` is true, `selected` is true as well.

File: crates/re_viewport/src/viewport_blueprint_ui.rs [hunk 2]
```diff
@@ -388,16 +405,23 @@ fn focus_tab(tree: &mut egui_tiles::Tree<SpaceViewId>, tab: &SpaceViewId) {
...
+    selected: bool,
     add_content: impl FnOnce(&mut egui::Ui) -> egui::Response,
     add_on_hover_buttons: impl FnOnce(&re_ui::ReUi, &mut egui::Ui),
 ) {
     let where_to_add_hover_rect = ui.painter().add(egui::Shape::Noop);
 
+    ui.visuals_mut().widgets.hovered.expansion = 2.0;
+    ui.visuals_mut().widgets.active.expansion = 2.0;
+    ui.visuals_mut().widgets.open.expansion = 2.0;
+    ui.visuals_mut().widgets.inactive.expansion = 2.0;
```
Comment (Wumpf) [inline crates/re_viewport/src/viewport_blueprint_ui.rs:423]: these visuals changes now leak into the caller which is generally a bad thing, they should be scoped to this method

In this case it should be enough to just move them insode the `with_layout` block (?). Otherwise, `ui.scope` is the way to go

**Review by Wumpf — APPROVED** [review]
great to have that fixed, was visually very annoying before!

Please check on the leaking `ui.visuals_mut()` before merging

**Review by martenbjork — APPROVED** [review]
This is great! Small change, but it makes the UI feel much more solid and predictable. 💯🚢

File: crates/re_viewport/src/viewport_blueprint_ui.rs (hunk 1 above)
Comment (abey79) [reply crates/re_viewport/src/viewport_blueprint_ui.rs:486]: Things can be highlighted without being selected by virtue of the corresponding entities being hovered over in the timeline/stream tree, so this check is indeed necessary.

File: crates/re_viewport/src/viewport_blueprint_ui.rs (hunk 2 above)
Comment (abey79) [reply crates/re_viewport/src/viewport_blueprint_ui.rs]: Removed altogether as per our discussion.

**Comment by abey79** [comment]
@martenbjork there is aspect to this PR that might be improved, it's the hover state of the "minus" and "eye" buttons when the item is selected:

image
(mouse pointer is missing from the screenshot, it was hovering over the `–` button)

Hover feedback here would be nice, but I'm unsure how to best implement it. Can you propose something? It'd be ideal to create a new issue as we would like to merge this as is (it's already much better than before) and ship in a 0.8 alpha release due very soon.

**Comment by martenbjork** [comment]
I agree, that `—` hover state needs some love. But I agree, let's ship this and follow up with the details. 🚢

I'm currently polishing all these details so we'll have a better design soon!

**Review by Wumpf — APPROVED** [review]
