### PR TITLE
Fix expecting always Rgba8Unorm backbuffer on Web & Bgra8Unorm on native

### LINKED ISSUE #1353: egui-wgpu crash for Rgba8Unorm backbuffers
Full crash log:
https://pastebin.com/LzZA3NGz

Looks like something in egui-wgpu is hardcoding `Bgra8Unorm` instead of checking on the surface format. Haven't checked yet but seems pretty straight forward.

### PR DESCRIPTION
**Pull request by Wumpf**
Fixes #1353 which was *not*  egui-wgpu bug after all but a straight forward issue in our code.

Tested re_renderer example and viewer on web & native, worked for me as before.
Not yet confirmed on a setup that crashed before, but I'm very confident this is fixed

### Checklist
* [x] I have read and agree to [Contributor Guide](../CONTRIBUTING.md) and the [Code of Conduct](../CODE_OF_CONDUCT.md)
* [ ] I've included a screenshot or gif (if applicable)
* [ ] I've added a line to `CHANGELOG.md` (if this is a big enough change to warrant it)

### CODE REVIEW

File: crates/re_renderer/examples/framework.rs [hunk 1]
```diff
@@ -124,12 +124,17 @@ impl<E: Example + 'static> Application<E> {
...
+        let formats = surface.get_capabilities(&adapter).formats;
+        let mut swapchain_format = formats[0]; // Default to first format.
+        for format in formats {
+            if matches!(
+                format,
+                wgpu::TextureFormat::Rgba8Unorm | wgpu::TextureFormat::Bgra8Unorm
+            ) {
+                swapchain_format = format;
+            }
+        }
```
Comment (emilk) [inline crates/re_renderer/examples/framework.rs:137]:
```suggestion
        let formats = surface.get_capabilities(&adapter).formats;
        let swapchain_format = egui_wgpu::preferred_framebuffer_format(&formats);
```

**Review by emilk — CHANGES_REQUESTED** [review]

File: crates/re_renderer/examples/framework.rs (hunk 1 above)
Comment (Wumpf) [reply crates/re_renderer/examples/framework.rs:137]: that's re_renderer samples, we don't have egui there

Comment (emilk) [reply crates/re_renderer/examples/framework.rs:137]: oh right. Well, copy-paste the function and reuse it that way? This function doesn't need more code in it imho

**Review by emilk — APPROVED** [review]

File: crates/re_renderer/examples/framework.rs (hunk 1 above)
Comment (Wumpf) [reply crates/re_renderer/examples/framework.rs:137]: ok!
