### PR TITLE
Fix no default colors showing for class ids when there's no annotation context

### LINKED ISSUE #3425: No default AnnotationContext in prerelease
**Describe the annoyance**
Not sure if this was changed on purpose, but in the prerelease, there will be no colors when logging `SegmentationImage` except `AnnotationContext` is also logged. Previously default colors would be shown. 

Similar issue when logging points with class_ids (all have the same pink color). I suspect other archetypes will have similar issues.

**To Reproduce**
```python
import rerun as rr
import rerun.experimental as rr2
import numpy as np

rr.init("test annotation context", spawn=True)
rr2.log("/", rr2.AnnotationContext([(1, "red", (255, 0, 0)), (2, "green", (0, 255, 0))]))
rr2.log("image", rr2.Image(np.random.rand(100,100,3) * 0.2))
rr2.log("image/segmentation", rr2.SegmentationImage(np.random.randint(0,10, size=(100,100))))
```
With and without the `AnnotationContext` line.

**Expected behavior**
I'd say having matching default colors (for matching class_ids) is better.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Additional context**
```
rerun_py 0.9.0-alpha.4 [rustc 1.72.1 (d5c2e9c34 2023-09-13), LLVM 16.0.5] x86_64-unknown-linux-gnu 2e9df4c, built 2023-09-23T09:59:35Z
```

### PR DESCRIPTION
**Pull request by Wumpf**
### What

* Fixes #3425

It seems during refactor in #2910 we lost class_id during `ResolvedClassDescription`->`ResolvedAnnotationInfo`

image

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested [demo.rerun.io](https://demo.rerun.io/pr/3451) (if applicable)

- [PR Build Summary](https://build.rerun.io/pr/3451)
- [Docs preview](https://rerun.io/preview/6c4cdf6b13f075161145a772212c154d456fdee1/docs) 
- [Examples preview](https://rerun.io/preview/6c4cdf6b13f075161145a772212c154d456fdee1/examples) 
- [Recent benchmark results](https://ref.rerun.io/dev/bench/)
- [Wasm size tracking](https://ref.rerun.io/dev/sizes/)

### CODE REVIEW

File: crates/re_viewer_context/src/annotations.rs [hunk 1]
```diff
@@ -94,7 +94,7 @@ impl<'a> ResolvedClassDescription<'a> {
     #[inline]
     pub fn annotation_info(&self) -> ResolvedAnnotationInfo {
         ResolvedAnnotationInfo {
-            class_id: self.class_description.map(|desc| desc.info.id.into()),
+            class_id: self.class_id,
```
Comment (jleibs) [inline crates/re_viewer_context/src/annotations.rs:97]: I suspect there are cases we want this to be something like?
```
self.class_id.or_else(||, self.class_description.map(|desc| desc.info.id.into()))
```

Comment (Wumpf) [reply crates/re_viewer_context/src/annotations.rs:97]: I think if we have no class_id but were able to resolve to a class_description something went wrong, no?

Comment (jleibs) [reply crates/re_viewer_context/src/annotations.rs:97]: You're right -- read through the code -- class_description should only be set if class_id is non-None, and the reverse should never be true.

**Review by jleibs — APPROVED** [review]

File: crates/re_viewer_context/src/annotations.rs (hunk 1 above)
Comment (Wumpf) [reply crates/re_viewer_context/src/annotations.rs:97]: let's try to keep this in mind on a future refactor
