### PR TITLE
Make pinhole.hpp robust against min/max preprocessor macros (typically from windows.h)

### LINKED ISSUE #5414: pinhole.hpp compiler error with std::max
**Describe the bug**
Compiler error pointing to std::max function in [pinhole.hpp](https://github.com/rerun-io/rerun/blob/0.14.1/rerun_cpp/src/rerun/archetypes/pinhole.hpp#L156)
```
const float focal_length_y = 0.5f / std::tan(std::max(fov_y * 0.5f, EPSILON));
```
Compiler errors:
```
[build] XXX\rerun\archetypes/pinhole.hpp(156,63): error C2589: '(': illegal token on right side of '::' (compiling source file YYY.cpp) [ZZZ.vcxproj]
[build] XXX\rerun\archetypes/pinhole.hpp(156): error C2144: syntax error: 'unknown-type' should be preceded by ')' (compiling source file YYY.cpp) [ZZZ.vcxproj]
[build] XXX\rerun\archetypes/pinhole.hpp(156,1): error C2661: 'tan': no overloaded function takes 0 arguments (compiling source file YYY.cpp) [ZZZ.vcxproj]
[build] XXX\rerun\archetypes/pinhole.hpp(156,25): error C2737: 'focal_length_y': const object must be initialized (compiling source file YYY.cpp) [ZZZ.vcxproj]
[build] XXX\rerun\archetypes/pinhole.hpp(156): error C2144: syntax error: 'unknown-type' should be preceded by ';' (compiling source file YYY.cpp) [ZZZ.vcxproj]
[build] XXX\rerun\archetypes/pinhole.hpp(156,63): error C2143: syntax error: missing ')' before '*' (compiling source file YYY.cpp) [ZZZ.vcxproj]
[build] XXX\rerun\archetypes/pinhole.hpp(156,63): error C2143: syntax error: missing ';' before '*' (compiling source file YYY.cpp) [ZZZ.vcxproj]
[build] XXX\rerun\archetypes/pinhole.hpp(156,1): error C2082: redefinition of formal parameter 'fov_y' (compiling source file YYY.cpp) [ZZZ.vcxproj]
[build] XXX\rerun\archetypes/pinhole.hpp(156,1): error C2059: syntax error: ')' (compiling source file YYY.cpp) [ZZZ.vcxproj]
[build] XXX\rerun\archetypes/pinhole.hpp(156,63): error C2100: illegal indirection (compiling source file YYY.cpp) [ZZZ.vcxproj]
[build] Build finished with exit code 1
```

**To Reproduce**
1. Compile C++ project linking Rerun

**Expected behavior**
No compiler errors

**Desktop (please complete the following information):**
 - OS: Windows, VS 2019

**Rerun version**
0.14.1

**Additional context**
Workaround is manually patch this line by adding braces:
```
const float focal_length_y = 0.5f / std::tan((std::max)(fov_y * 0.5f, EPSILON));
```

### PR DESCRIPTION
**Pull request by Wumpf**
### What

And add a test to ensure we don't run into this again!

* Fixes #5414

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using newly built examples: [app.rerun.io](https://app.rerun.io/pr/5432/index.html)
  * Using examples from latest `main` build: [app.rerun.io](https://app.rerun.io/pr/5432/index.html?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [app.rerun.io](https://app.rerun.io/pr/5432/index.html?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!

- [PR Build Summary](https://build.rerun.io/pr/5432)
- [Docs preview](https://rerun.io/preview/13b23da339babe01018016fb651da7d8f02e549c/docs) 
- [Examples preview](https://rerun.io/preview/13b23da339babe01018016fb651da7d8f02e549c/examples) 
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

### CODE REVIEW

File: rerun_cpp/tests/windows_min_max_robustness.cpp [hunk 1]
```diff
@@ -0,0 +1,10 @@
+
+// `<windows.h>` by default defined min and max as macros, which can cause issues with std::min and std::max.
+// This can be easily turned off by the user with `#define NOMINMAX` before including `<windows.h>`.
+// However, users might not know about this or forget about it and we want to be robust against it.
+//
+// This test checks that rerun.h is robust against this issue by explicitly setting `min`/`max` macros and including rerun.hpp.
+#define min(a, b) (this does not compile)
+#define max(a, b) (this does not compile)
```
Comment (abey79) [inline rerun_cpp/tests/windows_min_max_robustness.cpp:8]: nice!

**Review by abey79 — APPROVED** [review]
Thanks, I hate this :)
