### PR TITLE
GC improvements 1: fix timeless tables not being `RowId`-ordered

### LINKED ISSUE #1807: datastore: timeless ordering should be `RowId`-based
With the new GC landing in #1801, garbage collection is now deterministic and based on `RowId` order, i.e. the clients' wall-clocks.
But our timeless tables are still using insertion order, which is both inconsistent and meaningless.

Our timeless tables should be sorted based on `RowId`s too.

### PR DESCRIPTION
**Pull request by teh-cmc**
Fixes a long-standing bug: timeless tables not being sorted by `RowId`, which means they effectively always return incorrect results for out-of-order data (yes, that is a thing even in a timeless context).

This _worsens_  GC performance for timeless tables, but:
1. The performance of incorrect code hardly matters to begin with, and
2. this is ground work for turning timeless tables in ringbuffers in an upcoming PR, which will massively improve performance. 

- Fixes #1807 

### Benchmarks

Hint: it's even worse!

```
group                                                     gc_improvements_0                       gc_improvements_1
-----                                                     -----------------                       -----------------
.../plotting_dashboard/drop_at_least=0.3/bucketsz=1024    1.00   1084.0±4.47ms 54.1 KElem/sec     1.03   1117.2±9.07ms 52.4 KElem/sec
.../plotting_dashboard/drop_at_least=0.3/bucketsz=2048    1.00       2.1±0.02s 27.6 KElem/sec     1.01       2.1±0.01s 27.3 KElem/sec
.../plotting_dashboard/drop_at_least=0.3/bucketsz=256     1.00    465.8±2.50ms 125.8 KElem/sec    1.01    471.5±4.76ms 124.3 KElem/sec
.../plotting_dashboard/drop_at_least=0.3/bucketsz=512     1.00    655.3±2.61ms 89.4 KElem/sec     1.02    666.7±6.64ms 87.9 KElem/sec
.../plotting_dashboard/drop_at_least=0.3/default          1.00    652.8±4.12ms 89.8 KElem/sec     1.02    665.6±4.67ms 88.0 KElem/sec
.../timeless_logs/drop_at_least=0.3/bucketsz=1024         1.00       2.4±0.05s 24.2 KElem/sec     3.35       8.1±0.10s  7.2 KElem/sec
.../timeless_logs/drop_at_least=0.3/bucketsz=2048         1.00       2.4±0.03s 24.1 KElem/sec     3.30       8.0±0.09s  7.3 KElem/sec
.../timeless_logs/drop_at_least=0.3/bucketsz=256          1.00       2.5±0.08s 23.5 KElem/sec     3.23       8.1±0.11s  7.3 KElem/sec
.../timeless_logs/drop_at_least=0.3/bucketsz=512          1.00       2.4±0.02s 24.5 KElem/sec     3.38       8.1±0.11s  7.3 KElem/sec
.../timeless_logs/drop_at_least=0.3/default               1.00       2.4±0.03s 24.4 KElem/sec     3.35       8.1±0.07s  7.3 KElem/sec

```

---

Part of the GC improvements series:
- #4394
- #4395
- #4396
- #4397
- #4398
- #4399
- #4400
- #4401

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested [app.rerun.io](https://app.rerun.io/pr/4394) (if applicable)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG

- [PR Build Summary](https://build.rerun.io/pr/4394)
- [Docs preview](https://rerun.io/preview/3a163cddcfe9cd6e5067cf9ed94e96b6defb0a3f/docs) 
- [Examples preview](https://rerun.io/preview/3a163cddcfe9cd6e5067cf9ed94e96b6defb0a3f/examples) 
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

### CODE REVIEW

File: crates/re_arrow_store/tests/correctness.rs [hunk 1]
```diff
@@ -147,6 +147,46 @@ fn row_id_ordering_semantics() -> anyhow::Result<()> {
         }
     }
 
+    // Timeless is RowId-ordered too!
+    //
+    // * Insert timeless `point1` with a random `RowId`.
+    // * Insert timeless `point2` using `point1`'s `RowId`, decremented by one.
+    // * Query timelessly and make sure we get `point1` because of timeless tie-breaks.
```
Comment (Wumpf) [inline crates/re_arrow_store/tests/correctness.rs:154]: overviews like that a very appreciated :)

File: crates/re_arrow_store/src/store_stats.rs [hunk 2]
```diff
@@ -429,17 +422,22 @@ impl SizeBytes for PersistentIndexedTable {
...
+            is_sorted,
+        } = &*inner.read();
 
         ent_path.total_size_bytes()
             + cluster_key.total_size_bytes()
             + col_insert_id.total_size_bytes()
             + col_row_id.total_size_bytes()
             + col_num_instances.total_size_bytes()
             + columns.total_size_bytes()
+            + is_sorted.total_size_bytes()
```
Comment (Wumpf) [inline crates/re_arrow_store/src/store_stats.rs:441]: offtopic, but this way of counting the size of a struct (and what it points to) isn't all that accurate since padding between fields can play a big role :/. Not that it matters all that much in the big picture here

**Review by Wumpf — APPROVED** [review]
looking great!

File: crates/re_arrow_store/src/store_stats.rs (hunk 2 above)
Comment (teh-cmc) [reply crates/re_arrow_store/src/store_stats.rs:441]: Yep, the stats are not meant to be perfectly accurate, they just need to be "good enough" and more importantly _consistent_: since the GC works with percentages rather than raw numbers, as long as things are consistent it works out okay.

By far our biggest problem at the moment is the size of serialized arrow data, which is both wrong and inconsistent in many ways lol.

Quoting the docs:
```rust
/// The size of both the control & component data stored in this bucket, heap and stack
/// included, in bytes.
///
/// This is a best-effort approximation, adequate for most purposes (stats,
/// triggering GCs, …).
```
