### PR TITLE
Fix (log only) error on quickly resizing the viewer

### LINKED ISSUE #4455: Error when quickly resizing viewer with 3D view
**Describe the bug**
When resizing the viewer for a little while it eventually crashes with the following error
```
2023-12-07T10:44:52Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default

thread 'ThreadId(1)' panicked at 'wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `encoder`
    In a set_viewport command
    Viewport has invalid rect Rect { x: 224.0, y: 72.0, w: 932.0, h: 496.0 }; origin and/or size is less than or equal to 0, and/or is not contained in the render target Extent3d { width: 1055, height: 631, depth_or_array_layers: 1 }
```

https://github.com/rerun-io/rerun/assets/9785832/abb552f4-5d24-4d28-afc9-96fb777ef322

**To Reproduce**
Open the viewer and continuously resize for a few seconds. I think what matters is that it is fast (I guess too fast for my computer to handle something, wouldn't be surprised if this is harder to reproduce on better hardware or different OS). This is the code I use here, but I don't think it matters:
```
import numpy as np
import rerun as rr

rr.init("collapsing", spawn=True)
rr.log("parent/p1", rr.Points3D(np.random.rand(10,3)))
rr.log("parent/p2", rr.Points3D(np.random.rand(10,3)))
rr.log("parent/p3", rr.Points3D(np.random.rand(10,3)))
rr.log("parent/p4", rr.Points3D(np.random.rand(10,3)))
rr.log("parent/p5", rr.Points3D(np.random.rand(10,3)))
rr.log("parent/p6", rr.Points3D(np.random.rand(10,3)))

```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Rerun version**
```
rerun_py 0.12.0-alpha.1+dev [rustc 1.74.0 (79e9716c9 2023-11-13), LLVM 17.0.4] x86_64-unknown-linux-gnu
```

### PR DESCRIPTION
**Pull request by Wumpf**
### What

* Fixes #4455

Got a good repro of this on my windows machine by using the screenshot action on a low-dpi screen (screenshot action will do a quick resize on native) while having the pose tracking example open.

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using newly built examples: [app.rerun.io](https://app.rerun.io/pr/5189/index.html)
  * Using examples from latest `main` build: [app.rerun.io](https://app.rerun.io/pr/5189/index.html?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [app.rerun.io](https://app.rerun.io/pr/5189/index.html?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!

- [PR Build Summary](https://build.rerun.io/pr/5189)
- [Docs preview](https://rerun.io/preview/f54be52f2819874bcec35e91db189eb369a007af/docs) 
- [Examples preview](https://rerun.io/preview/f54be52f2819874bcec35e91db189eb369a007af/examples) 
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

### CODE REVIEW

File: crates/re_viewer_context/src/gpu_bridge/re_renderer_callback.rs [hunk 1]
```diff
@@ -78,7 +78,7 @@ impl egui_wgpu::CallbackTrait for ReRendererCallback {
 
     fn paint<'a>(
         &'a self,
-        info: egui::PaintCallbackInfo,
+        _info: egui::PaintCallbackInfo,
```
Comment (emilk) [inline crates/re_viewer_context/src/gpu_bridge/re_renderer_callback.rs:81]: So the viewport coming from egui was somehow wrong?
Is this a bug in an egui crate?

Comment (Wumpf) [reply crates/re_viewer_context/src/gpu_bridge/re_renderer_callback.rs:81]: we only passed on the viewport offset from egui, not the viewport size. We then assumed the size was what we had previously on the viewbuilder.
... which come to think means that the viewbuilder got an outdated size! This is concerning but I reckon this can easily happen though when new sizes come in asynchronously; to nail this down perfectly we'd need to know when egui queries the size that leads to the final renderpass.
This PR instead just trusts egui with the viewport setting, after all egui also set up the renderpass and knows what a valid viewport is for that renderpass.

**Review by emilk — APPROVED** [review]
