### PR TITLE
Limit the size of component tooltips with `UiVerbosity::Reduced`

### LINKED ISSUE #3154: The hover previews on events in the Streams View flicker and block
See video

https://github.com/rerun-io/rerun/assets/2624717/50c276c9-d783-4478-a2f8-a1b78ac56e0f

As you hover events in the streams view, the preview data UI flickers in and out and covers way too much of the UI. THe effect is quite jarring

How to reproduce:
```bash
pip install --pre -f https://build.rerun.io/commit/d7de7f9/wheels --upgrade rerun-sdk.  # Latest build as of Aug 30th 09.20 CET
python -m rerun_demo
```

### PR DESCRIPTION
**Pull request by abey79**
### What

Limit the size of component tooltips with `UiVerbosity::Reduced`

Fixes #3154

image

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested [demo.rerun.io](https://demo.rerun.io/pr/3171) (if applicable)

- [PR Build Summary](https://build.rerun.io/pr/3171)
- [Docs preview](https://rerun.io/preview/35244cb0963af9643740613271415a8b7d4f4475/docs) 
- [Examples preview](https://rerun.io/preview/35244cb0963af9643740613271415a8b7d4f4475/examples) 
- [Recent benchmark results](https://ref.rerun.io/dev/bench/)
- [Wasm size tracking](https://ref.rerun.io/dev/sizes/)

### CODE REVIEW

**Comment by nikolausWest** [comment]
Regarding screenshot: shy is the tooltip so wide?

**Comment by abey79** [comment]
@nikolausWest I rushed that before leaving earlier and didn't even realise 🤦🏻  Anyways, I found the culprit.

@emilk requesting a review from you as I'm wondering if there was a reason for that autoshrink not to be set to true in the first place. (I couldn't find one by playing around with the UI.)

**Comment by emilk** [comment]
> @emilk requesting a review from you as I'm wondering if there was a reason for that autoshrink not to be set to true in the first place. (I couldn't find one by playing around with the UI.)

I can't see any. Maybe a copy-paste bug :T

File: crates/re_data_ui/src/component.rs [hunk 1]
```diff
@@ -85,8 +93,20 @@ impl DataUi for EntityComponentWithInstances {
...
                     re_ui::ReUi::setup_table_body(&mut body);
                     let row_height = re_ui::ReUi::table_line_height();
-                    body.rows(row_height, num_instances, |index, mut row| {
-                        if let Some(instance_key) = instance_keys.get(index) {
+                    body.rows(row_height, max_row, |index, mut row| {
+                        if index == max_row - 1 && num_instances > max_row {
+                            // last row, suggest that there is more.
+                            row.col(|ui| {
+                                ui.label(format!(
+                                    "{} more…",
```
Comment (emilk) [inline crates/re_data_ui/src/component.rs:101]: I think this will look better, but maybe not.

```suggestion
                                    "… and {} more.",
```

btw, nice use of `format_large_number`! It's easy to forget to use that one, so nice that you didn't :)

File: crates/re_data_ui/src/component.rs [hunk 2]
```diff
@@ -85,8 +93,20 @@ impl DataUi for EntityComponentWithInstances {
                 .body(|mut body| {
                     re_ui::ReUi::setup_table_body(&mut body);
                     let row_height = re_ui::ReUi::table_line_height();
-                    body.rows(row_height, num_instances, |index, mut row| {
-                        if let Some(instance_key) = instance_keys.get(index) {
+                    body.rows(row_height, max_row, |index, mut row| {
+                        if index == max_row - 1 && num_instances > max_row {
+                            // last row, suggest that there is more.
+                            row.col(|ui| {
+                                ui.label(format!(
```
Comment (emilk) [inline crates/re_data_ui/src/component.rs:100]: I think it would make more sense to put this label _after_ the table body. Right now the label expands the width of the first column, but this label shouldn't need to.

Also it leads to convoluted logic where you need to use `4` to mean "at most 3 elements", which threw me off quite a bit when reading the code.

File: crates/re_data_ui/src/component.rs (hunk 1 above)
Comment (abey79) [reply crates/re_data_ui/src/component.rs:101]: TIL 🤣

Not only I would have *totally* forgotten that, but I didn't even realise that Copilot added it for me! (In fairness, I was in a bit of a rush then.)

File: crates/re_data_ui/src/component.rs (hunk 2 above)
Comment (abey79) [reply crates/re_data_ui/src/component.rs]: Moving that out of the table makes total.

TBH, in the strict "max_row" sense that encompasses the "...x more" line (which I aimed for), the behaviour is intrinsically convoluted. For eg. max_row = 5, if you have 5 items you display all five, but if you have 6 you only display 4 and "...2 more".

I opted to stick to that (somewhat uptight) max_row definition but made the code much more clear.

File: crates/re_data_ui/src/component.rs (hunk 1 above)
Comment (abey79) [reply crates/re_data_ui/src/component.rs]: I like your version more, but without the space after the `…`. (Couldn't find any indications online that there ever should be one.)

File: crates/re_data_ui/src/component.rs [hunk 3]
```diff
@@ -44,6 +45,20 @@ impl DataUi for EntityComponentWithInstances {
...
+            UiVerbosity::Reduced => num_instances.at_most(4), // includes "…x more" if any
+            UiVerbosity::All => num_instances,
+        };
+
+        let displayed_row = if num_instances <= max_row {
+            num_instances
+        } else {
+            // this accounts for the "…x more" using a row
+            max_row - 1
+        };
```
Comment (emilk) [inline crates/re_data_ui/src/component.rs:60]: I think we can simplify this a lot:

```suggestion
        let num_rows_to_show = match verbosity {
            UiVerbosity::Small => 0,
            UiVerbosity::Reduced => num_instances.at_most(3),
            UiVerbosity::All => num_instances,
        };
```

File: crates/re_data_ui/src/component.rs [hunk 4]
```diff
@@ -112,6 +127,12 @@ impl DataUi for EntityComponentWithInstances {
                         }
                     });
                 });
+            if num_instances > displayed_row {
+                ui.label(format!(
+                    "…and {} more.",
+                    re_format::format_large_number((num_instances - displayed_row) as _)
+                ));
+            }
```
Comment (emilk) [inline crates/re_data_ui/src/component.rs:135]:
```suggestion
            if num_rows_to_show  < num_instances {
                ui.label(format!(
                    "…and {} more.",
                    re_format::format_large_number((num_instances - num_rows_to_show) as _)
                ));
            }
```

File: crates/re_data_ui/src/component.rs (hunk 3 above)
Comment (abey79) [reply crates/re_data_ui/src/component.rs:60]: My behaviour (4 rows is strictly respected):

| 3 | 4 | 5 | 6 |
|--------|--------|--------|--------|
| x | x | x | x |
| x | x | x | x |
| x | x | x | x |
| | x | ...+2 | ...+3 |

Your behaviour (4  rows is *not* respected and the "...1 more" feels weird as you might as well put the corresponding item there):
| 3 | 4 | 5 | 6 |
|--------|--------|--------|--------|
| x | x | x | x |
| x | x | x | x |
| x | x | x | x |
| | x | x | x |
| |  | ...+1 | ...+2 |

The key difference is the `max_row - 1` in my code.

**Review by martenbjork — APPROVED** [review]
Looks good!

File: crates/re_data_ui/src/component.rs (hunk 3 above)
Comment (abey79) [reply crates/re_data_ui/src/component.rs]: As discussed, I updated the docs.

And luckily I just experienced the panic-inducing case of `max_row = 0` (=> `max_row - 1` panics) and fixed it.
