### PR TITLE
Dataframe v2: big ol' hindsight-driven refactoring

### LINKED ISSUE #7681: `filter_is_not_null` / `filtered_point_of_view` returns incorrect results
- Surfaced this issue while working on: https://github.com/rerun-io/rerun/pull/7680

Position3D is not in the result set even though it should be.

Can be reproduced on top of https://github.com/rerun-io/rerun/pull/7680

Simple repro in python:
```python
import rerun as rr
import tempfile


rr.init("rerun_example_test_recording")

rr.set_time_sequence("my_index", 1)
rr.log("points", rr.Points3D([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))
rr.set_time_sequence("my_index", 7)
rr.log("points", rr.Points3D([[10, 11, 12]], colors=[[255, 0, 0]]))

with tempfile.TemporaryDirectory() as tmpdir:
    rrd = tmpdir + "/tmp.rrd"

    rr.save(rrd)

    recording = rr.dataframe.load_recording(rrd)

color_col = rr.dataframe.ComponentColumnSelector("points", rr.components.Color)

view = recording.view(index="my_index", contents="points")

# Baseline
table = view.select().read_all()
print(80 * "=")
print(table)
print(80 * "=")

# my_index, log_time, log_tick, points, colors
assert table.num_columns == 5
assert table.num_rows == 2

assert table.column("my_index").combine_chunks()[1].as_py() == 7

assert table.column("/points:Color").combine_chunks()[1][0].as_py() == 4278190335
assert table.column("/points:Position3D").combine_chunks()[1][0].as_py() == [10, 11, 12]

# Filtered to Color is not null
table = view.filter_is_not_null(color_col).select().read_all()
print(80 * "=")
print(table)
print(80 * "=")

# my_index, log_time, log_tick, points, colors
assert table.num_columns == 5
assert table.num_rows == 1

assert table.column("my_index").combine_chunks()[0].as_py() == 7

assert table.column("/points:Color").combine_chunks()[0][0].as_py() == 4278190335
assert table.column("/points:Position3D").combine_chunks()[0][0].as_py() == [10, 11, 12]

```

Output:
```
================================================================================
pyarrow.Table
log_tick: int64
log_time: timestamp[ns]
my_index: int64
/points:Color: list<item: uint32>
  child 0, item: uint32
/points:Position3D: list<item: fixed_size_list<item: float not null>[3]>
  child 0, item: fixed_size_list<item: float not null>[3]
      child 0, item: float not null
----
log_tick: [[1]]
log_time: [[2024-10-10 16:22:00.557968899]]
my_index: [[7]]
/points:Color: [[[4278190335]]]
/points:Position3D: [[null]]
================================================================================
Traceback (most recent call last):
  File "/home/jleibs/rerun/repro.py", line 50, in <module>
    assert table.column("/points:Position3D").combine_chunks()[0][0].as_py() == [10, 11, 12]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "pyarrow/scalar.pxi", line 691, in pyarrow.lib.ListScalar.__getitem__
TypeError: 'NoneType' object is not subscriptable
```

### PR DESCRIPTION
**Pull request by teh-cmc**
Simpler. Faster. Correct-er.

* Fixes #7681
* DNM: requires #7677

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using examples from latest `main` build: [rerun.io/viewer](https://rerun.io/viewer/pr/7683?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [rerun.io/viewer](https://rerun.io/viewer/pr/7683?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!
* [x] If have noted any breaking changes to the log API in `CHANGELOG.md` and the migration guide

- [PR Build Summary](https://build.rerun.io/pr/7683)
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

File: crates/store/re_dataframe/src/query.rs [hunk 1]
```diff
@@ -1683,10 +1557,10 @@ mod tests {
                 "\
                 [
                     Int64[30, 40, 50, 70],
-                    Timestamp(Nanosecond, None)[None, None, None, None],
+                    Timestamp(Nanosecond, None)[None, None, 1970-01-01 00:00:00.000000050, 1970-01-01 00:00:00.000000070],
                     ListArray[[2], [3], [4], [6]],
                     ListArray[None, None, None, None],
-                    ListArray[None, None, None, None],
+                    ListArray[[{x: 2, y: 2}], [{x: 3, y: 3}], [{x: 4, y: 4}], [{x: 8, y: 8}]],
```
Comment (teh-cmc) [inline crates/store/re_dataframe/src/query.rs:1563]: Yup, the `expected` value was wrong :unamused:

**Review by jleibs — APPROVED** [review]
This is so much easier to follow!
