### PR TITLE
Strongly-typed analytics

### LINKED ISSUE #3269: Strongly-typed analytics events
Right now we construct events ad-hoc in code, and properties are mostly undocumented. We should instead just have a proper struct/enum with a single `into_event` method for each event.

We need to be careful about keeping these types clear of any extra noise that a non-Rust user would not be interested in. For example, no `derive` on the types if we can help it, and any `impl` blocks should be in a separate file.

### LINKED ISSUE #3271: Make anonymous analytics events and properties easier to review
Currently `rerun/crates/re_viewer/src/viewer_analytics.rs` contains all definitions of properties and events sent to analytics (with references to any exceptions). That's a great start but you still need to read a bunch of Rust code to understand what these properties and events actually mean.

For our analytics to be as useful (to Rerun) and transparent (to users) it should be easier to understand what events and properties are collected and what they mean. It's currently OK to figure out what is sent, but very hard to figure out what it actually means.

Suggestion:
- All events and properties are defined in central enums where each event and possible property value is documented
- These enums are defined in a single file
- Documentation about analytics points to that file or renders it's content

### PR DESCRIPTION
**Pull request by jprochazk**
### What

- Closes #3269 
- Closes #3271 

We want analytics to be easier to grok at a glance, both for our own and our users' sake. Events and their properties should be defined in plain structs with as little other boilerplate around them as possible. Anyone who's ever read a statically-typed language with a `struct`-like concept should be able to understand them.

This will also make it easier for us to track our own analytics events. What kinds are there, and what properties do they have, all defined in one place. The only exception is the events we send on our website.

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using newly built examples: [app.rerun.io](https://app.rerun.io/pr/5267/index.html)
  * Using examples from latest `main` build: [app.rerun.io](https://app.rerun.io/pr/5267/index.html?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [app.rerun.io](https://app.rerun.io/pr/5267/index.html?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!

- [PR Build Summary](https://build.rerun.io/pr/5267)
- [Docs preview](https://rerun.io/preview/f3a810f071726578b8b9846cd8aaa7805cfeeac3/docs) 
- [Examples preview](https://rerun.io/preview/f3a810f071726578b8b9846cd8aaa7805cfeeac3/examples) 
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

### CODE REVIEW

File: crates/re_analytics/src/event.rs [hunk 1]
```diff
@@ -1,88 +1,232 @@
-use crate::{Event, Property};
+// This file is linked to in a number of places, do not move/rename it without updating all the links!
+
+//! All analytics events collected by the Rerun viewer are defined in this file.
+//!
+//! Analytics can be completely disabled with `rerun analytics disable`,
+//! or by compiling rerun without the `analytics` feature flag.
```
Comment (emilk) [inline crates/re_analytics/src/event.rs:6]:
```suggestion
//! or by compiling rerun without the `analytics` feature flag.
//!
//! All collected analytics data is anonymized, stripping all personal identifiable information
//! as well as information about user data.
//! Read more about our analytics policy at <https://github.com/rerun-io/rerun/tree/main/crates/re_analytics>.
```

File: crates/re_analytics/src/event.rs [hunk 2]
```diff
@@ -1,88 +1,232 @@
...
+            opt_in_metadata,
+        } = self;
+
+        build_info.serialize(event);
+        event.insert_opt("rust_version", rust_version.clone());
+        event.insert_opt("llvm_version", llvm_version.clone());
+        event.insert_opt("python_version", python_version.clone());
+        for (name, value) in opt_in_metadata {
+            event.insert(name.clone(), value.clone());
+        }
```
Comment (emilk) [inline crates/re_analytics/src/event.rs:158]: we can avoid a lot of clones if we change `serialize` to consume `self`.
That's how it is used anyway: an event is discarded after it has been serialized.

```suggestion
    fn serialize(self, event: &mut AnalyticsEvent) {
        let Self {
            build_info,
            rust_version,
            llvm_version,
            python_version,
            opt_in_metadata,
        } = self;

        build_info.serialize(event);
        event.insert_opt("rust_version", rust_version);
        event.insert_opt("llvm_version", llvm_version);
        event.insert_opt("python_version", python_version);
        for (name, value) in opt_in_metadata {
            event.insert(name, value);
        }
```

File: crates/re_analytics/src/lib.rs [hunk 3]
```diff
@@ -331,3 +316,45 @@ impl Analytics {
...
+/// Trait representing the properties of an analytics event.
+///
+/// This is separate from [`Event`] to facilitate code re-use.
+///
+/// For example, [`re_build_info::BuildInfo`] has an implementation of this trait,
+/// so that any event which wants to include build info in its properties
+/// may include that struct in its own definition, and then call `build_info.serialize`
+/// in its own `serialize` implementation.
+pub trait Properties {
+    fn serialize(&self, event: &mut AnalyticsEvent) {
```
Comment (emilk) [inline crates/re_analytics/src/lib.rs:344]:
```suggestion
    fn serialize(self, event: &mut AnalyticsEvent) {
```

File: crates/re_analytics/src/lib.rs [hunk 4]
```diff
@@ -54,76 +59,51 @@ pub enum EventKind {
...
 
-    pub fn update(name: impl Into<Cow<'static, str>>) -> Self {
-        Self {
-            time_utc: OffsetDateTime::now_utc(),
-            kind: EventKind::Update,
-            name: name.into(),
-            props: Default::default(),
-        }
+    #[inline]
+    pub fn append(name: impl Into<Cow<'static, str>>) -> Self {
```
Comment (emilk) [inline crates/re_analytics/src/lib.rs:84]: It would be nice with a docstring explaining what `append` is for, and how it compares to `insert`

File: crates/re_analytics/src/lib.rs [hunk 5]
```diff
@@ -54,76 +59,51 @@ pub enum EventKind {
...
-        self.with_prop("rerun_version", version.to_string())
-            .with_prop("rust_version", (*rustc_version).to_owned())
-            .with_prop("llvm_version", (*llvm_version).to_owned())
-            .with_prop("target", *target_triple)
-            .with_prop("git_hash", build_info.git_hash_or_tag())
-            .with_prop("build_date", *datetime)
-            .with_prop("debug", cfg!(debug_assertions)) // debug-build?
-            .with_prop("rerun_workspace", *is_in_rerun_workspace)
+    #[inline]
+    pub fn insert(&mut self, name: impl Into<Cow<'static, str>>, value: impl Into<Property>) {
```
Comment (emilk) [inline crates/re_analytics/src/lib.rs:94]: please add a docstring

File: crates/re_analytics/src/lib.rs [hunk 6]
```diff
@@ -54,76 +59,51 @@ pub enum EventKind {
...
-    ) -> Self {
-        let name = name.into();
-        debug_assert!(
-            name != "git_branch" && name != "location",
-            "We filter out the property name {name:?} on the server-end. Pick a different name."
-        );
-        self.props.insert(name, value.into());
-        self
+    #[inline]
+    pub fn identify() -> Self {
```
Comment (emilk) [inline crates/re_analytics/src/lib.rs:89]: please add a docstring

File: crates/re_analytics/src/lib.rs [hunk 7]
```diff
@@ -300,21 +281,25 @@ impl Analytics {
...
 
-    /// Register a property that will be included in all [`EventKind::Append`].
-    pub fn register_append_property(&mut self, name: &'static str, prop: impl Into<Property>) {
-        self.default_append_props.insert(name.into(), prop.into());
-    }
+    /// Record a single event.
+    ///
+    /// The event is constructed using the implementations of [`Event`] and [`Properties`].
+    /// The event's properties will be extended with an `event_id`.
+    #[allow(clippy::needless_pass_by_value)]
```
Comment (emilk) [inline crates/re_analytics/src/lib.rs:288]:
```suggestion
```

File: crates/re_crash_handler/src/lib.rs [hunk 8]
```diff
@@ -67,24 +67,14 @@ fn install_panic_hook(_build_info: BuildInfo) {
...
-
-                if let Some(file_line) = file_line {
-                    event = event.with_prop("file_line", file_line);
-                }
-
-                analytics.record(event);
+                analytics.record(re_analytics::event::CrashPanic {
+                    build_info: _build_info,
+                    callstack,
+                    // Don't include it, because it can contain sensitive information,
```
Comment (emilk) [inline crates/re_crash_handler/src/lib.rs:73]:
```suggestion
                    // Don't include panic message, because it can contain sensitive information,
```

File: crates/re_crash_handler/src/lib.rs [hunk 9]
```diff
@@ -202,12 +192,30 @@ fn install_signal_handler(build_info: BuildInfo) {
...
+            const NAME: &'static str = "crash-signal";
+        }
+
+        impl re_analytics::Properties for CrashSignal {
+            fn serialize(&self, event: &mut re_analytics::AnalyticsEvent) {
+                self.build_info.serialize(event);
+                event.insert("signal", self.signal.clone());
+                event.insert("callstack", self.callstack.clone());
+            }
+        }
```
Comment (emilk) [inline crates/re_crash_handler/src/lib.rs:211]: move `CrashSignal` to `crates/re_analytics/src/event.rs`

File: crates/re_viewer/src/app.rs [hunk 10]
```diff
@@ -138,7 +137,10 @@ pub struct App {
     command_receiver: CommandReceiver,
     cmd_palette: re_ui::CommandPalette,
 
-    analytics: ViewerAnalytics,
+    // NOTE: Optional because it is possible to have the `analytics` feature flag enabled
+    // while at the same time opting-out of analytics at run-time.
+    #[cfg(feature = "analytics")]
+    analytics: Option<crate::viewer_analytics::ViewerAnalytics>,
```
Comment (emilk) [inline crates/re_viewer/src/app.rs:143]: The old code encapsulated this `Option` and `#[cfg(feature = "analytics")]` so users of the analytics wouldn't need to care.

Now all uses of analytics will be littered with

```
#[cfg(feature = "analytics")]
if let Some(analytics) = &mut self.analytics {
    …
}
```

If we want to save CPU, we can still do

```
if self.analytics.is_enabled() {
    …
}
```

File: crates/re_viewer/src/viewer_analytics/event.rs [hunk 11]
```diff
@@ -0,0 +1,130 @@
+use crate::AppEnvironment;
```
Comment (emilk) [inline crates/re_viewer/src/viewer_analytics/event.rs:1]: Now that `viewer_analytics` is a mod dir, we should move `viewer_analytics.rs` -> `viewer_analytics/mod.rs`

File: crates/re_viewer/src/app.rs (hunk 10 above)
Comment (emilk) [reply crates/re_viewer/src/app.rs:143]: It's not used a lot now, but maybe it will be?

**Review by emilk — APPROVED** [review]
Much nicer!

File: crates/re_analytics/src/lib.rs (hunk 4 above)
Comment (jprochazk) [reply crates/re_analytics/src/lib.rs:84]: These are constructors, but they are no longer in use, so I removed them

File: crates/re_viewer/src/app.rs (hunk 10 above)
Comment (jprochazk) [reply crates/re_viewer/src/app.rs:143]: Yeah, it felt like a lot of `cfg`s where there should be just a few, but it makes more sense to move it back
