### PR TITLE
SDK batching/revamp 3: sunset `PythonSession`

### LINKED ISSUE #1619: Tracking issue: end-to-end batching
- Will create individual issues as the need arises.
- Most likely an evolving document.

[RFC](https://github.com/rerun-io/rerun/pull/1610)

---

- [x] Move `DataStore` sanity checks and formatting tools to separate files  
`store.rs` is supposed to be the place where one can get an overview of all the datastructures involved in the store, except it has slowly become a mess over time and is now pretty much unreadable.
- [x] Implement all the needed tests & benchmarks  
We need to be able to check for regressions at every step, so make sure we have all the tests and benchmarks we need for that.  
We should already be 95% of the way there at this point.

- [x] Replace `MsgBundle` & `ComponentBundle` with the new types (`DataCell`, `DataRow`, `DataTable`, `EventId`, `BatchId`...)  
No actual batching features nor any kind of behavior changes of any sort: just define the new types and use them everywhere.

- [x] Pass entity path as a column rather than as metadata  
Replace the current entity_path that is passed in the metadata map with an actual column instead. This will also requires us to make `EntityPath` a proper arrow datatype (..datatype, not component!!).

- [x] #1892
Issue created; not blocking for batching.

- [x] #1893  
Issue created; not blocking for batching.

- [x] Get rid of component buckets altogether  
Update the store implementation to remove component tables, remove the `get` APIs, introduce slicing on the write path, etc. Still no batching in sight!

- [ ] https://github.com/rerun-io/rerun/issues/1880

- [ ] Implement the coalescing/accumulation logic in the SDK  
Add the required logic/thread/timers/whatever-else in the SDKs to accumulate data and just send it all as many `LogMsg`s (i.e. no batching yet).

- [ ] Implement full-on batching  
End-to-end: transport, storage, the whele shebang.

- [ ] Sort the batch before sending (`(event_id, entity_path)`)  
Keep that in its own PR to keep track of the benchmarks.

- [x] Implement new GC  
The complete implementation; should close all existing GC issues.

- [x] Dump directly from the store into an rrd file  
No rebatching yet, just dump every event in its own `LogMsg`.

- [x] Remove `LogMsg`s from `LogDb`  
We shouldn't need to keep track of events outside the store past this point: clean it all up.  
Reminder: the timeline widget keeps track of timepoints directly, not events.

- [x] #1894  
Issue created; not blocking for batching.

- [x] #1891  
Issue created; not blocking for batching.

- [x] #1696   
Issue created; not blocking for batching.

- [x] #527

### PR DESCRIPTION
**Pull request by teh-cmc**
TODO:
- [ ] update rerun-docs if necessary
  - [ ] init mandatory
  - [ ] batching env vars
- [x] just py-run-all
- [x] just py-run-all without `init` calls shouldnt do anything crazy
- [x] missing init in notebook should clearly tell you what went wrong

---

1. #1980 
2. #1983
3. #2000 
4. #2002 
5. #1985

---

On top of #1983  
Fixes #1619 

Future work:
- expose individual `RecordingStream` to python: #1903

### CODE REVIEW

File: rerun_py/src/python_bridge.rs [hunk 1]
```diff
@@ -362,108 +361,78 @@ fn serve(open_browser: bool, web_port: Option<u16>, ws_port: Option<u16>) -> PyR
...
-impl PyMemorySinkStorage {
-    fn get_rrd_as_bytes<'p>(&self, py: Python<'p>) -> PyResult<&'p PyBytes> {
-        self.0
-            .rrd_as_bytes()
-            .map(|bytes| PyBytes::new(py, bytes.as_slice()))
-            .map_err(|err| PyRuntimeError::new_err(err.to_string()))
-    }
-}
+// TODO(jleibs) expose this as a python type
+fn start_web_viewer_server(port: u16) -> PyResult<()> {
```
Comment (jleibs) [inline rerun_py/src/python_bridge.rs:400]: You might want to cherry-pick this over as a starting point:
https://github.com/rerun-io/rerun/pull/2010/commits/707e76c76c35d111bef9e0e5192a5644d6d5da7e

File: rerun_py/src/python_bridge.rs [hunk 2]
```diff
@@ -500,16 +478,61 @@ fn reset_time() {
...
-fn convert_color(color: Vec<u8>) -> PyResult<[u8; 4]> {
-    match &color[..] {
-        [r, g, b] => Ok([*r, *g, *b, 255]),
-        [r, g, b, a] => Ok([*r, *g, *b, *a]),
-        _ => Err(PyTypeError::new_err(format!(
-            "Expected color to be of length 3 or 4, got {color:?}"
-        ))),
+/// Thread-local info
+#[derive(Default)]
+struct ThreadInfo {
```
Comment (teh-cmc) [inline rerun_py/src/python_bridge.rs:483]: move all of this into the `RecordingStream`

File: rerun_py/src/python_bridge.rs [hunk 3]
```diff
@@ -137,53 +101,120 @@ fn rerun_bindings(py: Python<'_>, m: &PyModule) -> PyResult<()> {
...
 
+    // misc
+    m.add_function(wrap_pyfunction!(get_app_url, m)?)?;
+    m.add_function(wrap_pyfunction!(get_recording_id, m)?)?;
+
     Ok(())
 }
 
+fn no_active_recording(origin: &str) {
+    re_log::debug!("No active recording - call to {origin}() ignored (have you called rr.init()?)",);
```
Comment (jleibs) [inline rerun_py/src/python_bridge.rs:153]: I think this should be at least warn-once? Most users won't have debug enabled.

**Review by jleibs — APPROVED** [review]
That seems straight forward. Nice improvement.

File: crates/re_sdk_comms/src/buffered_client.rs [hunk 4]
```diff
@@ -202,6 +202,10 @@ fn msg_encode(
                         re_log::error!("Failed to send message to tcp_sender thread. Likely a shutdown race-condition.");
                         return;
                     }
+                    // TODO: this is incorrect and dangerous: flush() can return before this
```
[the remark this answers is not in the document]
Comment (teh-cmc) [reply crates/re_sdk_comms/src/buffered_client.rs]: Magically fixed by all the changes to the shutdown process
