### PR TITLE
Fix `sensor_msgs::PointCloud2` MCAP parser for empty point clouds

### LINKED ISSUE #12683: MCAP PointCloud2 parser panics on empty ROS2 PointCloud2 messages with point_step == 0
**Describe the bug**

Loading an MCAP file that contains ROS2 `sensor_msgs/msg/PointCloud2` placeholder / empty messages crashes the viewer.

The offending messages appear to be valid empty point clouds with:
- `height = 0`
- `width = 0`
- `fields = []`
- `point_step = 0`
- `row_step = 0`
- `data = []`

Instead of skipping or handling these empty frames gracefully, Rerun panics with:

```text
panicked at crates/store/re_mcap/src/parsers/ros2msg/sensor_msgs/point_cloud_2.rs:171:30:
chunk size must be non-zero
```

**To Reproduce**

1. Open an MCAP file containing ROS2 sensor_msgs/msg/PointCloud2 messages.
2. Ensure at least one message is an empty / placeholder point cloud with point_step == 0.
3. Load the file in Rerun (web viewer or native viewer).
4. Observe that the viewer crashes.

**Expected behavior**

Rerun should not panic on empty PointCloud2 messages.
It should either:
- skip semantic extraction for those frames, or
- ingest them as empty point clouds / raw data without crashing.

**Screenshots**

Image

**Backtrace**

Rerun has crashed.

panicked at crates/store/re_mcap/src/parsers/ros2msg/sensor_msgs/point_cloud_2.rs:171:30:
chunk size must be non-zero

**Desktop (please complete the following information):**
 - OS: macOS 26.3.1 (25D2128)

**Rerun version**

0.28.0-alpha.1+dev (source build), commit deaef58e3749f9eb83951352c30b897867c3900c

**Additional context**

From local debugging, the problematic code path seems to be in:

- crates/store/re_mcap/src/parsers/ros2msg/sensor_msgs/point_cloud_2.rs
- Position3DIter::try_new, which calls data.chunks_exact(step)
- the field extraction loop, which calls point_cloud.data.chunks(point_cloud.point_step as usize)

Both paths are unsafe when point_step == 0.

I have a local fix and can open a PR for this.

### PR DESCRIPTION
**Pull request by Woodii1998**
### Related

Closes #12683

### What

Fixes a panic in the ROS 2 `sensor_msgs/msg/PointCloud2` MCAP parser when loading empty / placeholder point clouds.

Some MCAP files contain `PointCloud2` messages with `point_step == 0`, no fields, and no payload. Rerun previously tried to chunk the point blob using that zero step size, which caused a panic (`chunk size must be non-zero`) and crashed the viewer.

This change adds guards to skip semantic point extraction and per-field extraction when `point_step == 0`, and adds a regression test covering a valid point cloud followed by an empty placeholder message.

No breaking changes.

### CODE REVIEW

**Comment by MichaelGrupp** [comment]
@rerun-bot reality-sync

File: crates/store/re_mcap/src/parsers/ros2msg/sensor_msgs/point_cloud_2.rs [hunk 1]
```diff
@@ -590,3 +599,114 @@ impl MessageParser for PointCloud2MessageParser {
...
+
+        parser
+            .append(&mut ctx, &cdr_message(&empty_message))
+            .unwrap();
+
+        let chunks = Box::new(parser).finalize(ctx).unwrap();
+        let row_counts = chunks.iter().map(Chunk::num_rows).collect::<Vec<_>>();
+
+        assert_eq!(chunks.len(), 3);
+        assert_eq!(row_counts, vec![2, 1, 2]);
```
Comment (MichaelGrupp) [inline crates/store/re_mcap/src/parsers/ros2msg/sensor_msgs/point_cloud_2.rs:722]: Let's add also a check that the contents of the non-empty message are there (checking that we get an intensity entry should be enough).
```suggestion
        let row_counts = chunks.iter().map(Chunk::num_rows).collect::<Vec<_>>();
        let data_chunk = chunks
            .iter()
            .find(|chunk| chunk.num_rows() == 2 && chunk.num_components() > 1)
            .unwrap();
        let intensity_descriptor = ComponentDescriptor::partial("intensity")
            .with_builtin_archetype(archetypes::Points3D::name());

        assert_eq!(chunks.len(), 3);
        assert_eq!(row_counts, vec![2, 1, 2]);
        assert!(
            data_chunk
                .component_descriptors()
                .any(|descriptor| descriptor == &intensity_descriptor)
        );
```

File: crates/store/re_mcap/src/parsers/ros2msg/sensor_msgs/point_cloud_2.rs
Comment (MichaelGrupp) [inline crates/store/re_mcap/src/parsers/ros2msg/sensor_msgs/point_cloud_2.rs]: This here needs to be adapted too, because it would invalidate `extracted_fields` if there are no fields.
```suggestion
        if extracted_fields.is_empty && !point_cloud.fields.is_empty() {
```

Comment (Woodii1998) [reply crates/store/re_mcap/src/parsers/ros2msg/sensor_msgs/point_cloud_2.rs]: There's a missing parenthesis, but don't worry, I'll fix it and then test the data I have.

**Comment by Woodii1998** [comment]
looks good

**Comment by Woodii1998** [comment]
Hi @MichaelGrupp , 

I've addressed all the feedback from the previous review.  
Could you please take another look when you have time? 

Thanks!

**Comment by MichaelGrupp** [comment]
@rerun-bot reality-sync

**Comment by MichaelGrupp** [comment]
@rerun-bot reality-sync

**Comment by MichaelGrupp** [comment]
Hi, sorry I was busy the last days. I'm working on getting it merged now, thanks for updating the PR

**Comment by MichaelGrupp** [comment]
@rerun-bot reality-sync

**Comment by MichaelGrupp** [comment]
@rerun-bot reality-sync
