### PR TITLE
Handle reentrancy edge case in deserialization cache

### LINKED ISSUE #6195: Panic in `RangeComponentResults::to_dense`
Panic due to the `unwrap` on line 579:

https://github.com/rerun-io/rerun/blob/5b0dbb5a3ffe24991bc19794c96cab73fa20dfa3/crates/re_query/src/range/results.rs#L574-L582

Files for repro:
[repor_crash.zip](https://github.com/rerun-io/rerun/files/15189066/repor_crash.zip)

```
thread 'rayon-2' panicked at 'called `Option::unwrap()` on a `None` value'
re_query/src/range/results.rs:579
stack backtrace:
   8: core::panicking::panic_fmt
             at core/src/panicking.rs:72:14
   9: core::panicking::panic
             at core/src/panicking.rs:144:5
  10: re_space_view_time_series::point_visualizer_system::SeriesPointSystem::load_scalars
  11: <re_space_view_time_series::point_visualizer_system::SeriesPointSystem as re_viewer_context::space_view::visualizer_system::VisualizerSystem>::execute
             at re_space_view_time_series/src/point_visualizer_system.rs:66:15
  12: re_viewport::system_execution::create_and_run_space_view_systems::{{closure}}
             at re_viewport/src/system_execution.rs:47:19
      core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
             at core/src/ops/function.rs:272:13
  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at core/src/ops/function.rs:305:13
      core::option::Option<T>::map
             at core/src/option.rs:1072:29
      <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at core/src/iter/adapters/map.rs:104:26
      rayon::iter::plumbing::Folder::consume_iter
             at rayon-1.7.0/src/iter/plumbing/mod.rs:178:21
  14: <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at rayon-1.7.0/src/iter/map.rs:248:21
      rayon::iter::plumbing::Producer::fold_with
             at rayon-1.7.0/src/iter/plumbing/mod.rs:110:9
      rayon::iter::plumbing::bridge_producer_consumer::helper
             at rayon-1.7.0/src/iter/plumbing/mod.rs:438:13
  15: rayon_core::join::join_context::{{closure}}
  16: rayon_core::join::join_context
             at rayon-core-1.11.0/src/join/mod.rs:132:5
      rayon::iter::plumbing::bridge_producer_consumer::helper
             at rayon-1.7.0/src/iter/plumbing/mod.rs:416:47
  17: rayon::iter::plumbing::bridge_producer_consumer
             at rayon-1.7.0/src/iter/plumbing/mod.rs:397:12
      <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback
             at rayon-1.7.0/src/iter/plumbing/mod.rs:373:13
      <rayon::vec::Drain<T> as rayon::iter::IndexedParallelIterator>::with_producer
             at rayon-1.7.0/src/vec.rs:147:13
      <rayon::vec::IntoIter<T> as rayon::iter::IndexedParallelIterator>::with_producer
             at rayon-1.7.0/src/vec.rs:83:9
  18: rayon::iter::plumbing::bridge
             at rayon-1.7.0/src/iter/plumbing/mod.rs:357:12
  19: <rayon::vec::IntoIter<T> as rayon::iter::ParallelIterator>::drive_unindexed
             at rayon-1.7.0/src/vec.rs:58:9
      <rayon::collections::hash_map::IterMut<K,V> as rayon::iter::ParallelIterator>::drive_unindexed
             at rayon-1.7.0/src/delegate.rs:21:28
      <rayon::iter::map::Map<I,F> as rayon::iter::ParallelIterator>::drive_unindexed
             at rayon-1.7.0/src/iter/map.rs:49:9
      <rayon::iter::flatten::Flatten<I> as rayon::iter::ParallelIterator>::drive_unindexed
             at rayon-1.7.0/src/iter/flatten.rs:38:9
      rayon::iter::extend::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend
             at rayon-1.7.0/src/iter/extend.rs:576:28
      rayon::iter::from_par_iter::collect_extended
             at rayon-1.7.0/src/iter/from_par_iter.rs:17:5
      rayon::iter::from_par_iter::<impl rayon::iter::FromParallelIterator<T> for alloc::vec::Vec<T>>::from_par_iter
             at rayon-1.7.0/src/iter/from_par_iter.rs:30:9
      rayon::iter::ParallelIterator::collect
             at rayon-1.7.0/src/iter/mod.rs:2056:9
      re_viewport::system_execution::create_and_run_space_view_systems
             at re_viewport/src/system_execution.rs:42:21
      re_viewport::system_execution::execute_systems_for_space_view
             at re_viewport/src/system_execution.rs:133:9
  20: re_viewport::system_execution::execute_systems_for_all_space_views::{{closure}}::{{closure}}::{{closure}}
             at re_viewport/src/system_execution.rs:83:38
      core::option::Option<T>::map
             at core/src/option.rs:1072:29
      re_viewport::system_execution::execute_systems_for_all_space_views::{{closure}}::{{closure}}
             at re_viewport/src/system_execution.rs:81:21
      core::option::Option<T>::and_then
             at core/src/option.rs:1406:24
      re_viewport::system_execution::execute_systems_for_all_space_views::{{closure}}
             at re_viewport/src/system_execution.rs:79:13
      <rayon::iter::filter_map::FilterMapFolder<C,P> as rayon::iter::plumbing::Folder<T>>::consume
             at rayon-1.7.0/src/iter/filter_map.rs:123:36
  21: rayon::iter::plumbing::Folder::consume_iter
             at rayon-1.7.0/src/iter/plumbing/mod.rs:179:20
      rayon::iter::plumbing::Producer::fold_with
             at rayon-1.7.0/src/iter/plumbing/mod.rs:110:9
      rayon::iter::plumbing::bridge_producer_consumer::helper
             at rayon-1.7.0/src/iter/plumbing/mod.rs:438:13
  22: rayon_core::join::join_context::{{closure}}
  23: rayon_core::join::join_context
             at rayon-core-1.11.0/src/join/mod.rs:132:5
      rayon::iter::plumbing::bridge_producer_consumer::helper
             at rayon-1.7.0/src/iter/plumbing/mod.rs:416:47
  24: rayon_core::join::join_context::{{closure}}
  25: rayon_core::join::join_context
             at rayon-core-1.11.0/src/join/mod.rs:132:5
      rayon::iter::plumbing::bridge_producer_consumer::helper
             at rayon-1.7.0/src/iter/plumbing/mod.rs:416:47
  26: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at rayon-1.7.0/src/iter/plumbing/mod.rs:427:21
      rayon_core::join::join_context::call_b::{{closure}}
             at rayon-core-1.11.0/src/join/mod.rs:129:25
      rayon_core::job::JobResult<T>::call::{{closure}}
             at rayon-core-1.11.0/src/job.rs:218:41
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at core/src/panic/unwind_safe.rs:272:9
      std::panicking::try::do_call
             at std/src/panicking.rs:552:40
      std::panicking::try
             at std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at std/src/panic.rs:142:14
      rayon_core::unwind::halt_unwinding
             at rayon-core-1.11.0/src/unwind.rs:17:5
      rayon_core::job::JobResult<T>::call
             at rayon-core-1.11.0/src/job.rs:218:15
      <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
             at rayon-core-1.11.0/src/job.rs:120:32
  27: rayon_core::job::JobRef::execute
             at rayon-core-1.11.0/src/job.rs:64:9
      rayon_core::registry::WorkerThread::execute
             at rayon-core-1.11.0/src/registry.rs:874:13
      rayon_core::registry::WorkerThread::wait_until_cold
             at rayon-core-1.11.0/src/registry.rs:820:22
  28: rayon_core::registry::WorkerThread::wait_until
             at rayon-core-1.11.0/src/registry.rs:803:13
      rayon_core::registry::main_loop
             at rayon-core-1.11.0/src/registry.rs:948:5
      rayon_core::registry::ThreadBuilder::run
             at rayon-core-1.11.0/src/registry.rs:54:18
  29: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}}
             at rayon-core-1.11.0/src/registry.rs:99:20
```

### PR DESCRIPTION
**Pull request by teh-cmc**
- Fixes #6195 

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using examples from latest `main` build: [rerun.io/viewer](https://rerun.io/viewer/pr/6208?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [rerun.io/viewer](https://rerun.io/viewer/pr/6208?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!

- [PR Build Summary](https://build.rerun.io/pr/6208)
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

File: crates/re_query/src/range/results.rs [hunk 1]
```diff
@@ -566,6 +566,24 @@ impl RangeComponentResults {
...
+        if results.cached_dense.is_none() {
+            return RangeData {
+                indices: None,
+                data: None,
+                time_range: TimeRange::EMPTY,
+                front_status: PromiseResult::Ready(()),
+                back_status: PromiseResult::Ready(()),
+                reentering: &REENTERING,
+            };
+        }
```
Comment (emilk) [inline crates/re_query/src/range/results.rs:585]: Is there a possibility for some other thread to do something bad between this `if` and the the unwrap below?

**Review by emilk — APPROVED** [review]

File: crates/re_query/src/range/results.rs (hunk 1 above)
Comment (teh-cmc) [reply crates/re_query/src/range/results.rs:585]: Not that I know of; but I'd like to automate as much as possible the reentrancy checklist entry in a follow up PR, now that we can programmatically set time ranges.
