### PR TITLE
File-like entity paths

### LINKED ISSUE #3697: Space view names from drag & drop escape double slash
image

### LINKED ISSUE #3995: Warning about missing quotes in entity paths can be annoying
> WARN  re_log_types::path::parse_path] Found an entity path 'world/100_7100.JPG' that was not in the normalized form. Please write it as 'world/"100_7100.JPG"' instead.

### LINKED ISSUE #4338: Standardize how we show entity paths to the user
### Problem
Example entity paths, as currently shown with our `Display` implementation:

* `world/points`
* `images/"string"/segmentation`
* `images/"My Image.jpeg"/segmentation`
* `images/"Random text with newlines \n and quotes \"!"/segmentation`

As you see, newlines, quotes etc are already escaped in each individual string, so the formatted entity-path will not contain weird newlines etc.

Our `Debug` implementation for `EntityPath` is broken, and escapes newlines and backslashes _again_, which is just …bad, and should be fixed.

### String in paths
Note that there is a difference between _names_ (`world`, `points`, `images`, `segmentation`) and _strings_ (`"string", "My Image.jpeg", "Random text with newlines \n and quotes \"!"). Names are kind to struct-fields, while strings are kin to table keys. 

Maybe we shouldn't have this distinction, and instead do what most operating system do with paths: escape slashes and spaces (in addition to newlines etc) in embedded string, i.e.:  `images/My\ Image.jpeg/segmentation`.

### How to embed a path in a bigger string
So how do we show an entity path to the user when embedded in a larger string? In GUI:s we could use a separate background color or font, but that doesn't work everywhere (e.g. console logging), so I prefer a solution that is ASCII-based.

Using just `Display` seems like a bad idea:

* `eprintln!("There is a problem with {entity}")` -> `There is a problem with humanity`

Double-quotes will clash with existing quotes in the string:

* `eprintln!("There is a problem with \"{entity}\"")` -> `There is a problem with "certain/" bugs and "/issues"`

Single-quotes seems better:

* `eprintln!("There is a problem with '{entity}'")` -> `There is a problem with 'certain/" bugs and "/issues'`

### Enforcement
Let's assume for a second we opt to select all entity paths in single quotes - how do we enforce it?

We can change `Display` to add the  `'quotes'` around the entity-path, and then always use `Display` (i.e. `{}`) to display the strings. This is after all the purpose of `Display`. In the long-run we can add a lint against using Debug-formatting for anything user-facing, but in the short term we can change `Debug` to act exactly like `Display`. That way we can't go wrong, as long as we don't add extra explicit quotes (`\"{}\"), which we already have a lint against in `lint.py`.

There are cases though when entity-paths are standing alone in the UI (streams panel, selection panel) - do we really want to add single-quotes to those places too?

### Related issues
* https://github.com/rerun-io/rerun/issues/3697
* https://github.com/rerun-io/rerun/issues/3995

### LINKED ISSUE #4464: Make entity paths more similar to file paths
## Motivation
People are used to file paths.
If we follow their lead, things like globs become more natural.

### Examples of what we would like to do
* Write glob matches: `/world/**`
* Use `.` to mean "this folder", as in `/world/car/.`
* Allow users to put file and folder names into entity paths
* Prefix paths with minus in some queries (`-/world` == everything not in the world)
* Reserve the right for special characters to have special meanings
  * E.g. use `?` for a query suffix, `/entity/path?Confidence>0.5`

## Summary
Entities are like folders, and components are like files.

When we print things, always normalize, and use syntax highlighting in the GUI.

Each part of an entity path is just a string.

We escape characters with `\`, so e.g. `\n` is a newline and `\ ` is a space.

Example: `/world/my\ image.JPG/`

## Parsing
Be VERY liberal in what we accept, but print warnings.

* empty string is the same as root (`/`)
* multiple consecutive slashes are  treated as one slash
  * `world//car` => `world/car`
  * Allows user to do: `world/` + `/car`
  * Foot-gun: `f"world/{name}/car"` with empty name
* Unrecognized escapes are ignored so that `\x` is the same as `x`

## Printing
* Always escape anything not in `a-zA-Z0-9.-_`
* In each part, escape leading non-alpha-numeric characters with `\`
* Maybe (TBD):
  * Each path starts with a slash
* Color-code slashes and escapes in GUI
* Special-handle numbers when ordering, so that `/image/3` comes before `/image/10`
 
## Together with other things
We separate entity paths from component names with a colon: `/car:Position3D` (`:` in entity parts are escaped).

We separate entity paths from instance keys with `[]`: `/points[42]` (`[` in entity parts are escaped).

## Future
We would like to expand the paths to uniquely identify a piece of data, which would require something like:

`STORE_ID:/world/points[52]:Position3D[2]@frame=42`

```rs
struct DataSelector {
  store_id:       Optional<…>,
  entity_path:    Optional<…>,
  instance_key:   Optional<…>,
  component_name: Optional<…>,
  arrow_selector: Optional<…>,
  time_query:     Optional<…>,
}
```

### PR DESCRIPTION
**Pull request by emilk**
### What
This is a breaking change, though in _most_ cases it is a cosmetic one.

This PR makes entity paths work a lot more similar to file paths.
There is no need for `"` quotes around path parts, instead we now use `\` to escape special characters.

You need to escape any character that isn't alphabetical, numeric, `.`, `-`, or `_`.

Before: `world/"My Image.jpg"/detection`
After: `world/My\ Image.jpg/detection`

The entity path parser is very liberal in what it accepts (in fact, it never errors), but it will log a warning if the entity path doesn't follow the normalized form.

NOTE: unicode characters do NOT need escaping, so `värld/bil` is a valid entity path.
We also support unicode escapes like `\u{211D}`.

More details here: https://github.com/rerun-io/rerun/issues/4464

* Closes #3697
* Closes #3995
* Closes #4338
* Closes #4464

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Full build: [app.rerun.io](https://app.rerun.io/pr/4476/index.html)
  * Partial build: [app.rerun.io](https://app.rerun.io/pr/4476/index.html?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json) - Useful for quick testing when changes do not affect examples in any way
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG

- [PR Build Summary](https://build.rerun.io/pr/4476)
- [Docs preview](https://rerun.io/preview/2c7017ea73627cfec74d4aedb0aaa680344624d8/docs) 
- [Examples preview](https://rerun.io/preview/2c7017ea73627cfec74d4aedb0aaa680344624d8/examples) 
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

### CODE REVIEW

File: crates/re_log_types/src/path/parse_path.rs [hunk 1]
```diff
@@ -154,44 +146,41 @@ impl EntityPath {
...
         if let Some(instance_key) = instance_key {
             return Err(PathParseError::UnexpectedInstanceKey(instance_key));
         }
         if let Some(component_name) = component_name {
             return Err(PathParseError::UnexpectedComponentName(component_name));
         }
+
+        let normalized = entity_path.to_string();
+        if normalized != input {
+            re_log::warn_once!("The entity path '{input}' that was not in the normalized form. It will be interpreted as '{normalized}'. See https://www.rerun.io/docs/concepts/entity-path for more");
```
Comment (jleibs) [inline crates/re_log_types/src/path/parse_path.rs:165]:
```suggestion
            re_log::warn_once!("The entity path '{input}' was not in the normalized form. It will be interpreted as '{normalized}'. See https://www.rerun.io/docs/concepts/entity-path for more");
```

File: crates/re_log_types/src/path/parse_path.rs [hunk 2]
```diff
@@ -154,44 +146,41 @@ impl EntityPath {
...
-        let path = EntityPath::from(parts);
+    pub fn parse_forgiving(input: &str) -> Self {
+        let parts = parse_entity_path_forgiving(input);
+        let entity_path = EntityPath::from(parts);
 
-        if path.to_string() != s {
-            re_log::warn_once!("Found an entity path '{s}' that was not in the normalized form. Please write it as '{path}' instead. Only ASCII characters, numbers, underscore, and dash are allowed in identifiers. To put arbitrary text in an entity path, surround it with double-quotes. See https://www.rerun.io/docs/concepts/entity-path for more");
+        let normalized = entity_path.to_string();
+        if normalized != input {
+            re_log::warn_once!("The entity path '{input}' that was not in the normalized form. It will be interpreted as '{normalized}'. See https://www.rerun.io/docs/concepts/entity-path for more");
```
Comment (jleibs) [inline crates/re_log_types/src/path/parse_path.rs:180]:
```suggestion
            re_log::warn_once!("The entity path '{input}' was not in the normalized form. It will be interpreted as '{normalized}'. See https://www.rerun.io/docs/concepts/entity-path for more");
```

File: docs/content/concepts/entity-path.md [hunk 3]
```diff
@@ -17,32 +17,37 @@ elements. The conventional path semantics including concepts of *root* and *pare
...
-However, it is also acceptable to leave implicitly "empty" elements in your paths as well.
+It is also acceptable to leave implicitly "empty" entities in your paths as well.
 ```python
 rr.log("camera/image", rr.Image(img))
 rr.log("camera/image/detections/points", rr.Points2D(points))
 ```
+
 Nothing needs to be explicitly logged to `"camera"` or `"camera/image/detection"` to make the above valid.
+In other words, the `log` call is akin to creating a folder with `mkdir -p` and then writing files (components) to it.
+Existing components of the same name will be overwritten.
```
Comment (jleibs) [inline docs/content/concepts/entity-path.md:38]: I'm still liking this analogy!

**Review by jleibs — APPROVED** [review]

File: docs/content/concepts/entity-path.md (hunk 3 above)
Comment (emilk) [reply docs/content/concepts/entity-path.md:38]: me too :)
