### PR TITLE
Fix double clicking objects no longer focusing the camera on them

### LINKED ISSUE #2215: Double-click to zoom to a point is broken
Can repro on colmap. Just double-click a point in the point-cloud.
 - Worked on 0.4.0: https://app.rerun.io/version/v0.4.0/index.html
 - Broken on 0.5.0: https://app.rerun.io/version/v0.5.0/index.html

### PR DESCRIPTION
**Pull request by Wumpf**
_Requires #2188_ ✔️ 

Fixes #2215 
* #2215 

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)

PR Build Summary: https://build.rerun.io/pr/2227

### CODE REVIEW

File: crates/re_viewer/src/ui/view_spatial/ui_3d.rs [hunk 1]
```diff
@@ -47,9 +47,6 @@ pub struct View3DState {
 
     eye_interpolation: Option<EyeInterpolation>,
 
-    /// Where in world space the mouse is hovering (from previous frame)
-    hovered_point: Option<glam::Vec3>,
```
Comment (emilk) [inline crates/re_viewer/src/ui/view_spatial/ui_3d.rs:51]: Ouch, I would had hoped clippy would have caught a field only being read from

**Review by emilk — APPROVED** [review]
