### PR TITLE
Fix missing data for "bridged" range queries

### LINKED ISSUE #5686: Visible time range queries skip random chunks of data (for 2D points)
**Describe the bug**
It seems like the visible time range queries sometimes miss chunks, i.e., one or more consecutive datapoints. I have observed this with the drone example (with Points3D) before, but had trouble reproducing it reliably in that case. I believe this is happening since the caching was introduced.

**To Reproduce**
Check [this](https://drive.google.com/file/d/1qvkYXRFWxkU-V9RDl222ST-kfiHU9T7O/view?usp=sharing) rrd file.

It contains sampled images over time (logged as colored 2D points) and the image changes every second. When setting the visibility history to -1s and scrolling along the timeline, black parts without any data appear despite data being logged at these times. The sections with missing data change when restarting the viewer, but there always seem to be one or more. Somewhat easy to find by just scrolling along the axis looking for black parts to appear.

https://github.com/rerun-io/rerun/assets/9785832/a1fb93d6-de3b-4fa5-b539-ef6f0b55175c

The issue can be seen at around 0:18, before I'm just showing what the data looks like.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Rerun version**
> rerun_py 0.14.1 [rustc 1.74.0 (79e9716c9 2023-11-13), LLVM 17.0.4] x86_64-unknown-linux-gnu release-0.14.1 74f1c23, built 2024-02-29T11:00:55Z

### PR DESCRIPTION
**Pull request by teh-cmc**
A cheap fix for #5686, both in terms of added code and runtime performance, as it only kicks in in very particular circumstances.
The test added in this PR explains the situation better than words ever could.

The proper solution here would to implement proper bucketing in the range cache (#4810), but that's a much bigger change that I don't want to get into until after the upcoming drastic changes to the datastore.

- Fixes #5686 

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using examples from latest `main` build: [rerun.io/viewer](https://rerun.io/viewer/pr/6177?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [rerun.io/viewer](https://rerun.io/viewer/pr/6177?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!

- [PR Build Summary](https://build.rerun.io/pr/6177)
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

File: crates/re_query/src/range/query.rs [hunk 1]
```diff
@@ -47,7 +48,65 @@ impl Caches {
...
+                        let hole_end =
+                            TimeInt::new_temporal(query.range().min().as_i64().saturating_sub(1));
+                        if hole_start < hole_end {
+                            if let Some((data_time, _, _)) = store.latest_at(
+                                &LatestAtQuery::new(query.timeline(), hole_end),
+                                entity_path,
+                                component_name,
+                                &[component_name],
+                            ) {
+                                if data_time != hole_start {
```
Comment (jleibs) [inline crates/re_query/src/range/query.rs:79]: Again a little confused by what's happening here. I suspect this is to avoid invalidating in cases where the hole otherwise contains no data.

However, shouldn't it be `data_time > hole_start`. 

Any situation where `data_time < hole_start` doesn't seem like it should require an invalidation since the values pulled in by the new query should be correct?

File: crates/re_query/src/range/query.rs [hunk 2]
```diff
@@ -47,7 +48,65 @@ impl Caches {
...
+            // and coarsly invalidates the whole range in that case, to avoid the kind of bugs
+            // showcased in <https://github.com/rerun-io/rerun/issues/5686>.
+            {
+                let time_range = cache.per_data_time.read_recursive().time_range();
+                if let Some(time_range) = time_range {
+                    {
+                        let hole_start = time_range.max();
+                        let hole_end =
+                            TimeInt::new_temporal(query.range().min().as_i64().saturating_sub(1));
+                        if hole_start < hole_end {
```
[the remark this answers is not in the document]
Comment (teh-cmc) [reply crates/re_query/src/range/query.rs:72]: > It looks like what's going on is that is that any time a new query comes before or after the existing range cache, then we clear the cache to avoid ever ending up with a hole in the first place?

Yes, we prematurely clear the cache anytime two non-contiguous queries (as defined by the checks below) come in one after another, to keep it simple.

File: crates/re_query/src/range/query.rs (hunk 1 above)
Comment (teh-cmc) [reply crates/re_query/src/range/query.rs]: Yeah you're right, nice catch

**Review by jleibs — APPROVED** [review]
