### PR TITLE
Fix presence of segmentation images and tensor causing generation of root space view

### LINKED ISSUE #3677: Bad heuristic results in adding inappropriate segmentation to 3D scenes
Repro:
```
"""Log a pinhole and a random image."""
import numpy as np
import rerun as rr

rr.init("rerun_example_pinhole", spawn=True)
rng = np.random.default_rng(12345)

image = rng.uniform(0, 255, size=[3, 3, 3])
rr.log("world/camera/image", rr.Pinhole(focal_length=3, width=3, height=3))
rr.log("world/camera/image", rr.Image(image))

image = rng.uniform(0, 255, size=[3, 3, 1])
rr.log("seg", rr.SegmentationImage(image))
```

image

Note this *only* happens with `rr.SegmentationImage` but not with `rr.Image` so there's probably some place we need to do a more complete check.

### PR DESCRIPTION
**Pull request by Wumpf**
### What

* Fixes #3677

Definitely need to come up with something better to steer the heuristics - we made good strides in space view refactor and recent advances in System heuristics, but there's still a lot to be desired!

In the test scene there's still the issue of a unexplicably large accumulated bounding box which causes the camera to zoom out a lot. This is most likely caused by an initially bad heuristic for the frustum length. I suspect this is a problem we already had in 0.8 and might be fairly hard to solve until we fixup our blueprint & object property story.

Before:
image

After:
image

Test code:
```py
"""Log a pinhole and a random image."""
import numpy as np
import rerun as rr

rr.init("rerun_example_pinhole", spawn=True)
rng = np.random.default_rng(12345)

image = rng.uniform(0, 255, size=[3, 3, 3])
rr.log("world/camera/image", rr.Pinhole(focal_length=3, width=3, height=3))
rr.log("world/camera/image", rr.Image(image))

image = rng.uniform(0, 255, size=[3, 3, 1])
rr.log("seg", rr.SegmentationImage(image))
```

Also made sure this doesn't regress the fix in #3583 (which touched this code last!)

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested [demo.rerun.io](https://demo.rerun.io/pr/3681) (if applicable)

- [PR Build Summary](https://build.rerun.io/pr/3681)
- [Docs preview](https://rerun.io/preview/a29d7764be26c9cc746a726c589a284ef7efad8f/docs) 
- [Examples preview](https://rerun.io/preview/a29d7764be26c9cc746a726c589a284ef7efad8f/examples) 
- [Recent benchmark results](https://ref.rerun.io/dev/bench/)
- [Wasm size tracking](https://ref.rerun.io/dev/sizes/)

### CODE REVIEW

File: crates/re_viewport/src/space_view_heuristics.rs [hunk 1]
```diff
@@ -142,10 +143,12 @@ fn is_interesting_space_view_at_root(
         return false;
     }
 
+    // TODO(andreas): We have to figure out how to do this kind of heuristic in a more generic way without deep knowledge of re_types.
+    //
     // If there are any images directly under the root, don't create root space either.
     // -> For images we want more fine grained control and resort to child-of-root spaces only.
     for entity_path in &candidate.contents.root_group().entities {
-        if contains_any_image(entity_path, data_store) {
+        if contains_tensor_data(entity_path, data_store) {
```
Comment (emilk) [inline crates/re_viewport/src/space_view_heuristics.rs:151]: Will this mess things up for non-2D tensors?

**Review by emilk — COMMENTED** [review]
So `is_interesting_space_view_at_root` used to return `true` for segmentation images, but I don't understand how that would put it in the same spaceview as an entity with a different root?

File: crates/re_viewport/src/space_view_heuristics.rs (hunk 1 above)
Comment (Wumpf) [reply crates/re_viewport/src/space_view_heuristics.rs:151]: I think you're right. The old code did this:
https://github.com/rerun-io/rerun/blob/release-0.8/crates/re_viewport/src/space_view_heuristics.rs#L76

**Comment by Wumpf** [comment]
> but I don't understand how that would put it in the same spaceview as an entity with a different root?

Root is *the* root here, i.e. `/`. If we decide to create one there we end up deciding it must be 3D and then things go awry

File: crates/re_viewport/src/space_view_heuristics.rs (hunk 1 above)
Comment (Wumpf) [reply crates/re_viewport/src/space_view_heuristics.rs:151]: I'm a bit concerned now. I could do the 2dness check on top and be mostly with the old behavior but this has slight regression potential on the fix from https://github.com/rerun-io/rerun/pull/3583
Well, let's try it out!

Comment (Wumpf) [reply crates/re_viewport/src/space_view_heuristics.rs:151]: Actually it would be probably best then to check for Image _and_ SegmentationImage indicators.

Comment (Wumpf) [reply crates/re_viewport/src/space_view_heuristics.rs:154]: yes. This seems safest, easiest and passes both repro scripts

**Comment by emilk** [comment]
`scripts/run_all.py` looks good

**Review by emilk — APPROVED** [review]
