### PR TITLE
Fix issues with seeking in some H.264 videos on native & web

### LINKED ISSUE #8098: Problem time-stepping some videos
Problem video:  https://github.com/user-attachments/files/17713986/1517176996106838023-vUiO9nkD-I5wwMDD.mp4.zip

> on both web and native, the video player will go into an infinite spinner loop if you step backwards, but only for every second step (see attached video)

https://github.com/user-attachments/assets/ebfd0ea1-b6e3-4b4a-a15b-22ddb7cc8bd0

### PR DESCRIPTION
**Pull request by Wumpf**
### What

* Fixes #8098

Updates re_mp4 to 0.3.0, details of fixes see https://github.com/rerun-io/re_mp4/releases/tag/0.3.0

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using examples from latest `main` build: [rerun.io/viewer](https://rerun.io/viewer/pr/8111?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [rerun.io/viewer](https://rerun.io/viewer/pr/8111?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!
* [x] If have noted any breaking changes to the log API in `CHANGELOG.md` and the migration guide

- [PR Build Summary](https://build.rerun.io/pr/8111)
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

**Comment by Wumpf** [comment]
Tested the "oscilloscope video" on Web: Works but Firefox still struggles with bframe stepping (there's a separate issue about this), fine in Chrome though

File: crates/store/re_video/src/demux/mp4.rs [hunk 1]
```diff
@@ -75,6 +75,24 @@ impl VideoData {
             }
         }
 
+        // Generate data for `test_latest_sample_index_at_presentation_timestamp` test.
+        // re_log::info!(
```
Comment (emilk) [inline crates/store/re_video/src/demux/mp4.rs:79]: If you use `if false {` instead the code won't code-rot

File: crates/viewer/re_data_ui/src/video.rs [hunk 2]
```diff
@@ -113,7 +113,9 @@ fn video_data_ui(ui: &mut egui::Ui, ui_layout: UiLayout, video_data: &VideoData)
                     .value_text(video_data.gops.len().to_string()),
             )
             .on_hover_text("The total number of Group of Pictures (GOPs) in the video.");
-            samples_statistics_ui(ui, &video_data.samples_statistics);
+            ui.list_item_flat_noninteractive(
+                PropertyContent::new("All PTS equal DTS").value_bool(video_data.samples_statistics.dts_always_equal_pts)
```
Comment (emilk) [inline crates/viewer/re_data_ui/src/video.rs:117]: It would be nice to destruct `samples_statistics` here so that if we add new fields to it, we remember to also add a UI for it

**Review by emilk — APPROVED** [review]
