### PR TITLE
datastore: stabilize dataframe sorts

### LINKED ISSUE #894: Unstable test, `re_arrow_store::store_polars::to_dataframe` fails
**Describe the bug**
Test instability on CI. One instance of it:
https://github.com/rerun-io/rerun/actions/runs/3995045925/jobs/6853468210

**Backtrace**
```
 thread 'gc_correct' panicked at 'called `Option::unwrap()` on a `None` value', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/polars-core-0.26.1/src/utils/mod.rs:601:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
   3: core::option::Option<T>::unwrap
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/option.rs:775:21
   4: polars_core::utils::concat_df
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/polars-core-0.26.1/src/utils/mod.rs:601:22
   5: polars_core::functions::diag_concat_df
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/polars-core-0.26.1/src/functions.rs:289:5
   6: re_arrow_store::store_polars::<impl re_arrow_store::store::DataStore>::to_dataframe
             at ./src/store_polars.rs:94:18
   7: correctness::gc_correct
             at ./tests/correctness.rs:377:9
   8: correctness::gc_correct::{{closure}}
             at ./tests/correctness.rs:345:1
   9: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by teh-cmc**
This fixes some very real issues with dataframe sorting that cost me some hair when implementing tests for the defunct #1527.

This does _not_ fix #894, as there is in fact a very real bug in the GC and the flakiness is justified; but that's a topic for another PR that I'll cover tomorrow when I can finally focus on GC stuff.

(github won't let me _not_ close #894 now that I've mentioned it apparently... I'll re-open it manually once this is merged...)

### CODE REVIEW

File: crates/re_arrow_store/src/store_polars.rs [hunk 1]
```diff
@@ -89,25 +89,48 @@ impl DataStore {
...
         ]
         .into_iter()
         .flatten()
+        // NOTE: Already properly arranged above, and already contains insert_id if needed.
+        .chain(
+            df.get_column_names()
+                .into_iter()
+                .filter(|col| *col != TIMELESS_COL) // we handle this one separately
+                .filter(|col| *col != insert_id_col) // we handle this one separately
+                .filter(|col| !col.starts_with("rerun.")) // lists cannot be sorted
```
Comment (emilk) [inline crates/re_arrow_store/src/store_polars.rs:131]: I don't get this line. `rerun.` is the prefix for official components. Why are they different from `ext.` components? And if it is lists that can't be sorted, why not check whether the column contains lists instead?

Or should this be an allow-list instead of a deny-list (name the columns we sort by, rather the ones we _don't_ sort by)?

File: crates/re_arrow_store/src/store_polars.rs [hunk 2]
```diff
@@ -89,25 +89,48 @@ impl DataStore {
...
+        // component columns themselves as they are internally lists of their own.
         let (sort_cols, sort_orders): (Vec<_>, Vec<_>) = [
-            has_timeless.then_some((IS_TIMELESS_COL, true)),
-            has_insert_ids.then_some((DataStore::insert_id_key().as_str(), false)),
+            df.column(TIMELESS_COL)
+                .is_ok()
+                .then_some((TIMELESS_COL, true)), // descending
+            df.column(insert_id_col)
+                .is_ok()
+                .then_some((insert_id_col, false)), // ascending
```
Comment (emilk) [inline crates/re_arrow_store/src/store_polars.rs:121]: very annoying that polars uses bools instead of an enum🤦‍♂️

File: crates/re_arrow_store/src/store_polars.rs (hunk 1 above)
Comment (teh-cmc) [reply crates/re_arrow_store/src/store_polars.rs:131]: Yeah I forgot about the `ext.` ones; you're right that a allow list should be better, I'll switch it up

**Review by emilk — APPROVED** [review]
