### PR TITLE
Fix ignoring nested `oneof` fields in `protobuf` MCAP messages

### LINKED ISSUE #12410: Rerun crashes when trying to load protobuf MCAP file
<!--
First look if there is already a similar bug report. If there is, upvote the issue with 👍
-->

**Describe the bug**
Rerun crashes when trying to load protobuf MCAP file

**To Reproduce**
1. Drag protobuf-encoded file into rerun or use the cmdline to open it
2. Observe crash

**Expected behavior**
Maybe some conversion error output or something, but no crash should happen.

**Backtrace**
With internal information redacted:
```
thread 'load_mcap("recovered.mcap"' panicked at 'StructBuilder (Schema { fields: [Field { name: "XX" }, Field { name: XX }, Field { name: "XX" }, Field { name: "XX" }, Field { name: "XX" }, Field { name: "XX" }, Field { name: "XX" }, Field { name: "XX" }, Field { name: "XX" }, Field { name: "XX" }], metadata: {} }) and field_builder with index 0 (Struct([Field { name: "XX", data_type: UInt64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: "XX", data_type: UInt32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }])) are of unequal lengths: (0 != 10).'
arrow-array-56.2.0/src/builder/struct_builder.rs:269
stack backtrace:
   6: core::panicking::panic_fmt
   7: arrow_array::builder::struct_builder::StructBuilder::validate_content::{{closure}}::panic_cold_display
   8: arrow_array::builder::struct_builder::StructBuilder::validate_content
   9: arrow_array::builder::struct_builder::StructBuilder::finish
  10: <re_mcap::layers::protobuf::ProtobufMessageParser as re_mcap::parsers::decode::MessageParser>::finalize
  11: <re_mcap::layers::MessageLayerRunner as re_mcap::layers::Layer>::process
  12: re_mcap::layers::ExecutionPlan::run
  13: re_data_loader::loader_mcap::load_mcap
  14: re_data_loader::loader_mcap::load_mcap_mmap
  15: std::sys::backtrace::__rust_begin_short_backtrace
  16: core::ops::function::FnOnce::call_once{{vtable.shim}}
  17: std::sys::pal::unix::thread::Thread::new::thread_start
  18: start_thread
             at pthread_create.c:442:8
  19: __GI___clone3
             at clone3.S:81:0
```
There are also some errors in the lead-up to the crash:
```
[2026-01-12T22:16:16Z ERROR re_mcap::layers] Failed to decode message on channel /XX/XX: missing protobuf field 8                                                                                                                                                                                                                                                       
[2026-01-12T22:16:16Z ERROR re_mcap::layers] Failed to decode message on channel /XX/XX: missing protobuf field 1  
```
These errors don't make sense to me because the fields are not `required` fields. They are `optional` according to the output of `mcap list schemas file.mcap`.

**Desktop:**
Ubuntu 22.04

**Rerun version**
```
rerun-cli 0.28.1 (base lance map_view nasm native_viewer oss_server perf_telemetry re_server release_full release_no_web_viewer web_viewer) [rustc 1.88.0 (6b00bc388 2025-06-23), LLVM 20.1.5] x86_64-unknown-linux-gnu prepare-release-0.28.1 ac98620, built 2025-12-19T21:06:08.748579589Z
Video features: av1 ffmpeg nasm
```

**Additional context**
The protobuf data is defined with `syntax = "proto3";`, where all data is optional by default, so it should be expected that some fields are missing.

### PR DESCRIPTION
**Pull request by grtlr**
### Related

* Follow up of #12436.
* Closes #12410.

### What

This PR fixes (and tests) ignoring of `oneof` fields in protobuf messages. Properly implementing `oneof` fields is tracked here:

* #11221

### CODE REVIEW

File: crates/store/re_mcap/src/layers/protobuf.rs [hunk 1]
```diff
@@ -288,6 +281,14 @@ fn append_value(
 
 fn struct_builder_from_message(message_descriptor: &MessageDescriptor) -> StructBuilder {
     // TODO(#11221): Support `oneof` values in protobuf MCAP files.
+    // Warn about oneof fields in this message (both top-level and nested)
+    if message_descriptor.oneofs().len() > 0 {
+        re_log::warn_once!(
+            "`oneof` in schema {} is not supported yet.",
```
Comment (MichaelGrupp) [inline crates/store/re_mcap/src/layers/protobuf.rs]: Maybe a bit clearer:
```suggestion
            "Ignoring {} message: Protobuf schemas containing `oneof` are not supported yet.",
```
