### PR TITLE
Dataframe API: remove control columns from public surface

### LINKED ISSUE #7599: Remove ControlColumn / RowId from the public APIs
Having a whole category of ControlColumnSelector / ControlColumnDescriptor at the query layer adds a lot of complexity just for RowId.

Also, we eventually want RowId to be able to act like an Index in the future. For example: `view(index=("frame", "row_id"), ...`,

So even when we expose it, we will want to make RowId a special kind of IndexColumn rather than a ControlColumn.

It may be helpful to give this a reserved name so that we can select("row_id", "log_time", ...) without worrying about ambiguity of a user-logged `row_id` timeline.

Short-term we don't need this to be an allowable timeline at all.

Longer term it would be nice to be able to use this as an index at query time, but this doesn't need to happen for 0.19.

Notably this could woud likely benefit from a specialized implementation that allowed for some documented exceptions:
- Sorting on RowId is less important
  - Since RowIds should be unique, sorted by chunk rather than row_id would let this be far more performant and return chunk-sized record-batches without the need to do any joining.
- LatestAt doesn't make sense on RowId index.

### PR DESCRIPTION
**Pull request by teh-cmc**
* Prevents ~hard~annoying-to-solve cross-feature interactions in the new API implementation.
* Fixes #7599

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using examples from latest `main` build: [rerun.io/viewer](https://rerun.io/viewer/pr/7612?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [rerun.io/viewer](https://rerun.io/viewer/pr/7612?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!
* [x] If have noted any breaking changes to the log API in `CHANGELOG.md` and the migration guide

- [PR Build Summary](https://build.rerun.io/pr/7612)
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

File: crates/viewer/re_space_view_dataframe/src/dataframe_ui.rs [hunk 1]
```diff
@@ -393,7 +371,7 @@ impl<'a> egui_table::TableDelegate for DataframeTableDelegate<'a> {
                     column.data_ui(
                         self.ctx,
                         ui,
-                        row_id,
+                        RowId::ZERO,
```
Comment (teh-cmc) [inline crates/viewer/re_space_view_dataframe/src/dataframe_ui.rs:374]: Will that be an issue @abey79 ? (I tried to test this myself, but there seems to be an unrelated issue on `main` at the moment, see #tech).

**Review by jleibs — APPROVED** [review]

File: crates/viewer/re_space_view_dataframe/src/dataframe_ui.rs (hunk 1 above)
Comment (abey79) [reply crates/viewer/re_space_view_dataframe/src/dataframe_ui.rs:374]: This `row_id` ultimately is routed to `ComponentUiRegistry::ui_raw`, which takes an `Option<RowId>`. If we no longer have a row id there, the correct patch is to remove it entirely and pass `None` in the `ui_raw` call site  (`fn data_ui()`  in `display_record_batch.rs`).

As to the effect of doing that, I can't even track where its actually used --> discussion on slack.

Comment (abey79) [reply crates/viewer/re_space_view_dataframe/src/dataframe_ui.rs:374]: If this blocks you, remove that `RowId` thing entirely and we'll copy later if that proves to be an actual issue. Gut feeling: some hovertooltip might end up being incorrect in edge cases.

Comment (abey79) [reply crates/viewer/re_space_view_dataframe/src/dataframe_ui.rs]: As discussed, the effect of this removal will be that the table cell will no longer preview tiny thumbnail of images. This actually is a good thing because this has performance issues anyways. Some more background in:
- #7617.
