### PR TITLE
renderer: fix the groupby logic in mesh instancing

### LINKED ISSUE #1530: Mesh instancing/batching is broken
We're rendering only one mesh per drawcall right now despite our instancing machinery. The `group_by` https://github.com/rerun-io/rerun/blob/main/crates/re_renderer/src/renderer/mesh_renderer.rs#L166 on the mesh_renderer instance creation doesn't seem to group correctly - apparently compare methods on the mesh handles don't work as expected.

### PR DESCRIPTION
**Pull request by teh-cmc**
Fixes #1530

### CODE REVIEW

File: crates/re_renderer/src/renderer/mesh_renderer.rs [hunk 1]
```diff
@@ -175,6 +175,16 @@ impl MeshDrawData {
             },
         );
 
+        let mut instances_by_mesh: HashMap<_, Vec<_>> = HashMap::with_capacity(instances.len());
```
Comment (teh-cmc) [inline crates/re_renderer/src/renderer/mesh_renderer.rs:178]: not allocating the right thing

**Review by Wumpf — APPROVED** [review]
yay, thank you!
