### PR TITLE
Fix indeterministic redundancy check for space view spawning heuristic

### LINKED ISSUE #5258: Unnecessary Camera space created in structure from motion scene
https://app.rerun.io/pr/5249/index.html

Related to
* #5167

(but I think I already found a different separate bug source here)

### PR DESCRIPTION
**Pull request by Wumpf**
### What

* Fixes #5258

The mechanism we used for determining whether a "recommended" space view is redundant was flawed in several ways, causing it to be order hash map order dependent among other things.

Small improvement to 3d space view heuristic that stop it from considering subspaces with ViewCoordinates.

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using newly built examples: [app.rerun.io](https://app.rerun.io/pr/5266/index.html)
  * Using examples from latest `main` build: [app.rerun.io](https://app.rerun.io/pr/5266/index.html?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [app.rerun.io](https://app.rerun.io/pr/5266/index.html?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!

- [PR Build Summary](https://build.rerun.io/pr/5266)
- [Docs preview](https://rerun.io/preview/8cce4d41110675bca314b675d962644ea0fdf394/docs) 
- [Examples preview](https://rerun.io/preview/8cce4d41110675bca314b675d962644ea0fdf394/examples) 
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

### CODE REVIEW

File: crates/re_viewport/src/viewport.rs [hunk 1]
```diff
@@ -333,46 +332,68 @@ impl<'a, 'b> Viewport<'a, 'b> {
...
+                .recommended_space_views
+                .into_iter()
+                .filter(|recommended_view| {
+                    existing_path_filters.iter().all(|existing_filter| {
+                        !existing_filter.is_superset_of(&recommended_view.query_filter)
+                    })
+                })
+                .collect::<Vec<_>>();
+
+            // Remove all space views that redundant within the remaining recommendation.
```
Comment (Wumpf) [inline crates/re_viewport/src/viewport.rs:366]:
```suggestion
            // Remove all space views that are redundant within the remaining recommendation.
```

**Review by Wumpf — COMMENTED** [review]
built this in pair programming together with @jleibs and reviewed it myself now again. Looking still good after a couple of days, so merging (;
