### PR TITLE
Fix handling very large meshes & plots (allow maximum available gpu buffers)

### LINKED ISSUE #3928: Crash when supplying too large mesh
Similar to too large textures previously, we have issues with too large buffers. Easiest way to get a too large buffer is to supply a too large mesh through any api.

Just as before we need more extensive vetting of user supplied data _and_ need to tell wgpu to allow the largest possible buffer.

### LINKED ISSUE #5051: Crash on un-aggregated SeriesPoint for 1M series
Repro:
data: [1M_line_series.rrd.zip](https://github.com/rerun-io/rerun/files/14176705/1M_line_series.rrd.zip)

```bash
RUST_LOG=debug cargo r -p rerun-cli --no-default-features --features native_viewer --release -- -j1 1M_line_series.rrd
```

Setup:

https://github.com/rerun-io/rerun/assets/2624717/1aa24ed7-a8f1-49d3-9bfb-828e4add59bf

CLI output:
```bash
[2024-02-06T08:15:16Z DEBUG re_memory::memory_limit] Setting memory limit to 24.0 GiB, which is 75% of total available memory (32.0 GiB).
[2024-02-06T08:15:16Z INFO  re_data_source::load_file] Loading "1M_line_series.rrd"…
[2024-02-06T08:15:16Z DEBUG re_data_source::data_loader::loader_rrd] Loading rrd data from filesystem… filepath="1M_line_series.rrd" loader="rerun.data_loaders.Rrd"
[2024-02-06T08:15:16Z DEBUG re_data_source::load_file] compatible loader found loader="rerun.data_loaders.Rrd" path="1M_line_series.rrd"
[2024-02-06T08:15:16Z DEBUG eframe] Using the wgpu renderer
[2024-02-06T08:15:16Z DEBUG re_data_source::load_file] compatible loader found loader="rerun.data_loaders.Archetype" path="1M_line_series.rrd"
[2024-02-06T08:15:16Z DEBUG re_data_source::data_loader::loader_external] Found duplicated data-loader in $PATH name="rerun-loader-docx" paths=["/Users/niko/.local/bin/rerun-loader-docx", "/Users/niko/.local/bin/rerun-loader-docx"]
[2024-02-06T08:15:16Z DEBUG re_data_source::data_loader::loader_external] Found duplicated data-loader in $PATH name="rerun-loader-tfrecord" paths=["/Users/niko/.local/bin/rerun-loader-tfrecord", "/Users/niko/.local/bin/rerun-loader-tfrecord"]
[2024-02-06T08:15:16Z DEBUG re_data_source::data_loader::loader_external] Loading data from filesystem using external loader… filepath="1M_line_series.rrd" loader="/Users/niko/.local/bin/rerun-loader-docx"
[2024-02-06T08:15:16Z DEBUG re_data_source::data_loader::loader_external] Loading data from filesystem using external loader… filepath="1M_line_series.rrd" loader="/Users/niko/.local/bin/rerun-loader-tfrecord"
[2024-02-06T08:15:16Z DEBUG eframe::native::wgpu_integration] Event::Resumed
[2024-02-06T08:15:16Z DEBUG eframe::native::file_storage] Loading app state from "/Users/niko/Library/Application Support/rerun/app.ron"…
[2024-02-06T08:15:16Z DEBUG egui_wgpu] Picked the only available wgpu adapter: backend: Metal, device_type: IntegratedGpu, name: "Apple M1 Pro"
[2024-02-06T08:15:16Z DEBUG re_renderer::context] wgpu adapter backend: Metal, device_type: IntegratedGpu, name: "Apple M1 Pro"
[2024-02-06T08:15:16Z DEBUG egui::context] Loading new font definitions
[2024-02-06T08:15:19Z DEBUG re_viewer] Shutting down ui_waker thread
[2024-02-06T08:15:19Z DEBUG re_viewer::app] Opening a new recording: StoreInfo { application_id: ApplicationId("rerun_example_plot_dashboard_stress"), store_id: StoreId { kind: Recording, id: "ac487959-f0b2-4dc2-9a9f-d14aeadbc578" }, is_official_example: false, started: "2024-02-05 21:04:49.408498Z", store_source: RustSdk { rustc_version: "1.74.0 (79e9716c9 2023-11-13)", llvm_version: "17.0.4" }, store_kind: Recording }
[2024-02-06T08:15:19Z DEBUG re_viewer::store_hub] Trying to load blueprint for rerun_example_plot_dashboard_stress from "/Users/niko/Library/Application Support/rerun/blueprints/rerun_example_plot_dashboard_stress.blueprint"
[2024-02-06T08:15:19Z DEBUG re_viewer::store_hub] Switching blueprint for ApplicationId("rerun_example_plot_dashboard_stress") to StoreId { kind: Blueprint, id: "rerun_example_plot_dashboard_stress" }
[2024-02-06T08:15:36Z DEBUG re_viewer::app] Data source file://1M_line_series.rrd has left
[2024-02-06T08:15:46Z DEBUG re_viewer::store_hub] Saving blueprint for <welcome screen> to "/Users/niko/Library/Application Support/rerun/blueprints/-welcome-screen--e59dfa2c766d0b8f.blueprint"
[2024-02-06T08:15:46Z DEBUG re_viewer::store_hub] Saving blueprint for rerun_example_plot_dashboard_stress to "/Users/niko/Library/Application Support/rerun/blueprints/rerun_example_plot_dashboard_stress.blueprint"
[2024-02-06T08:16:22Z DEBUG re_viewer_context::space_view::view_query] Overriding /space_view/8e4a5141-e7eb-4e72-82e0-fc12846f7abf with EntityProperties { visible: true, visible_history: ExtraQueryHistory { enabled: false, nanos: VisibleHistory { from: Infinite, to: Infinite }, sequences: VisibleHistory { from: Infinite, to: Infinite } }, interactive: true, color_mapper: Auto(Colormap(Turbo)), pinhole_image_plane_distance: Auto(0.0), backproject_depth: Auto(true), depth_from_world_scale: Auto(1.0), backproject_radius_scale: Auto(1.0), transform_3d_visible: Auto(false), transform_3d_size: Auto(1.0), show_legend: Auto(true), legend_location: None, time_series_aggregator: UserEdited(Off) }

thread 'main' panicked at 'Failed to create staging buffer for index data'
egui-wgpu/src/renderer.rs:834
stack backtrace:


Troubleshooting Rerun: https://www.rerun.io/docs/getting-started/troubleshooting
Report bugs: https://github.com/rerun-io/rerun/issues
```

### PR DESCRIPTION
**Pull request by Wumpf**
### What

We already did this for textures, was overdue to do it for buffers as well.

* fixes #3928
* fixes #5051

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using newly built examples: [app.rerun.io](https://app.rerun.io/pr/5053/index.html)
  * Using examples from latest `main` build: [app.rerun.io](https://app.rerun.io/pr/5053/index.html?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [app.rerun.io](https://app.rerun.io/pr/5053/index.html?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG

- [PR Build Summary](https://build.rerun.io/pr/5053)
- [Docs preview](https://rerun.io/preview/3d6c0ddd06db9e8500fd715637e6cbf30c08ab06/docs) 
- [Examples preview](https://rerun.io/preview/3d6c0ddd06db9e8500fd715637e6cbf30c08ab06/examples) 
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

### CODE REVIEW

File: crates/re_renderer/src/config.rs [hunk 1]
```diff
@@ -72,6 +72,11 @@ pub struct DeviceCaps {
     /// Since this has a direct effect on the image sizes & screen resolution a user can use, we always pick the highest possible.
     pub max_texture_dimension2d: u32,
 
+    /// Maximum buffer size in bytes.
+    ///
+    /// Since this has a direct effect much data a user can wrangle on the gpu, we always pick the highest possible.
```
Comment (Wumpf) [inline crates/re_renderer/src/config.rs:77]:
```suggestion
    /// Since this has a direct effect on much data a user can wrangle on the gpu, we always pick the highest possible.
```

**Review by teh-cmc — APPROVED** [review]
Confirmed working on my end -- I can now look at 4M non-aggregated points on a plot :scream:

**Comment by Wumpf** [comment]
@nikolausWest confirmed as well
