### PR TITLE
Fix colormap picker preview & show it for depth point clouds as well

### LINKED ISSUE #3242: Colormap selection preview is sometimes bugged, sometimes not there at all
Here's a colormap selector for depth clouds -- no preview at all:
image

And here's a colormap selector for tensors -- layout is broken:
image

### PR DESCRIPTION
**Pull request by Wumpf**
### What

* Fixes #3242

image

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested [demo.rerun.io](https://demo.rerun.io/pr/3373) (if applicable)

- [PR Build Summary](https://build.rerun.io/pr/3373)
- [Docs preview](https://rerun.io/preview/73ad32ebf606b6d91192ca5c490d0b158c79f769/docs) 
- [Examples preview](https://rerun.io/preview/73ad32ebf606b6d91192ca5c490d0b158c79f769/examples) 
- [Recent benchmark results](https://ref.rerun.io/dev/bench/)
- [Wasm size tracking](https://ref.rerun.io/dev/sizes/)

### CODE REVIEW

File: crates/re_space_view_tensor/src/space_view_class.rs [hunk 1]
```diff
@@ -430,10 +430,11 @@ fn colormap_preview_ui(
     re_tracing::profile_function!();
 
     let desired_size = egui::vec2(128.0, 16.0);
-    let (rect, response) = ui.allocate_exact_size(desired_size, egui::Sense::hover());
+    let (response, painter) = ui.allocate_painter(desired_size, egui::Sense::hover());
```
Comment (emilk) [inline crates/re_space_view_tensor/src/space_view_class.rs]: This creates a `painter` with a smaller `clip_rect`, so that is probably the change that made it work.

This means `render_image` still has a footgun: an undocumented requirement that the clip rectangle is the same as the viewport rectangle.

This is a new requirement (it obviously wasn't there when the colormap gradient code was first written) so it would probably be good to understand it a bit more.

I am curious what happens, for instance, if the painter clip rectangle is _smaller_ than the viewport (e.g. when scrolling an area where we call `render_image`). It seems likely that will also be buggy.

File: crates/re_viewer/src/ui/selection_panel.rs [hunk 2]
```diff
@@ -409,32 +411,50 @@ fn entity_props_ui(
...
+                                re_renderer::Colormap::Magma => Colormap::Magma,
+                                re_renderer::Colormap::Inferno => Colormap::Inferno,
+                            };
+                            entity_props.color_mapper =
+                                EditableAutoValue::UserEdited(ColorMapper::Colormap(value));
+                        }
+                        colormap_preview_ui(ctx.render_ctx, ui, option);
+                        ui.end_row();
+                    }
+                });
```
Comment (emilk) [inline crates/re_viewer/src/ui/selection_panel.rs:457]: it looks like you copied the code from `ColorMapping::ui` to here? Why not create a reusable `fn colormap_dropdown_button_ui` instead? It can return the new selection (if any) so that at the call-site it can be assigned to an `EditableAutoValue` as needed here.

It will make it much easier to add the same code to a third place, and will also reduce the chance of copy-paste errors (like having `ui.style_mut().wrap = Some(false);` in only one of the dropdowns).

The essential question should be this: should our colormap select dropdown look the same? Then they should be the same function

**Comment by teh-cmc** [comment]
(Speaking as a color n00b) shouldn't we fix the gamma here? That grayscale isn't much of a scale :grimacing: 
image

File: crates/re_space_view_tensor/src/space_view_class.rs (hunk 1 above)
Comment (Wumpf) [reply crates/re_space_view_tensor/src/space_view_class.rs]: spot on, the **actual** error was a very simple mistake in the re_renderer callback!

File: crates/re_viewer_context/src/gpu_bridge/re_renderer_callback.rs [hunk 3]
```diff
@@ -116,7 +116,7 @@ impl egui_wgpu::CallbackTrait for ReRendererCallback {
             return;
         };
 
-        let screen_position = (info.clip_rect.min.to_vec2() * info.pixels_per_point).round();
+        let screen_position = (info.viewport.min.to_vec2() * info.pixels_per_point).round();
```
Comment (Wumpf) [inline crates/re_viewer_context/src/gpu_bridge/re_renderer_callback.rs:119]: **this** is the actual bugfix!

Comment (emilk) [reply crates/re_viewer_context/src/gpu_bridge/re_renderer_callback.rs:119]: ah, nice one!

**Review by emilk — APPROVED** [review]
